name: ✨ Feature Request
description: Suggest a new feature or improvement
title: "[Feature]: "
labels: ["enhancement", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! We love hearing ideas from the community.

  - type: textarea
    id: description
    attributes:
      label: Feature Description
      description: A clear and concise description of the feature you'd like.
      placeholder: I would like to see...
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve? Is it related to a frustration?
      placeholder: I'm always frustrated when...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like
      placeholder: My ideal solution would be...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Any alternative solutions or features you've considered?
      placeholder: I also thought about...

  - type: dropdown
    id: category
    attributes:
      label: Feature Category
      description: Which area of the app does this relate to?
      options:
        - 3D Muscle Visualization
        - Workout Tracking
        - Exercise Library
        - User Profile & Stats
        - Social Features
        - Gamification (XP, Achievements)
        - Mobile Experience
        - Accessibility
        - Performance
        - Developer Experience
        - Other
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Nice to have - Would be cool
        - Important - Would significantly improve my experience
        - Critical - I really need this feature
    validations:
      required: true

  - type: dropdown
    id: contribution
    attributes:
      label: Willing to Contribute?
      description: Would you be interested in helping implement this feature?
      options:
        - "Yes - I can implement this"
        - "Yes - I can help with design/testing"
        - "No - But I can provide feedback"
        - "Not sure - Need guidance"

  - type: textarea
    id: mockups
    attributes:
      label: Mockups / Examples
      description: If you have mockups, sketches, or examples from other apps, share them here
      placeholder: Drag and drop images or paste URLs

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other context or screenshots about the feature request
      placeholder: Add any other context here...

  - type: checkboxes
    id: terms
    attributes:
      label: Checklist
      options:
        - label: I have searched existing issues and feature requests
          required: true
        - label: This feature aligns with MuscleMap's focus on fitness visualization
          required: true
