/**
 * Achievement Definitions Seed File
 *
 * 50+ achievements across 8 categories covering all aspects of the MuscleMap experience.
 *
 * Categories:
 * - milestone: Workout counts and general progress markers
 * - streak: Consistency achievements for consecutive day activity
 * - record: Personal records and strength milestones
 * - first_time: First-time accomplishments
 * - social: Community engagement achievements
 * - top_rank: Leaderboard and competition achievements
 * - special: Holiday and rare achievements
 * - nutrition: Nutrition-related achievements (if enabled)
 *
 * Tiers: bronze (50 XP), silver (100 XP), gold (250 XP), platinum (500 XP), diamond (1000 XP)
 * Rarity: common (60%), uncommon (25%), rare (10%), epic (4%), legendary (1%)
 */

export interface AchievementSeed {
  key: string;
  name: string;
  description: string;
  category: 'milestone' | 'streak' | 'record' | 'first_time' | 'social' | 'top_rank' | 'special' | 'nutrition';
  tier: 'bronze' | 'silver' | 'gold' | 'platinum' | 'diamond';
  rarity: 'common' | 'uncommon' | 'rare' | 'epic' | 'legendary';
  points: number; // XP reward: bronze=50, silver=100, gold=250, platinum=500, diamond=1000
  icon: string;
  enabled?: boolean;
  requires_verification?: boolean;
}

// XP reward mapping by tier
export const TIER_XP_REWARDS = {
  bronze: 50,
  silver: 100,
  gold: 250,
  platinum: 500,
  diamond: 1000,
} as const;

// ============================================
// WORKOUT MILESTONES
// ============================================
export const workoutMilestoneAchievements: AchievementSeed[] = [
  {
    key: 'first_workout',
    name: 'First Steps',
    description: 'Complete your first workout',
    category: 'milestone',
    tier: 'bronze',
    rarity: 'common',
    points: TIER_XP_REWARDS.bronze,
    icon: '🎯',
  },
  {
    key: 'workouts_5',
    name: 'Getting Started',
    description: 'Complete 5 workouts',
    category: 'milestone',
    tier: 'bronze',
    rarity: 'common',
    points: TIER_XP_REWARDS.bronze,
    icon: '💪',
  },
  {
    key: 'workouts_10',
    name: 'Committed',
    description: 'Complete 10 workouts',
    category: 'milestone',
    tier: 'bronze',
    rarity: 'common',
    points: TIER_XP_REWARDS.bronze,
    icon: '🏋️',
  },
  {
    key: 'workouts_25',
    name: 'Building Momentum',
    description: 'Complete 25 workouts',
    category: 'milestone',
    tier: 'silver',
    rarity: 'common',
    points: TIER_XP_REWARDS.silver,
    icon: '🚀',
  },
  {
    key: 'workouts_50',
    name: 'Dedicated',
    description: 'Complete 50 workouts',
    category: 'milestone',
    tier: 'silver',
    rarity: 'uncommon',
    points: TIER_XP_REWARDS.silver,
    icon: '⭐',
  },
  {
    key: 'workouts_100',
    name: 'Century Club',
    description: 'Complete 100 workouts',
    category: 'milestone',
    tier: 'gold',
    rarity: 'uncommon',
    points: TIER_XP_REWARDS.gold,
    icon: '💯',
  },
  {
    key: 'workouts_250',
    name: 'Seasoned Athlete',
    description: 'Complete 250 workouts',
    category: 'milestone',
    tier: 'gold',
    rarity: 'rare',
    points: TIER_XP_REWARDS.gold,
    icon: '🏆',
  },
  {
    key: 'workouts_500',
    name: 'Iron Will',
    description: 'Complete 500 workouts',
    category: 'milestone',
    tier: 'platinum',
    rarity: 'rare',
    points: TIER_XP_REWARDS.platinum,
    icon: '🔥',
  },
  {
    key: 'workouts_1000',
    name: 'Legendary',
    description: 'Complete 1,000 workouts',
    category: 'milestone',
    tier: 'diamond',
    rarity: 'epic',
    points: TIER_XP_REWARDS.diamond,
    icon: '👑',
  },
  {
    key: 'workouts_2500',
    name: 'Immortal',
    description: 'Complete 2,500 workouts',
    category: 'milestone',
    tier: 'diamond',
    rarity: 'legendary',
    points: TIER_XP_REWARDS.diamond,
    icon: '⚡',
  },
];

// ============================================
// STREAK ACHIEVEMENTS
// ============================================
export const streakAchievements: AchievementSeed[] = [
  {
    key: 'streak_3',
    name: 'Three-peat',
    description: 'Log workouts 3 days in a row',
    category: 'streak',
    tier: 'bronze',
    rarity: 'common',
    points: TIER_XP_REWARDS.bronze,
    icon: '🔥',
  },
  {
    key: 'streak_7',
    name: 'Week Warrior',
    description: 'Log workouts 7 days in a row',
    category: 'streak',
    tier: 'bronze',
    rarity: 'common',
    points: TIER_XP_REWARDS.bronze,
    icon: '📅',
  },
  {
    key: 'streak_14',
    name: 'Fortnight Fighter',
    description: 'Log workouts 14 days in a row',
    category: 'streak',
    tier: 'silver',
    rarity: 'uncommon',
    points: TIER_XP_REWARDS.silver,
    icon: '💪',
  },
  {
    key: 'streak_30',
    name: 'Monthly Grind',
    description: 'Log workouts 30 days in a row',
    category: 'streak',
    tier: 'gold',
    rarity: 'rare',
    points: TIER_XP_REWARDS.gold,
    icon: '🌟',
  },
  {
    key: 'streak_60',
    name: 'Two Month Titan',
    description: 'Log workouts 60 days in a row',
    category: 'streak',
    tier: 'gold',
    rarity: 'rare',
    points: TIER_XP_REWARDS.gold,
    icon: '⚡',
  },
  {
    key: 'streak_100',
    name: 'Century Streak',
    description: 'Log workouts 100 days in a row',
    category: 'streak',
    tier: 'platinum',
    rarity: 'epic',
    points: TIER_XP_REWARDS.platinum,
    icon: '💎',
  },
  {
    key: 'streak_180',
    name: 'Half-Year Hero',
    description: 'Log workouts 180 days in a row',
    category: 'streak',
    tier: 'platinum',
    rarity: 'epic',
    points: TIER_XP_REWARDS.platinum,
    icon: '🏅',
  },
  {
    key: 'streak_365',
    name: 'Year of Iron',
    description: 'Log workouts 365 days in a row',
    category: 'streak',
    tier: 'diamond',
    rarity: 'legendary',
    points: TIER_XP_REWARDS.diamond,
    icon: '👑',
  },
];

// ============================================
// STRENGTH RECORDS
// ============================================
export const strengthRecordAchievements: AchievementSeed[] = [
  {
    key: 'first_pr',
    name: 'Personal Best',
    description: 'Set your first personal record',
    category: 'record',
    tier: 'bronze',
    rarity: 'common',
    points: TIER_XP_REWARDS.bronze,
    icon: '📈',
  },
  {
    key: 'prs_10',
    name: 'Record Setter',
    description: 'Set 10 personal records',
    category: 'record',
    tier: 'silver',
    rarity: 'common',
    points: TIER_XP_REWARDS.silver,
    icon: '🎯',
  },
  {
    key: 'prs_25',
    name: 'PR Machine',
    description: 'Set 25 personal records',
    category: 'record',
    tier: 'silver',
    rarity: 'uncommon',
    points: TIER_XP_REWARDS.silver,
    icon: '🔥',
  },
  {
    key: 'prs_50',
    name: 'Record Breaker',
    description: 'Set 50 personal records',
    category: 'record',
    tier: 'gold',
    rarity: 'rare',
    points: TIER_XP_REWARDS.gold,
    icon: '💪',
  },
  {
    key: 'prs_100',
    name: 'PR Legend',
    description: 'Set 100 personal records',
    category: 'record',
    tier: 'platinum',
    rarity: 'epic',
    points: TIER_XP_REWARDS.platinum,
    icon: '🏆',
  },
  // Bodyweight benchmark achievements
  {
    key: 'bench_bodyweight',
    name: 'Bodyweight Bench',
    description: 'Bench press your bodyweight for 1 rep',
    category: 'record',
    tier: 'silver',
    rarity: 'uncommon',
    points: TIER_XP_REWARDS.silver,
    icon: '🏋️',
  },
  {
    key: 'bench_1_5x_bodyweight',
    name: 'Strong Bench',
    description: 'Bench press 1.5x your bodyweight for 1 rep',
    category: 'record',
    tier: 'gold',
    rarity: 'rare',
    points: TIER_XP_REWARDS.gold,
    icon: '💪',
  },
  {
    key: 'bench_2x_bodyweight',
    name: 'Elite Bench',
    description: 'Bench press 2x your bodyweight for 1 rep',
    category: 'record',
    tier: 'diamond',
    rarity: 'legendary',
    points: TIER_XP_REWARDS.diamond,
    icon: '👑',
    requires_verification: true,
  },
  {
    key: 'squat_bodyweight',
    name: 'Bodyweight Squat',
    description: 'Squat your bodyweight for 1 rep',
    category: 'record',
    tier: 'bronze',
    rarity: 'common',
    points: TIER_XP_REWARDS.bronze,
    icon: '🦵',
  },
  {
    key: 'squat_1_5x_bodyweight',
    name: 'Strong Squat',
    description: 'Squat 1.5x your bodyweight for 1 rep',
    category: 'record',
    tier: 'silver',
    rarity: 'uncommon',
    points: TIER_XP_REWARDS.silver,
    icon: '🏋️',
  },
  {
    key: 'squat_2x_bodyweight',
    name: 'Elite Squat',
    description: 'Squat 2x your bodyweight for 1 rep',
    category: 'record',
    tier: 'gold',
    rarity: 'rare',
    points: TIER_XP_REWARDS.gold,
    icon: '💪',
  },
  {
    key: 'squat_2_5x_bodyweight',
    name: 'Legendary Squat',
    description: 'Squat 2.5x your bodyweight for 1 rep',
    category: 'record',
    tier: 'diamond',
    rarity: 'legendary',
    points: TIER_XP_REWARDS.diamond,
    icon: '👑',
    requires_verification: true,
  },
  {
    key: 'deadlift_1_5x_bodyweight',
    name: 'Strong Deadlift',
    description: 'Deadlift 1.5x your bodyweight for 1 rep',
    category: 'record',
    tier: 'bronze',
    rarity: 'common',
    points: TIER_XP_REWARDS.bronze,
    icon: '🏋️',
  },
  {
    key: 'deadlift_2x_bodyweight',
    name: 'Elite Deadlift',
    description: 'Deadlift 2x your bodyweight for 1 rep',
    category: 'record',
    tier: 'silver',
    rarity: 'uncommon',
    points: TIER_XP_REWARDS.silver,
    icon: '💪',
  },
  {
    key: 'deadlift_2_5x_bodyweight',
    name: 'Legendary Deadlift',
    description: 'Deadlift 2.5x your bodyweight for 1 rep',
    category: 'record',
    tier: 'gold',
    rarity: 'rare',
    points: TIER_XP_REWARDS.gold,
    icon: '🔥',
  },
  {
    key: 'deadlift_3x_bodyweight',
    name: 'Immortal Deadlift',
    description: 'Deadlift 3x your bodyweight for 1 rep',
    category: 'record',
    tier: 'diamond',
    rarity: 'legendary',
    points: TIER_XP_REWARDS.diamond,
    icon: '👑',
    requires_verification: true,
  },
];

// ============================================
// VOLUME ACHIEVEMENTS
// ============================================
export const volumeAchievements: AchievementSeed[] = [
  {
    key: 'volume_10k_kg',
    name: 'Ten Ton Club',
    description: 'Lift a total of 10,000 kg in a single workout',
    category: 'milestone',
    tier: 'silver',
    rarity: 'uncommon',
    points: TIER_XP_REWARDS.silver,
    icon: '🏋️',
  },
  {
    key: 'volume_100k_kg_total',
    name: 'Iron Apprentice',
    description: 'Lift 100,000 kg total across all workouts',
    category: 'milestone',
    tier: 'silver',
    rarity: 'uncommon',
    points: TIER_XP_REWARDS.silver,
    icon: '⚙️',
  },
  {
    key: 'volume_500k_kg_total',
    name: 'Iron Master',
    description: 'Lift 500,000 kg total across all workouts',
    category: 'milestone',
    tier: 'gold',
    rarity: 'rare',
    points: TIER_XP_REWARDS.gold,
    icon: '🔩',
  },
  {
    key: 'volume_1m_kg_total',
    name: 'Million Kilo Club',
    description: 'Lift 1,000,000 kg total across all workouts',
    category: 'milestone',
    tier: 'platinum',
    rarity: 'epic',
    points: TIER_XP_REWARDS.platinum,
    icon: '💎',
  },
  {
    key: 'volume_5m_kg_total',
    name: 'Iron Legend',
    description: 'Lift 5,000,000 kg total across all workouts',
    category: 'milestone',
    tier: 'diamond',
    rarity: 'legendary',
    points: TIER_XP_REWARDS.diamond,
    icon: '👑',
  },
];

// ============================================
// EXERCISE MASTERY
// ============================================
export const exerciseMasteryAchievements: AchievementSeed[] = [
  {
    key: 'mastery_chest_all',
    name: 'Chest Champion',
    description: 'Complete all chest exercises at least once',
    category: 'milestone',
    tier: 'gold',
    rarity: 'rare',
    points: TIER_XP_REWARDS.gold,
    icon: '💪',
  },
  {
    key: 'mastery_back_all',
    name: 'Back Beast',
    description: 'Complete all back exercises at least once',
    category: 'milestone',
    tier: 'gold',
    rarity: 'rare',
    points: TIER_XP_REWARDS.gold,
    icon: '🦍',
  },
  {
    key: 'mastery_legs_all',
    name: 'Leg Legend',
    description: 'Complete all leg exercises at least once',
    category: 'milestone',
    tier: 'gold',
    rarity: 'rare',
    points: TIER_XP_REWARDS.gold,
    icon: '🦵',
  },
  {
    key: 'mastery_arms_all',
    name: 'Arm Authority',
    description: 'Complete all arm exercises at least once',
    category: 'milestone',
    tier: 'gold',
    rarity: 'rare',
    points: TIER_XP_REWARDS.gold,
    icon: '💪',
  },
  {
    key: 'mastery_core_all',
    name: 'Core Commander',
    description: 'Complete all core exercises at least once',
    category: 'milestone',
    tier: 'gold',
    rarity: 'rare',
    points: TIER_XP_REWARDS.gold,
    icon: '🎯',
  },
  {
    key: 'mastery_shoulders_all',
    name: 'Shoulder Sovereign',
    description: 'Complete all shoulder exercises at least once',
    category: 'milestone',
    tier: 'gold',
    rarity: 'rare',
    points: TIER_XP_REWARDS.gold,
    icon: '🏔️',
  },
  {
    key: 'mastery_exercise_explorer',
    name: 'Exercise Explorer',
    description: 'Try 50 different exercises',
    category: 'milestone',
    tier: 'silver',
    rarity: 'uncommon',
    points: TIER_XP_REWARDS.silver,
    icon: '🗺️',
  },
  {
    key: 'mastery_exercise_master',
    name: 'Exercise Master',
    description: 'Try 100 different exercises',
    category: 'milestone',
    tier: 'gold',
    rarity: 'rare',
    points: TIER_XP_REWARDS.gold,
    icon: '📚',
  },
];

// ============================================
// SOCIAL ACHIEVEMENTS
// ============================================
export const socialAchievements: AchievementSeed[] = [
  {
    key: 'first_high_five',
    name: 'First High Five',
    description: 'Give or receive your first high five',
    category: 'social',
    tier: 'bronze',
    rarity: 'common',
    points: TIER_XP_REWARDS.bronze,
    icon: '🙏',
  },
  {
    key: 'high_fives_10',
    name: 'High Five Enthusiast',
    description: 'Give 10 high fives',
    category: 'social',
    tier: 'bronze',
    rarity: 'common',
    points: TIER_XP_REWARDS.bronze,
    icon: '✋',
  },
  {
    key: 'high_fives_100',
    name: 'High Five Hero',
    description: 'Give 100 high fives',
    category: 'social',
    tier: 'silver',
    rarity: 'uncommon',
    points: TIER_XP_REWARDS.silver,
    icon: '👋',
  },
  {
    key: 'first_crew_join',
    name: 'Crew Member',
    description: 'Join your first crew',
    category: 'social',
    tier: 'bronze',
    rarity: 'common',
    points: TIER_XP_REWARDS.bronze,
    icon: '👥',
  },
  {
    key: 'crew_create',
    name: 'Crew Captain',
    description: 'Create a crew',
    category: 'social',
    tier: 'silver',
    rarity: 'uncommon',
    points: TIER_XP_REWARDS.silver,
    icon: '⚓',
  },
  {
    key: 'first_hangout_join',
    name: 'Hangout Rookie',
    description: 'Join your first hangout',
    category: 'social',
    tier: 'bronze',
    rarity: 'common',
    points: TIER_XP_REWARDS.bronze,
    icon: '🏠',
  },
  {
    key: 'hangout_create',
    name: 'Hangout Host',
    description: 'Create a hangout',
    category: 'social',
    tier: 'silver',
    rarity: 'uncommon',
    points: TIER_XP_REWARDS.silver,
    icon: '🎉',
  },
  {
    key: 'hangouts_5',
    name: 'Social Butterfly',
    description: 'Join 5 different hangouts',
    category: 'social',
    tier: 'silver',
    rarity: 'uncommon',
    points: TIER_XP_REWARDS.silver,
    icon: '🦋',
  },
  {
    key: 'hangouts_10',
    name: 'Community Leader',
    description: 'Join 10 different hangouts',
    category: 'social',
    tier: 'gold',
    rarity: 'rare',
    points: TIER_XP_REWARDS.gold,
    icon: '🌟',
  },
  {
    key: 'first_checkin',
    name: 'Checked In',
    description: 'Check into a hangout for the first time',
    category: 'social',
    tier: 'bronze',
    rarity: 'common',
    points: TIER_XP_REWARDS.bronze,
    icon: '📍',
  },
  {
    key: 'checkins_50',
    name: 'Regular',
    description: 'Check in 50 times',
    category: 'social',
    tier: 'gold',
    rarity: 'rare',
    points: TIER_XP_REWARDS.gold,
    icon: '🏆',
  },
];

// ============================================
// JOURNEY ACHIEVEMENTS
// ============================================
export const journeyAchievements: AchievementSeed[] = [
  {
    key: 'journey_first_complete',
    name: 'Journey Complete',
    description: 'Complete your first journey',
    category: 'milestone',
    tier: 'gold',
    rarity: 'rare',
    points: TIER_XP_REWARDS.gold,
    icon: '🗺️',
  },
  {
    key: 'journey_year_1',
    name: 'One Year Strong',
    description: 'Stay active for 1 year',
    category: 'milestone',
    tier: 'platinum',
    rarity: 'epic',
    points: TIER_XP_REWARDS.platinum,
    icon: '🎂',
  },
  {
    key: 'journey_year_2',
    name: 'Two Year Veteran',
    description: 'Stay active for 2 years',
    category: 'milestone',
    tier: 'diamond',
    rarity: 'legendary',
    points: TIER_XP_REWARDS.diamond,
    icon: '🏅',
  },
  {
    key: 'archetype_complete',
    name: 'Archetype Master',
    description: 'Complete all goals for your archetype',
    category: 'milestone',
    tier: 'platinum',
    rarity: 'epic',
    points: TIER_XP_REWARDS.platinum,
    icon: '🎭',
  },
];

// ============================================
// SPECIAL ACHIEVEMENTS
// ============================================
export const specialAchievements: AchievementSeed[] = [
  // Holiday achievements
  {
    key: 'new_year_workout',
    name: 'New Year, New You',
    description: 'Complete a workout on January 1st',
    category: 'special',
    tier: 'silver',
    rarity: 'uncommon',
    points: TIER_XP_REWARDS.silver,
    icon: '🎆',
  },
  {
    key: 'christmas_workout',
    name: 'Festive Fitness',
    description: 'Complete a workout on December 25th',
    category: 'special',
    tier: 'silver',
    rarity: 'uncommon',
    points: TIER_XP_REWARDS.silver,
    icon: '🎄',
  },
  {
    key: 'thanksgiving_workout',
    name: 'Burn Before Feast',
    description: 'Complete a workout on Thanksgiving',
    category: 'special',
    tier: 'silver',
    rarity: 'uncommon',
    points: TIER_XP_REWARDS.silver,
    icon: '🦃',
  },
  {
    key: 'halloween_workout',
    name: 'Scary Strong',
    description: 'Complete a workout on October 31st',
    category: 'special',
    tier: 'silver',
    rarity: 'uncommon',
    points: TIER_XP_REWARDS.silver,
    icon: '🎃',
  },
  {
    key: 'valentines_workout',
    name: 'Self Love',
    description: 'Complete a workout on February 14th',
    category: 'special',
    tier: 'silver',
    rarity: 'uncommon',
    points: TIER_XP_REWARDS.silver,
    icon: '❤️',
  },
  {
    key: 'independence_day_workout',
    name: 'Freedom Fitness',
    description: 'Complete a workout on July 4th',
    category: 'special',
    tier: 'silver',
    rarity: 'uncommon',
    points: TIER_XP_REWARDS.silver,
    icon: '🇺🇸',
  },
  // Time-based achievements
  {
    key: 'early_bird',
    name: 'Early Bird',
    description: 'Complete a workout before 6 AM',
    category: 'special',
    tier: 'bronze',
    rarity: 'common',
    points: TIER_XP_REWARDS.bronze,
    icon: '🌅',
  },
  {
    key: 'night_owl',
    name: 'Night Owl',
    description: 'Complete a workout after 10 PM',
    category: 'special',
    tier: 'bronze',
    rarity: 'common',
    points: TIER_XP_REWARDS.bronze,
    icon: '🌙',
  },
  {
    key: 'weekend_warrior',
    name: 'Weekend Warrior',
    description: 'Complete workouts on both Saturday and Sunday in the same weekend',
    category: 'special',
    tier: 'bronze',
    rarity: 'common',
    points: TIER_XP_REWARDS.bronze,
    icon: '📅',
  },
  // Rare achievements
  {
    key: 'founding_member',
    name: 'Founding Member',
    description: 'Joined MuscleMap during its first year',
    category: 'special',
    tier: 'platinum',
    rarity: 'epic',
    points: TIER_XP_REWARDS.platinum,
    icon: '🏛️',
  },
  {
    key: 'beta_tester',
    name: 'Beta Tester',
    description: 'Helped test MuscleMap during beta',
    category: 'special',
    tier: 'gold',
    rarity: 'rare',
    points: TIER_XP_REWARDS.gold,
    icon: '🧪',
  },
  {
    key: 'bug_hunter',
    name: 'Bug Hunter',
    description: 'Reported a bug that was fixed',
    category: 'special',
    tier: 'silver',
    rarity: 'uncommon',
    points: TIER_XP_REWARDS.silver,
    icon: '🐛',
  },
];

// ============================================
// TOP RANK / LEADERBOARD ACHIEVEMENTS
// ============================================
export const topRankAchievements: AchievementSeed[] = [
  {
    key: 'hangout_record',
    name: 'Hangout Record',
    description: 'Set a new record at a hangout',
    category: 'top_rank',
    tier: 'gold',
    rarity: 'rare',
    points: TIER_XP_REWARDS.gold,
    icon: '🏅',
  },
  {
    key: 'global_record',
    name: 'Global Record',
    description: 'Set a new global record',
    category: 'top_rank',
    tier: 'diamond',
    rarity: 'legendary',
    points: TIER_XP_REWARDS.diamond,
    icon: '🌍',
    requires_verification: true,
  },
  {
    key: 'top_10_entry',
    name: 'Top 10',
    description: 'Enter a hangout top 10 leaderboard',
    category: 'top_rank',
    tier: 'silver',
    rarity: 'uncommon',
    points: TIER_XP_REWARDS.silver,
    icon: '🔟',
  },
  {
    key: 'top_3_entry',
    name: 'Podium Finish',
    description: 'Enter a hangout top 3',
    category: 'top_rank',
    tier: 'gold',
    rarity: 'rare',
    points: TIER_XP_REWARDS.gold,
    icon: '🥉',
  },
  {
    key: 'number_one',
    name: 'Number One',
    description: 'Reach #1 on a hangout leaderboard',
    category: 'top_rank',
    tier: 'platinum',
    rarity: 'epic',
    points: TIER_XP_REWARDS.platinum,
    icon: '🥇',
  },
];

// ============================================
// FIRST TIME ACHIEVEMENTS
// ============================================
export const firstTimeAchievements: AchievementSeed[] = [
  {
    key: 'first_pullup',
    name: 'First Pull-up',
    description: 'Complete your first pull-up',
    category: 'first_time',
    tier: 'silver',
    rarity: 'uncommon',
    points: TIER_XP_REWARDS.silver,
    icon: '🎯',
  },
  {
    key: 'first_muscle_up',
    name: 'First Muscle-up',
    description: 'Complete your first muscle-up',
    category: 'first_time',
    tier: 'gold',
    rarity: 'rare',
    points: TIER_XP_REWARDS.gold,
    icon: '🔥',
  },
  {
    key: 'first_handstand',
    name: 'First Handstand',
    description: 'Hold your first freestanding handstand',
    category: 'first_time',
    tier: 'gold',
    rarity: 'rare',
    points: TIER_XP_REWARDS.gold,
    icon: '🤸',
  },
  {
    key: 'first_pistol_squat',
    name: 'First Pistol Squat',
    description: 'Complete your first pistol squat',
    category: 'first_time',
    tier: 'silver',
    rarity: 'uncommon',
    points: TIER_XP_REWARDS.silver,
    icon: '🦵',
  },
  {
    key: 'first_5k_run',
    name: 'First 5K',
    description: 'Complete your first 5K run',
    category: 'first_time',
    tier: 'silver',
    rarity: 'uncommon',
    points: TIER_XP_REWARDS.silver,
    icon: '🏃',
  },
  {
    key: 'first_10k_run',
    name: 'First 10K',
    description: 'Complete your first 10K run',
    category: 'first_time',
    tier: 'gold',
    rarity: 'rare',
    points: TIER_XP_REWARDS.gold,
    icon: '🏃',
  },
  {
    key: 'first_half_marathon',
    name: 'First Half Marathon',
    description: 'Complete your first half marathon',
    category: 'first_time',
    tier: 'platinum',
    rarity: 'epic',
    points: TIER_XP_REWARDS.platinum,
    icon: '🏅',
  },
  {
    key: 'first_marathon',
    name: 'First Marathon',
    description: 'Complete your first marathon',
    category: 'first_time',
    tier: 'diamond',
    rarity: 'legendary',
    points: TIER_XP_REWARDS.diamond,
    icon: '👑',
  },
];

// ============================================
// COMBINE ALL ACHIEVEMENTS
// ============================================
export const allAchievements: AchievementSeed[] = [
  ...workoutMilestoneAchievements,
  ...streakAchievements,
  ...strengthRecordAchievements,
  ...volumeAchievements,
  ...exerciseMasteryAchievements,
  ...socialAchievements,
  ...journeyAchievements,
  ...specialAchievements,
  ...topRankAchievements,
  ...firstTimeAchievements,
];

// ============================================
// EXPORT DEFAULT
// ============================================
export default {
  achievements: allAchievements,
  tiers: TIER_XP_REWARDS,
  // Statistics about the seed data
  stats: {
    total: allAchievements.length,
    byCategory: {
      milestone: allAchievements.filter((a) => a.category === 'milestone').length,
      streak: allAchievements.filter((a) => a.category === 'streak').length,
      record: allAchievements.filter((a) => a.category === 'record').length,
      first_time: allAchievements.filter((a) => a.category === 'first_time').length,
      social: allAchievements.filter((a) => a.category === 'social').length,
      top_rank: allAchievements.filter((a) => a.category === 'top_rank').length,
      special: allAchievements.filter((a) => a.category === 'special').length,
    },
    byTier: {
      bronze: allAchievements.filter((a) => a.tier === 'bronze').length,
      silver: allAchievements.filter((a) => a.tier === 'silver').length,
      gold: allAchievements.filter((a) => a.tier === 'gold').length,
      platinum: allAchievements.filter((a) => a.tier === 'platinum').length,
      diamond: allAchievements.filter((a) => a.tier === 'diamond').length,
    },
    byRarity: {
      common: allAchievements.filter((a) => a.rarity === 'common').length,
      uncommon: allAchievements.filter((a) => a.rarity === 'uncommon').length,
      rare: allAchievements.filter((a) => a.rarity === 'rare').length,
      epic: allAchievements.filter((a) => a.rarity === 'epic').length,
      legendary: allAchievements.filter((a) => a.rarity === 'legendary').length,
    },
  },
};
