/**
 * Circus Arts & Aerial Exercise Seeds
 *
 * 60+ exercises based on training methodologies from:
 * - Cirque du Soleil conditioning programs
 * - Professional aerial arts training
 * - Circus arts academies
 * - Contortion and flexibility science
 */

import { ExerciseSeed, ActivationSeed } from './climbing-gymnastics-exercises';

// ============================================
// AERIAL SILKS/FABRIC EXERCISES (20+)
// ============================================

export const aerialSilksExercises: ExerciseSeed[] = [
  // Basic Climbs & Holds
  {
    id: 'aerial-basic-climb',
    name: 'Basic Silk Climb',
    type: 'aerial',
    difficulty: 2,
    primaryMuscles: 'lats,biceps-long,forearm-flexors,rectus-abdominis',
    description: 'Fundamental silk climbing technique. Uses foot lock and upper body pulling.',
    cues: 'Secure foot wrap, pull from lats, controlled ascent',
    equipmentRequired: ['aerial_silks'],
    locations: ['circus_studio', 'gym'],
    movementPattern: 'pull_climb',
    skillLevel: 'intermediate',
    sourceMethodology: 'aerial_silks',
    progressionExercise: 'aerial-russian-climb',
  },
  {
    id: 'aerial-russian-climb',
    name: 'Russian Climb',
    type: 'aerial',
    difficulty: 3,
    primaryMuscles: 'lats,biceps-long,rectus-abdominis,hip-flexors',
    description: 'Advanced climbing technique using straddle and arm pulls alternately.',
    cues: 'Straddle up, pull, repeat, maintain control',
    equipmentRequired: ['aerial_silks'],
    locations: ['circus_studio', 'gym'],
    movementPattern: 'pull_climb',
    skillLevel: 'advanced',
    sourceMethodology: 'aerial_silks',
    regressionExercise: 'aerial-basic-climb',
  },
  {
    id: 'aerial-inversion',
    name: 'Silk Inversion',
    type: 'aerial',
    difficulty: 2,
    primaryMuscles: 'rectus-abdominis,hip-flexors,lats,obliques',
    description: 'Inverting body on silks to hang upside down. Foundation for many poses.',
    cues: 'Pike up, hook silks, control the inversion',
    equipmentRequired: ['aerial_silks'],
    locations: ['circus_studio', 'gym'],
    movementPattern: 'inversion',
    skillLevel: 'intermediate',
    sourceMethodology: 'aerial_silks',
  },
  {
    id: 'aerial-straddle-up',
    name: 'Straddle Up (Silks)',
    type: 'aerial',
    difficulty: 3,
    primaryMuscles: 'rectus-abdominis,hip-flexors,adductor-magnus,lats',
    description: 'Lift body with straight legs straddled around silks. Core intensive.',
    cues: 'Pull down on silks, pike hard, straddle legs around',
    equipmentRequired: ['aerial_silks'],
    locations: ['circus_studio', 'gym'],
    movementPattern: 'core_pull_compound',
    skillLevel: 'advanced',
    sourceMethodology: 'aerial_silks',
  },
  {
    id: 'aerial-skin-the-cat',
    name: 'Skin the Cat (Silks)',
    type: 'aerial',
    difficulty: 2,
    primaryMuscles: 'lats,biceps-long,delt-rear,rectus-abdominis',
    description: 'Rotate body through arms in hanging position. Shoulder mobility and strength.',
    cues: 'Control through full rotation, both directions',
    equipmentRequired: ['aerial_silks'],
    locations: ['circus_studio', 'gym'],
    movementPattern: 'rotation_hang',
    skillLevel: 'intermediate',
    sourceMethodology: 'aerial_silks',
  },

  // Poses & Holds
  {
    id: 'aerial-hip-key',
    name: 'Hip Key',
    type: 'aerial',
    difficulty: 2,
    primaryMuscles: 'hip-flexors,obliques,rectus-abdominis',
    description: 'Fundamental silk wrap around hip for hands-free poses.',
    cues: 'Secure wrap, release hands slowly, engage core',
    equipmentRequired: ['aerial_silks'],
    locations: ['circus_studio', 'gym'],
    movementPattern: 'hold_wrap',
    skillLevel: 'intermediate',
    sourceMethodology: 'aerial_silks',
  },
  {
    id: 'aerial-star',
    name: 'Star Pose',
    type: 'aerial',
    difficulty: 3,
    primaryMuscles: 'adductor-magnus,rectus-abdominis,hip-flexors,obliques',
    description: 'Spread star shape on silks. Requires flexibility and grip strength.',
    cues: 'Secure grips, open to star, hold position',
    equipmentRequired: ['aerial_silks'],
    locations: ['circus_studio', 'gym'],
    movementPattern: 'hold_spread',
    skillLevel: 'advanced',
    sourceMethodology: 'aerial_silks',
  },
  {
    id: 'aerial-crucifix',
    name: 'Crucifix (Silks)',
    type: 'aerial',
    difficulty: 3,
    primaryMuscles: 'delt-side,chest-mid,rectus-abdominis,lats',
    description: 'Arms spread holding silks at sides. Upper body strength hold.',
    cues: 'Spread arms, engage shoulders, hold steady',
    equipmentRequired: ['aerial_silks'],
    locations: ['circus_studio', 'gym'],
    movementPattern: 'hold_spread',
    skillLevel: 'advanced',
    sourceMethodology: 'aerial_silks',
  },

  // Dynamic Movements
  {
    id: 'aerial-drop',
    name: 'Basic Silk Drop',
    type: 'aerial',
    difficulty: 4,
    primaryMuscles: 'forearm-flexors,lats,rectus-abdominis',
    description: 'Controlled fall caught by silk wrap. Requires trust and technique.',
    cues: 'Secure wrap, release controlled, catch at bottom',
    equipmentRequired: ['aerial_silks'],
    locations: ['circus_studio'],
    movementPattern: 'drop_catch',
    skillLevel: 'advanced',
    sourceMethodology: 'aerial_silks',
  },
  {
    id: 'aerial-salto-drop',
    name: 'Salto Drop',
    type: 'aerial',
    difficulty: 5,
    primaryMuscles: 'rectus-abdominis,hip-flexors,lats,forearm-flexors',
    description: 'Rotational drop with somersault. Advanced drop technique.',
    cues: 'Initiate rotation, maintain body position, catch cleanly',
    equipmentRequired: ['aerial_silks'],
    locations: ['circus_studio'],
    movementPattern: 'drop_rotation',
    skillLevel: 'elite',
    sourceMethodology: 'aerial_silks',
  },
];

// ============================================
// TRAPEZE EXERCISES (15+)
// ============================================

export const trapezeExercises: ExerciseSeed[] = [
  {
    id: 'trap-hang',
    name: 'Trapeze Hang',
    type: 'aerial',
    difficulty: 1,
    primaryMuscles: 'forearm-flexors,lats,delt-side',
    description: 'Basic hang from trapeze bar. Foundation grip and shoulder stability.',
    cues: 'Full grip, shoulders engaged, controlled breathing',
    equipmentRequired: ['trapeze'],
    locations: ['circus_studio', 'gym'],
    movementPattern: 'hang',
    skillLevel: 'fundamental',
    sourceMethodology: 'trapeze',
    progressionExercise: 'trap-pullover',
  },
  {
    id: 'trap-pullover',
    name: 'Trapeze Pullover',
    type: 'aerial',
    difficulty: 2,
    primaryMuscles: 'lats,rectus-abdominis,hip-flexors,biceps-long',
    description: 'Pull body over trapeze bar from hang to sitting position.',
    cues: 'Pike up, pull bar to hips, rotate over',
    equipmentRequired: ['trapeze'],
    locations: ['circus_studio', 'gym'],
    movementPattern: 'pullover',
    skillLevel: 'intermediate',
    sourceMethodology: 'trapeze',
    regressionExercise: 'trap-hang',
    progressionExercise: 'trap-knee-hang',
  },
  {
    id: 'trap-knee-hang',
    name: 'Knee Hang',
    type: 'aerial',
    difficulty: 2,
    primaryMuscles: 'hamstring-bicep,quad-rectus,rectus-abdominis',
    description: 'Hang from trapeze by knees. Builds leg grip strength.',
    cues: 'Secure knee grip, control descent, hands-free hold',
    equipmentRequired: ['trapeze'],
    locations: ['circus_studio', 'gym'],
    movementPattern: 'hang_inverted',
    skillLevel: 'intermediate',
    sourceMethodology: 'trapeze',
  },
  {
    id: 'trap-ankle-hang',
    name: 'Ankle Hang',
    type: 'aerial',
    difficulty: 3,
    primaryMuscles: 'tibialis-anterior,gastrocnemius,rectus-abdominis',
    description: 'Hang from trapeze by ankles. Advanced inverted hold.',
    cues: 'Point toes over bar, secure ankle position, control body',
    equipmentRequired: ['trapeze'],
    locations: ['circus_studio'],
    movementPattern: 'hang_inverted',
    skillLevel: 'advanced',
    sourceMethodology: 'trapeze',
  },
  {
    id: 'trap-bird-seat',
    name: 'Bird Seat',
    type: 'aerial',
    difficulty: 2,
    primaryMuscles: 'adductor-magnus,rectus-abdominis,hip-flexors',
    description: 'Seated position on trapeze with legs wrapped around ropes.',
    cues: 'Secure seat, wrap legs, release hands for balance',
    equipmentRequired: ['trapeze'],
    locations: ['circus_studio', 'gym'],
    movementPattern: 'hold_balance',
    skillLevel: 'intermediate',
    sourceMethodology: 'trapeze',
  },
  {
    id: 'trap-mermaid',
    name: 'Mermaid Pose',
    type: 'aerial',
    difficulty: 3,
    primaryMuscles: 'obliques,rectus-abdominis,adductor-magnus,hip-flexors',
    description: 'Side-lying pose on trapeze. Requires balance and flexibility.',
    cues: 'Secure hip position, extend legs, arch body',
    equipmentRequired: ['trapeze'],
    locations: ['circus_studio'],
    movementPattern: 'hold_balance',
    skillLevel: 'advanced',
    sourceMethodology: 'trapeze',
  },
  {
    id: 'trap-splits',
    name: 'Trapeze Splits',
    type: 'aerial',
    difficulty: 4,
    primaryMuscles: 'hip-flexors,hamstring-bicep,adductor-magnus,glute-max',
    description: 'Full splits while on trapeze. Extreme hip flexibility.',
    cues: 'Secure position, open to full split, maintain balance',
    equipmentRequired: ['trapeze'],
    locations: ['circus_studio'],
    movementPattern: 'hold_flexibility',
    skillLevel: 'elite',
    sourceMethodology: 'trapeze',
  },
  {
    id: 'trap-casting',
    name: 'Trapeze Casting',
    type: 'aerial',
    difficulty: 3,
    primaryMuscles: 'lats,delt-front,triceps-long,rectus-abdominis',
    description: 'Swing and release from trapeze. Flying trapeze foundation.',
    cues: 'Build swing, time release, control flight',
    equipmentRequired: ['trapeze'],
    locations: ['circus_studio'],
    movementPattern: 'swing_release',
    skillLevel: 'advanced',
    sourceMethodology: 'trapeze',
  },
];

// ============================================
// AERIAL HOOP/LYRA EXERCISES (10+)
// ============================================

export const aerialHoopExercises: ExerciseSeed[] = [
  {
    id: 'lyra-mount',
    name: 'Lyra Mount',
    type: 'aerial',
    difficulty: 2,
    primaryMuscles: 'lats,biceps-long,rectus-abdominis,forearm-flexors',
    description: 'Basic mount onto aerial hoop from ground or jump.',
    cues: 'Grip hoop, pull up, swing leg over',
    equipmentRequired: ['aerial_hoop'],
    locations: ['circus_studio', 'gym'],
    movementPattern: 'mount',
    skillLevel: 'intermediate',
    sourceMethodology: 'aerial_hoop',
  },
  {
    id: 'lyra-man-in-moon',
    name: 'Man in the Moon',
    type: 'aerial',
    difficulty: 2,
    primaryMuscles: 'rectus-abdominis,hip-flexors,quad-rectus',
    description: 'Classic lyra pose seated in bottom of hoop.',
    cues: 'Sit in hoop, extend legs, pose arms',
    equipmentRequired: ['aerial_hoop'],
    locations: ['circus_studio', 'gym'],
    movementPattern: 'hold_pose',
    skillLevel: 'intermediate',
    sourceMethodology: 'aerial_hoop',
  },
  {
    id: 'lyra-gazelle',
    name: 'Gazelle Pose',
    type: 'aerial',
    difficulty: 3,
    primaryMuscles: 'erector-spinae,glute-max,hamstring-bicep,delt-rear',
    description: 'Backbend pose in lyra with one leg extended.',
    cues: 'Arch back, extend leg, arms for balance',
    equipmentRequired: ['aerial_hoop'],
    locations: ['circus_studio'],
    movementPattern: 'hold_backbend',
    skillLevel: 'advanced',
    sourceMethodology: 'aerial_hoop',
  },
  {
    id: 'lyra-amazon',
    name: 'Amazon Pose',
    type: 'aerial',
    difficulty: 3,
    primaryMuscles: 'obliques,rectus-abdominis,hip-flexors,adductor-magnus',
    description: 'Standing pose in lyra with one foot on bottom bar.',
    cues: 'Secure standing foot, extend other leg, balance',
    equipmentRequired: ['aerial_hoop'],
    locations: ['circus_studio'],
    movementPattern: 'hold_balance',
    skillLevel: 'advanced',
    sourceMethodology: 'aerial_hoop',
  },
  {
    id: 'lyra-spinning',
    name: 'Lyra Spinning',
    type: 'aerial',
    difficulty: 2,
    primaryMuscles: 'rectus-abdominis,obliques,forearm-flexors',
    description: 'Controlled spinning on lyra while holding pose.',
    cues: 'Initiate spin, maintain position, control speed',
    equipmentRequired: ['aerial_hoop'],
    locations: ['circus_studio'],
    movementPattern: 'spin',
    skillLevel: 'intermediate',
    sourceMethodology: 'aerial_hoop',
  },
];

// ============================================
// CONTORTION & FLEXIBILITY (15+)
// ============================================

export const contortionExercises: ExerciseSeed[] = [
  // Backbends
  {
    id: 'contort-bridge',
    name: 'Full Bridge',
    type: 'contortion',
    difficulty: 2,
    primaryMuscles: 'erector-spinae,glute-max,delt-front,quad-rectus',
    description: 'Standard backbend from floor. Foundation for advanced backbends.',
    cues: 'Push through hands and feet, open chest, straighten arms',
    equipmentRequired: [],
    locations: ['gym', 'home', 'circus_studio'],
    movementPattern: 'backbend',
    skillLevel: 'intermediate',
    sourceMethodology: 'contortion',
    progressionExercise: 'contort-chest-stand',
  },
  {
    id: 'contort-chest-stand',
    name: 'Chest Stand',
    type: 'contortion',
    difficulty: 4,
    primaryMuscles: 'erector-spinae,glute-max,hip-flexors',
    description: 'Extreme backbend with feet touching head from behind.',
    cues: 'Work toward feet to head, maintain controlled breathing',
    equipmentRequired: [],
    locations: ['circus_studio', 'gym'],
    movementPattern: 'backbend_extreme',
    skillLevel: 'elite',
    sourceMethodology: 'contortion',
    regressionExercise: 'contort-bridge',
  },
  {
    id: 'contort-scorpion',
    name: 'Scorpion Pose',
    type: 'contortion',
    difficulty: 4,
    primaryMuscles: 'erector-spinae,delt-front,triceps-long,hip-flexors',
    description: 'Forearm balance with extreme backbend, feet toward head.',
    cues: 'Solid forearm base, arch back, reach feet toward head',
    equipmentRequired: [],
    locations: ['circus_studio', 'gym'],
    movementPattern: 'backbend_balance',
    skillLevel: 'elite',
    sourceMethodology: 'contortion',
  },

  // Front Bends
  {
    id: 'contort-pancake',
    name: 'Pancake Stretch',
    type: 'contortion',
    difficulty: 2,
    primaryMuscles: 'adductor-magnus,hamstring-bicep,erector-spinae',
    description: 'Straddle forward fold with chest to floor. Hip and hamstring flexibility.',
    cues: 'Wide straddle, hinge from hips, chest to floor',
    equipmentRequired: [],
    locations: ['gym', 'home', 'circus_studio'],
    movementPattern: 'forward_fold',
    skillLevel: 'intermediate',
    sourceMethodology: 'contortion',
  },
  {
    id: 'contort-pike-fold',
    name: 'Standing Pike Fold',
    type: 'contortion',
    difficulty: 2,
    primaryMuscles: 'hamstring-bicep,erector-spinae,gastrocnemius',
    description: 'Standing forward fold with straight legs, nose to knees.',
    cues: 'Keep legs straight, fold from hips, relax into stretch',
    equipmentRequired: [],
    locations: ['gym', 'home', 'circus_studio'],
    movementPattern: 'forward_fold',
    skillLevel: 'intermediate',
    sourceMethodology: 'contortion',
  },

  // Splits
  {
    id: 'contort-front-split',
    name: 'Front Split',
    type: 'contortion',
    difficulty: 3,
    primaryMuscles: 'hip-flexors,hamstring-bicep,quad-rectus,glute-max',
    description: 'Full front split with hips square.',
    cues: 'Square hips, extend both legs, sink into split',
    equipmentRequired: [],
    locations: ['gym', 'home', 'circus_studio'],
    movementPattern: 'split',
    skillLevel: 'advanced',
    sourceMethodology: 'contortion',
    progressionExercise: 'contort-oversplit',
  },
  {
    id: 'contort-middle-split',
    name: 'Middle Split',
    type: 'contortion',
    difficulty: 3,
    primaryMuscles: 'adductor-magnus,adductor-longus,hip-flexors',
    description: 'Full straddle split with legs to sides.',
    cues: 'Turn knees up, hips forward, sink gradually',
    equipmentRequired: [],
    locations: ['gym', 'home', 'circus_studio'],
    movementPattern: 'split',
    skillLevel: 'advanced',
    sourceMethodology: 'contortion',
  },
  {
    id: 'contort-oversplit',
    name: 'Oversplit',
    type: 'contortion',
    difficulty: 5,
    primaryMuscles: 'hip-flexors,hamstring-bicep,quad-rectus,glute-max',
    description: 'Split beyond 180 degrees using elevated surface.',
    cues: 'Front foot elevated, controlled descent, maintain alignment',
    equipmentRequired: ['yoga_block'],
    locations: ['circus_studio', 'gym'],
    movementPattern: 'split_extreme',
    skillLevel: 'elite',
    sourceMethodology: 'contortion',
    regressionExercise: 'contort-front-split',
  },

  // Shoulder Flexibility
  {
    id: 'contort-shoulder-dislocate',
    name: 'Shoulder Dislocate',
    type: 'contortion',
    difficulty: 2,
    primaryMuscles: 'delt-front,delt-rear,chest-mid,rotator-cuff',
    description: 'Pass stick or band from front to back over head. Shoulder mobility.',
    cues: 'Wide grip, straight arms, controlled full rotation',
    equipmentRequired: ['pvc_pipe'],
    equipmentOptional: ['resistance_band'],
    locations: ['gym', 'home'],
    movementPattern: 'shoulder_rotation',
    skillLevel: 'intermediate',
    sourceMethodology: 'contortion',
  },
  {
    id: 'contort-german-hang',
    name: 'German Hang',
    type: 'contortion',
    difficulty: 3,
    primaryMuscles: 'delt-front,chest-mid,biceps-long',
    description: 'Hang from rings with body passed through arms behind. Extreme shoulder stretch.',
    cues: 'Rotate through slowly, support body weight, stretch shoulders',
    equipmentRequired: ['gymnastics_rings'],
    locations: ['gym', 'circus_studio'],
    movementPattern: 'hang_shoulder_stretch',
    skillLevel: 'advanced',
    sourceMethodology: 'contortion',
  },
];

// ============================================
// HAND BALANCING (10+)
// ============================================

export const handBalancingExercises: ExerciseSeed[] = [
  {
    id: 'hb-crow-pose',
    name: 'Crow Pose (Kakasana)',
    type: 'hand_balancing',
    difficulty: 2,
    primaryMuscles: 'triceps-long,delt-front,rectus-abdominis,hip-flexors',
    description: 'Arm balance with knees on triceps. Foundation hand balance.',
    cues: 'Hands shoulder width, lean forward, lift feet',
    equipmentRequired: [],
    locations: ['gym', 'home', 'circus_studio'],
    movementPattern: 'hand_balance',
    skillLevel: 'intermediate',
    sourceMethodology: 'hand_balancing',
    progressionExercise: 'hb-handstand',
  },
  {
    id: 'hb-handstand',
    name: 'Handstand (Wall)',
    type: 'hand_balancing',
    difficulty: 2,
    primaryMuscles: 'delt-front,triceps-long,rectus-abdominis,serratus',
    description: 'Inverted balance on hands against wall. Foundation for freestanding.',
    cues: 'Fingers spread, shoulders stacked over wrists, tight body',
    equipmentRequired: [],
    locations: ['gym', 'home', 'circus_studio'],
    movementPattern: 'hand_balance',
    skillLevel: 'intermediate',
    sourceMethodology: 'hand_balancing',
    progressionExercise: 'hb-freestanding-handstand',
  },
  {
    id: 'hb-freestanding-handstand',
    name: 'Freestanding Handstand',
    type: 'hand_balancing',
    difficulty: 4,
    primaryMuscles: 'delt-front,triceps-long,rectus-abdominis,serratus',
    description: 'Balanced handstand without wall support.',
    cues: 'Enter controlled, find balance point, micro-adjustments with fingers',
    equipmentRequired: [],
    locations: ['gym', 'circus_studio'],
    movementPattern: 'hand_balance',
    skillLevel: 'advanced',
    sourceMethodology: 'hand_balancing',
    regressionExercise: 'hb-handstand',
    progressionExercise: 'hb-one-arm-handstand',
  },
  {
    id: 'hb-press-handstand',
    name: 'Press to Handstand',
    type: 'hand_balancing',
    difficulty: 4,
    primaryMuscles: 'delt-front,rectus-abdominis,hip-flexors,triceps-long',
    description: 'Press from standing pike to handstand with straight arms.',
    cues: 'Lean forward, lift hips, press through shoulders',
    equipmentRequired: [],
    locations: ['gym', 'circus_studio'],
    movementPattern: 'press_balance',
    skillLevel: 'elite',
    sourceMethodology: 'hand_balancing',
  },
  {
    id: 'hb-straddle-press',
    name: 'Straddle Press to Handstand',
    type: 'hand_balancing',
    difficulty: 5,
    primaryMuscles: 'delt-front,rectus-abdominis,hip-flexors,adductor-magnus',
    description: 'Press to handstand through straddle position.',
    cues: 'Wide straddle, lean forward, close legs at top',
    equipmentRequired: [],
    locations: ['gym', 'circus_studio'],
    movementPattern: 'press_balance',
    skillLevel: 'elite',
    sourceMethodology: 'hand_balancing',
  },
  {
    id: 'hb-one-arm-handstand',
    name: 'One Arm Handstand',
    type: 'hand_balancing',
    difficulty: 5,
    primaryMuscles: 'delt-front,triceps-long,obliques,serratus',
    description: 'Handstand balanced on single arm. Peak of hand balancing.',
    cues: 'Shift weight to one side, lift hand, constant micro-adjustments',
    equipmentRequired: [],
    locations: ['circus_studio'],
    movementPattern: 'hand_balance_single',
    skillLevel: 'elite',
    sourceMethodology: 'hand_balancing',
  },
  {
    id: 'hb-handstand-walk',
    name: 'Handstand Walk',
    type: 'hand_balancing',
    difficulty: 3,
    primaryMuscles: 'delt-front,triceps-long,rectus-abdominis,obliques',
    description: 'Walking on hands while maintaining handstand.',
    cues: 'Shift weight side to side, small steps, maintain alignment',
    equipmentRequired: [],
    locations: ['gym', 'circus_studio'],
    movementPattern: 'hand_balance_locomotion',
    skillLevel: 'advanced',
    sourceMethodology: 'hand_balancing',
  },
  {
    id: 'hb-canes',
    name: 'Canes Balance',
    type: 'hand_balancing',
    difficulty: 4,
    primaryMuscles: 'delt-front,triceps-long,forearm-flexors,rectus-abdominis',
    description: 'Handstand on hand balancing canes. Increased difficulty and wrist demands.',
    cues: 'Grip canes firmly, same principles as floor handstand',
    equipmentRequired: ['hand_balance_canes'],
    locations: ['circus_studio'],
    movementPattern: 'hand_balance',
    skillLevel: 'elite',
    sourceMethodology: 'hand_balancing',
  },
];

// ============================================
// COMBINED EXPORTS
// ============================================

export const allCircusAerialExercises: ExerciseSeed[] = [
  ...aerialSilksExercises,
  ...trapezeExercises,
  ...aerialHoopExercises,
  ...contortionExercises,
  ...handBalancingExercises,
];

// ============================================
// MUSCLE ACTIVATIONS
// ============================================

export const circusAerialActivations: ActivationSeed[] = [
  // Aerial Silks
  { exerciseId: 'aerial-basic-climb', muscleId: 'lats', activation: 85 },
  { exerciseId: 'aerial-basic-climb', muscleId: 'biceps-long', activation: 80 },
  { exerciseId: 'aerial-basic-climb', muscleId: 'forearm-flexors', activation: 90 },
  { exerciseId: 'aerial-basic-climb', muscleId: 'rectus-abdominis', activation: 60 },

  { exerciseId: 'aerial-russian-climb', muscleId: 'lats', activation: 90 },
  { exerciseId: 'aerial-russian-climb', muscleId: 'biceps-long', activation: 85 },
  { exerciseId: 'aerial-russian-climb', muscleId: 'rectus-abdominis', activation: 75 },
  { exerciseId: 'aerial-russian-climb', muscleId: 'hip-flexors', activation: 70 },

  { exerciseId: 'aerial-inversion', muscleId: 'rectus-abdominis', activation: 90 },
  { exerciseId: 'aerial-inversion', muscleId: 'hip-flexors', activation: 85 },
  { exerciseId: 'aerial-inversion', muscleId: 'lats', activation: 60 },
  { exerciseId: 'aerial-inversion', muscleId: 'obliques', activation: 50 },

  { exerciseId: 'aerial-straddle-up', muscleId: 'rectus-abdominis', activation: 95 },
  { exerciseId: 'aerial-straddle-up', muscleId: 'hip-flexors', activation: 90 },
  { exerciseId: 'aerial-straddle-up', muscleId: 'adductor-magnus', activation: 70 },
  { exerciseId: 'aerial-straddle-up', muscleId: 'lats', activation: 65 },

  { exerciseId: 'aerial-crucifix', muscleId: 'delt-side', activation: 90 },
  { exerciseId: 'aerial-crucifix', muscleId: 'chest-mid', activation: 75 },
  { exerciseId: 'aerial-crucifix', muscleId: 'rectus-abdominis', activation: 70 },
  { exerciseId: 'aerial-crucifix', muscleId: 'lats', activation: 60 },

  // Trapeze
  { exerciseId: 'trap-hang', muscleId: 'forearm-flexors', activation: 85 },
  { exerciseId: 'trap-hang', muscleId: 'lats', activation: 50 },
  { exerciseId: 'trap-hang', muscleId: 'delt-side', activation: 40 },

  { exerciseId: 'trap-pullover', muscleId: 'lats', activation: 85 },
  { exerciseId: 'trap-pullover', muscleId: 'rectus-abdominis', activation: 80 },
  { exerciseId: 'trap-pullover', muscleId: 'hip-flexors', activation: 70 },
  { exerciseId: 'trap-pullover', muscleId: 'biceps-long', activation: 65 },

  { exerciseId: 'trap-knee-hang', muscleId: 'hamstring-bicep', activation: 80 },
  { exerciseId: 'trap-knee-hang', muscleId: 'quad-rectus', activation: 70 },
  { exerciseId: 'trap-knee-hang', muscleId: 'rectus-abdominis', activation: 50 },

  { exerciseId: 'trap-casting', muscleId: 'lats', activation: 85 },
  { exerciseId: 'trap-casting', muscleId: 'delt-front', activation: 75 },
  { exerciseId: 'trap-casting', muscleId: 'triceps-long', activation: 65 },
  { exerciseId: 'trap-casting', muscleId: 'rectus-abdominis', activation: 70 },

  // Lyra
  { exerciseId: 'lyra-mount', muscleId: 'lats', activation: 85 },
  { exerciseId: 'lyra-mount', muscleId: 'biceps-long', activation: 80 },
  { exerciseId: 'lyra-mount', muscleId: 'rectus-abdominis', activation: 65 },
  { exerciseId: 'lyra-mount', muscleId: 'forearm-flexors', activation: 75 },

  { exerciseId: 'lyra-gazelle', muscleId: 'erector-spinae', activation: 85 },
  { exerciseId: 'lyra-gazelle', muscleId: 'glute-max', activation: 70 },
  { exerciseId: 'lyra-gazelle', muscleId: 'hamstring-bicep', activation: 60 },
  { exerciseId: 'lyra-gazelle', muscleId: 'delt-rear', activation: 55 },

  // Contortion
  { exerciseId: 'contort-bridge', muscleId: 'erector-spinae', activation: 80 },
  { exerciseId: 'contort-bridge', muscleId: 'glute-max', activation: 75 },
  { exerciseId: 'contort-bridge', muscleId: 'delt-front', activation: 60 },
  { exerciseId: 'contort-bridge', muscleId: 'quad-rectus', activation: 55 },

  { exerciseId: 'contort-chest-stand', muscleId: 'erector-spinae', activation: 95 },
  { exerciseId: 'contort-chest-stand', muscleId: 'glute-max', activation: 85 },
  { exerciseId: 'contort-chest-stand', muscleId: 'hip-flexors', activation: 70 },

  { exerciseId: 'contort-scorpion', muscleId: 'erector-spinae', activation: 90 },
  { exerciseId: 'contort-scorpion', muscleId: 'delt-front', activation: 85 },
  { exerciseId: 'contort-scorpion', muscleId: 'triceps-long', activation: 80 },
  { exerciseId: 'contort-scorpion', muscleId: 'hip-flexors', activation: 75 },

  { exerciseId: 'contort-pancake', muscleId: 'adductor-magnus', activation: 85 },
  { exerciseId: 'contort-pancake', muscleId: 'hamstring-bicep', activation: 80 },
  { exerciseId: 'contort-pancake', muscleId: 'erector-spinae', activation: 50 },

  { exerciseId: 'contort-front-split', muscleId: 'hip-flexors', activation: 90 },
  { exerciseId: 'contort-front-split', muscleId: 'hamstring-bicep', activation: 85 },
  { exerciseId: 'contort-front-split', muscleId: 'quad-rectus', activation: 60 },
  { exerciseId: 'contort-front-split', muscleId: 'glute-max', activation: 55 },

  { exerciseId: 'contort-middle-split', muscleId: 'adductor-magnus', activation: 95 },
  { exerciseId: 'contort-middle-split', muscleId: 'adductor-longus', activation: 90 },
  { exerciseId: 'contort-middle-split', muscleId: 'hip-flexors', activation: 60 },

  // Hand Balancing
  { exerciseId: 'hb-crow-pose', muscleId: 'triceps-long', activation: 75 },
  { exerciseId: 'hb-crow-pose', muscleId: 'delt-front', activation: 70 },
  { exerciseId: 'hb-crow-pose', muscleId: 'rectus-abdominis', activation: 80 },
  { exerciseId: 'hb-crow-pose', muscleId: 'hip-flexors', activation: 65 },

  { exerciseId: 'hb-handstand', muscleId: 'delt-front', activation: 90 },
  { exerciseId: 'hb-handstand', muscleId: 'triceps-long', activation: 80 },
  { exerciseId: 'hb-handstand', muscleId: 'rectus-abdominis', activation: 75 },
  { exerciseId: 'hb-handstand', muscleId: 'serratus', activation: 70 },

  { exerciseId: 'hb-freestanding-handstand', muscleId: 'delt-front', activation: 95 },
  { exerciseId: 'hb-freestanding-handstand', muscleId: 'triceps-long', activation: 85 },
  { exerciseId: 'hb-freestanding-handstand', muscleId: 'rectus-abdominis', activation: 80 },
  { exerciseId: 'hb-freestanding-handstand', muscleId: 'serratus', activation: 75 },

  { exerciseId: 'hb-press-handstand', muscleId: 'delt-front', activation: 95 },
  { exerciseId: 'hb-press-handstand', muscleId: 'rectus-abdominis', activation: 95 },
  { exerciseId: 'hb-press-handstand', muscleId: 'hip-flexors', activation: 90 },
  { exerciseId: 'hb-press-handstand', muscleId: 'triceps-long', activation: 80 },

  { exerciseId: 'hb-one-arm-handstand', muscleId: 'delt-front', activation: 100 },
  { exerciseId: 'hb-one-arm-handstand', muscleId: 'triceps-long', activation: 90 },
  { exerciseId: 'hb-one-arm-handstand', muscleId: 'obliques', activation: 95 },
  { exerciseId: 'hb-one-arm-handstand', muscleId: 'serratus', activation: 85 },

  { exerciseId: 'hb-handstand-walk', muscleId: 'delt-front', activation: 90 },
  { exerciseId: 'hb-handstand-walk', muscleId: 'triceps-long', activation: 85 },
  { exerciseId: 'hb-handstand-walk', muscleId: 'rectus-abdominis', activation: 80 },
  { exerciseId: 'hb-handstand-walk', muscleId: 'obliques', activation: 85 },
];
