/**
 * Climbing & Gymnastics Exercise Seeds
 *
 * 150+ exercises for climbing, gymnastics, and calisthenics skill training.
 * Based on research from Eric Horst, Eva Lopez, GMB, and gymnastics conditioning manuals.
 */

export interface ExerciseSeed {
  id: string;
  name: string;
  type: string;
  difficulty: number;
  primaryMuscles: string;
  description: string;
  cues: string;
  equipmentRequired?: string[];
  equipmentOptional?: string[];
  locations?: string[];
  movementPattern?: string;
  skillLevel?: string;
  sourceMethodology?: string;
  regressionExercise?: string;
  progressionExercise?: string;
}

export interface ActivationSeed {
  exerciseId: string;
  muscleId: string;
  activation: number;
}

// ============================================
// CLIMBING EXERCISES (60+)
// ============================================

export const climbingExercises: ExerciseSeed[] = [
  // Hangboard / Finger Strength
  {
    id: 'climb-halfcrimp-20mm',
    name: 'Half-Crimp Hang (20mm)',
    type: 'climbing',
    difficulty: 2,
    primaryMuscles: 'forearm-flexors,lats,biceps-long',
    description: 'Hang from a 20mm edge in half-crimp position. This is the safest crimp position and the foundation of finger strength training. Based on Eva Lopez and Eric Horst protocols.',
    cues: 'Half-crimp position (90° DIP joint), shoulders engaged, breathe steadily',
    equipmentRequired: ['hangboard'],
    locations: ['gym', 'home', 'climbing_gym'],
    movementPattern: 'pull_isometric',
    skillLevel: 'intermediate',
    sourceMethodology: 'climbing',
    regressionExercise: 'climb-jug-hang',
    progressionExercise: 'climb-halfcrimp-18mm',
  },
  {
    id: 'climb-halfcrimp-18mm',
    name: 'Half-Crimp Hang (18mm)',
    type: 'climbing',
    difficulty: 3,
    primaryMuscles: 'forearm-flexors,lats,biceps-long',
    description: 'Hang from an 18mm edge in half-crimp position. Intermediate edge depth requiring developed finger strength.',
    cues: 'Maintain half-crimp, active shoulders, core tight',
    equipmentRequired: ['hangboard'],
    locations: ['gym', 'home', 'climbing_gym'],
    movementPattern: 'pull_isometric',
    skillLevel: 'advanced',
    sourceMethodology: 'climbing',
    regressionExercise: 'climb-halfcrimp-20mm',
    progressionExercise: 'climb-halfcrimp-15mm',
  },
  {
    id: 'climb-halfcrimp-15mm',
    name: 'Half-Crimp Hang (15mm)',
    type: 'climbing',
    difficulty: 4,
    primaryMuscles: 'forearm-flexors,lats,biceps-long',
    description: 'Hang from a 15mm edge in half-crimp position. Advanced edge depth for strong climbers.',
    cues: 'Perfect half-crimp form, no full crimping, controlled breathing',
    equipmentRequired: ['hangboard'],
    locations: ['gym', 'home', 'climbing_gym'],
    movementPattern: 'pull_isometric',
    skillLevel: 'advanced',
    sourceMethodology: 'climbing',
    regressionExercise: 'climb-halfcrimp-18mm',
    progressionExercise: 'climb-halfcrimp-12mm',
  },
  {
    id: 'climb-openhand-20mm',
    name: 'Open-Hand Hang (20mm)',
    type: 'climbing',
    difficulty: 2,
    primaryMuscles: 'forearm-flexors,lats',
    description: 'Hang from a 20mm edge with open-hand (drag) grip. Safer than crimp positions and builds different aspects of finger strength.',
    cues: 'Fingers open with slight curl, shoulders active, core engaged',
    equipmentRequired: ['hangboard'],
    locations: ['gym', 'home', 'climbing_gym'],
    movementPattern: 'pull_isometric',
    skillLevel: 'intermediate',
    sourceMethodology: 'climbing',
  },
  {
    id: 'climb-repeaters-7-3',
    name: '7/3 Repeaters Protocol',
    type: 'climbing',
    difficulty: 3,
    primaryMuscles: 'forearm-flexors,lats,biceps-long',
    description: '7 seconds hang, 3 seconds rest, repeated 6 times per set. This protocol builds strength-endurance specific to climbing demands. Based on PMC research.',
    cues: '7 sec on, 3 sec off, 6 reps = 1 set. 3 minute rest between sets.',
    equipmentRequired: ['hangboard'],
    locations: ['gym', 'home', 'climbing_gym'],
    movementPattern: 'pull_isometric',
    skillLevel: 'intermediate',
    sourceMethodology: 'climbing',
  },
  {
    id: 'climb-max-hangs',
    name: 'Max Hangs Protocol',
    type: 'climbing',
    difficulty: 4,
    primaryMuscles: 'forearm-flexors,lats,biceps-long',
    description: '10-second hang at max intensity (weight added so you fail at ~13 seconds). 3 minute rest between sets. 5 sets total. Based on Eric Horst research.',
    cues: 'Add weight so you can barely hold 13 seconds. Do 10 second hangs.',
    equipmentRequired: ['hangboard'],
    equipmentOptional: ['weight_vest'],
    locations: ['gym', 'home', 'climbing_gym'],
    movementPattern: 'pull_isometric',
    skillLevel: 'advanced',
    sourceMethodology: 'climbing',
  },
  {
    id: 'climb-one-arm-hang',
    name: 'One-Arm Hang (Assisted)',
    type: 'climbing',
    difficulty: 4,
    primaryMuscles: 'forearm-flexors,lats,biceps-long,obliques',
    description: 'Hang from one arm with pulley or band assistance. Elite finger strength exercise. Builds unilateral pulling strength.',
    cues: 'Use pulley for assistance, maintain shoulder engagement, no swinging',
    equipmentRequired: ['hangboard', 'pulley_system'],
    locations: ['gym', 'climbing_gym'],
    movementPattern: 'pull_isometric',
    skillLevel: 'elite',
    sourceMethodology: 'climbing',
  },
  {
    id: 'climb-pinch-block',
    name: 'Pinch Block Holds',
    type: 'climbing',
    difficulty: 3,
    primaryMuscles: 'forearm-flexors,forearm-extensors',
    description: 'Hold a pinch block (or weight plate) with thumb opposed to fingers. Builds pinch strength critical for slopers and pinch holds.',
    cues: 'Thumb opposes fingers, squeeze hard, maintain for time',
    equipmentRequired: ['pinch_block'],
    locations: ['gym', 'home', 'climbing_gym'],
    movementPattern: 'grip_isometric',
    skillLevel: 'intermediate',
    sourceMethodology: 'climbing',
  },
  {
    id: 'climb-campus-ladder',
    name: 'Campus Board Laddering',
    type: 'climbing',
    difficulty: 4,
    primaryMuscles: 'lats,biceps-long,forearm-flexors',
    description: 'Climb up campus board rungs without using feet. Explosive pulling exercise that builds contact strength and power.',
    cues: 'Controlled explosive movement, one rung at a time, no kipping',
    equipmentRequired: ['campus_board'],
    locations: ['climbing_gym'],
    movementPattern: 'pull_explosive',
    skillLevel: 'advanced',
    sourceMethodology: 'climbing',
  },
  {
    id: 'climb-lockoff-90',
    name: 'Lock-Off Hold (90 degrees)',
    type: 'climbing',
    difficulty: 3,
    primaryMuscles: 'biceps-long,biceps-short,lats',
    description: 'Hold a pull-up position with elbows at 90 degrees. Builds isometric pulling strength used in climbing moves.',
    cues: 'Pull to 90 degrees, hold, maintain shoulder engagement',
    equipmentRequired: ['pull_up_bar'],
    locations: ['gym', 'home', 'park', 'climbing_gym'],
    movementPattern: 'pull_isometric',
    skillLevel: 'intermediate',
    sourceMethodology: 'climbing',
    progressionExercise: 'climb-lockoff-120',
  },
  {
    id: 'climb-frenchies',
    name: 'Frenchies (3-Stage Lock-Off)',
    type: 'climbing',
    difficulty: 4,
    primaryMuscles: 'biceps-long,lats,forearm-flexors',
    description: 'Pull-up with lock-offs at top, 90°, and 120°. Complete climbing-specific pulling exercise.',
    cues: 'Pull up, hold top 5s, lower to 90° hold 5s, lower to 120° hold 5s, repeat',
    equipmentRequired: ['pull_up_bar'],
    locations: ['gym', 'home', 'park', 'climbing_gym'],
    movementPattern: 'pull_compound',
    skillLevel: 'advanced',
    sourceMethodology: 'climbing',
  },
  {
    id: 'climb-finger-extension',
    name: 'Finger Extensions with Band',
    type: 'climbing',
    difficulty: 1,
    primaryMuscles: 'forearm-extensors',
    description: 'Open fingers against band resistance. Essential antagonist training to prevent climber\'s elbow and finger injuries.',
    cues: 'Place band around fingertips, spread fingers apart, control return',
    equipmentRequired: ['resistance_band'],
    locations: ['gym', 'home', 'office'],
    movementPattern: 'isolation',
    skillLevel: 'fundamental',
    sourceMethodology: 'climbing',
  },
  {
    id: 'climb-reverse-wrist-curl',
    name: 'Reverse Wrist Curl',
    type: 'climbing',
    difficulty: 1,
    primaryMuscles: 'forearm-extensors',
    description: 'Wrist extension exercise for antagonist training. Prevents muscle imbalances from grip-heavy climbing.',
    cues: 'Palm down, extend wrist up, control descent',
    equipmentRequired: ['dumbbell'],
    locations: ['gym', 'home'],
    movementPattern: 'isolation',
    skillLevel: 'fundamental',
    sourceMethodology: 'climbing',
  },
  {
    id: 'climb-scapular-pullup',
    name: 'Scapular Pull-Up',
    type: 'climbing',
    difficulty: 2,
    primaryMuscles: 'traps-lower,rhomboids,lats',
    description: 'Pull-up focusing only on scapular movement (no elbow bend). Builds shoulder stability crucial for climbing.',
    cues: 'Dead hang, retract and depress scapula to rise slightly, release',
    equipmentRequired: ['pull_up_bar'],
    locations: ['gym', 'home', 'park', 'climbing_gym'],
    movementPattern: 'pull_isolation',
    skillLevel: 'intermediate',
    sourceMethodology: 'climbing',
  },
];

// ============================================
// GYMNASTICS EXERCISES (60+)
// ============================================

export const gymnasticsExercises: ExerciseSeed[] = [
  // Front Lever Progressions
  {
    id: 'gym-tuck-front-lever',
    name: 'Tuck Front Lever',
    type: 'gymnastics',
    difficulty: 3,
    primaryMuscles: 'lats,rectus-abdominis,biceps-long',
    description: 'Hang with body horizontal, knees tucked to chest. Foundation front lever progression building the lat and core strength needed for full front lever.',
    cues: 'Hips at bar height, depress and retract scapula, squeeze core',
    equipmentRequired: ['pull_up_bar'],
    locations: ['gym', 'home', 'park'],
    movementPattern: 'pull_isometric',
    skillLevel: 'intermediate',
    sourceMethodology: 'gymnastics',
    regressionExercise: 'bw-pullup',
    progressionExercise: 'gym-adv-tuck-front-lever',
  },
  {
    id: 'gym-adv-tuck-front-lever',
    name: 'Advanced Tuck Front Lever',
    type: 'gymnastics',
    difficulty: 3,
    primaryMuscles: 'lats,rectus-abdominis,biceps-long',
    description: 'Front lever with hips extended but knees still bent. Increases lever arm from tuck position.',
    cues: 'Open hip angle more, keep knees bent, back approaches horizontal',
    equipmentRequired: ['pull_up_bar'],
    locations: ['gym', 'home', 'park'],
    movementPattern: 'pull_isometric',
    skillLevel: 'advanced',
    sourceMethodology: 'gymnastics',
    regressionExercise: 'gym-tuck-front-lever',
    progressionExercise: 'gym-straddle-front-lever',
  },
  {
    id: 'gym-straddle-front-lever',
    name: 'Straddle Front Lever',
    type: 'gymnastics',
    difficulty: 4,
    primaryMuscles: 'lats,rectus-abdominis,biceps-long,adductor-magnus',
    description: 'Front lever with legs extended in straddle. Wide straddle reduces lever arm compared to full.',
    cues: 'Legs straight in wide straddle, body horizontal, point toes',
    equipmentRequired: ['pull_up_bar'],
    locations: ['gym', 'home', 'park'],
    movementPattern: 'pull_isometric',
    skillLevel: 'advanced',
    sourceMethodology: 'gymnastics',
    regressionExercise: 'gym-adv-tuck-front-lever',
    progressionExercise: 'gym-full-front-lever',
  },
  {
    id: 'gym-full-front-lever',
    name: 'Full Front Lever',
    type: 'gymnastics',
    difficulty: 5,
    primaryMuscles: 'lats,rectus-abdominis,biceps-long,glute-max',
    description: 'Full front lever with body horizontal, legs together and straight. Elite gymnastics skill.',
    cues: 'Legs together, body horizontal, total body tension',
    equipmentRequired: ['pull_up_bar'],
    locations: ['gym', 'home', 'park'],
    movementPattern: 'pull_isometric',
    skillLevel: 'elite',
    sourceMethodology: 'gymnastics',
    regressionExercise: 'gym-straddle-front-lever',
  },

  // Planche Progressions
  {
    id: 'gym-planche-lean',
    name: 'Planche Lean',
    type: 'gymnastics',
    difficulty: 2,
    primaryMuscles: 'delt-front,chest-mid,triceps-long',
    description: 'Push-up position with significant forward lean. Foundation exercise for planche, builds straight-arm strength.',
    cues: 'Lean forward 15-30 degrees past wrists, protract scapula, hollow body',
    equipmentRequired: [],
    equipmentOptional: ['parallettes'],
    locations: ['gym', 'home', 'park'],
    movementPattern: 'push_isometric',
    skillLevel: 'intermediate',
    sourceMethodology: 'gymnastics',
    progressionExercise: 'gym-tuck-planche',
  },
  {
    id: 'gym-tuck-planche',
    name: 'Tuck Planche',
    type: 'gymnastics',
    difficulty: 3,
    primaryMuscles: 'delt-front,chest-mid,triceps-long,rectus-abdominis',
    description: 'Support body on hands with knees tucked to chest, feet off ground. First true planche progression.',
    cues: 'Shoulders over or past wrists, round upper back, knees tight to chest',
    equipmentRequired: [],
    equipmentOptional: ['parallettes'],
    locations: ['gym', 'home', 'park'],
    movementPattern: 'push_isometric',
    skillLevel: 'advanced',
    sourceMethodology: 'gymnastics',
    regressionExercise: 'gym-planche-lean',
    progressionExercise: 'gym-adv-tuck-planche',
  },
  {
    id: 'gym-adv-tuck-planche',
    name: 'Advanced Tuck Planche',
    type: 'gymnastics',
    difficulty: 4,
    primaryMuscles: 'delt-front,chest-mid,triceps-long,rectus-abdominis',
    description: 'Planche with flattened back and hips at shoulder height. Significant increase in difficulty from tuck.',
    cues: 'Flatten back (less rounded), hips at shoulder height, knees still bent',
    equipmentRequired: [],
    equipmentOptional: ['parallettes'],
    locations: ['gym', 'home', 'park'],
    movementPattern: 'push_isometric',
    skillLevel: 'advanced',
    sourceMethodology: 'gymnastics',
    regressionExercise: 'gym-tuck-planche',
    progressionExercise: 'gym-straddle-planche',
  },
  {
    id: 'gym-straddle-planche',
    name: 'Straddle Planche',
    type: 'gymnastics',
    difficulty: 5,
    primaryMuscles: 'delt-front,chest-mid,triceps-long,rectus-abdominis',
    description: 'Planche with legs extended in straddle position. Very advanced gymnastics skill.',
    cues: 'Massive forward lean, straight legs in wide straddle, point toes',
    equipmentRequired: [],
    equipmentOptional: ['parallettes'],
    locations: ['gym', 'home', 'park'],
    movementPattern: 'push_isometric',
    skillLevel: 'elite',
    sourceMethodology: 'gymnastics',
    regressionExercise: 'gym-adv-tuck-planche',
    progressionExercise: 'gym-full-planche',
  },
  {
    id: 'gym-full-planche',
    name: 'Full Planche',
    type: 'gymnastics',
    difficulty: 5,
    primaryMuscles: 'delt-front,chest-mid,triceps-long,rectus-abdominis,glute-max',
    description: 'Full planche with legs together and body horizontal. One of the most difficult bodyweight skills.',
    cues: 'Legs together, perfect body line, extreme shoulder strength',
    equipmentRequired: [],
    equipmentOptional: ['parallettes'],
    locations: ['gym', 'home', 'park'],
    movementPattern: 'push_isometric',
    skillLevel: 'elite',
    sourceMethodology: 'gymnastics',
    regressionExercise: 'gym-straddle-planche',
  },

  // Ring Work
  {
    id: 'gym-ring-support',
    name: 'Ring Support Hold',
    type: 'gymnastics',
    difficulty: 2,
    primaryMuscles: 'chest-mid,triceps-long,delt-front',
    description: 'Hold support position on rings with arms locked. Foundation ring exercise.',
    cues: 'Arms locked, rings turned out, depress shoulders',
    equipmentRequired: ['gymnastics_rings'],
    locations: ['gym', 'home', 'park'],
    movementPattern: 'push_isometric',
    skillLevel: 'intermediate',
    sourceMethodology: 'gymnastics',
    progressionExercise: 'gym-ring-dip',
  },
  {
    id: 'gym-ring-dip',
    name: 'Ring Dip',
    type: 'gymnastics',
    difficulty: 3,
    primaryMuscles: 'chest-lower,triceps-long,delt-front',
    description: 'Dip performed on gymnastic rings. Much harder than bar dips due to instability.',
    cues: 'Rings turned out at top, control descent, elbows back not flared',
    equipmentRequired: ['gymnastics_rings'],
    locations: ['gym', 'home', 'park'],
    movementPattern: 'push_vertical',
    skillLevel: 'advanced',
    sourceMethodology: 'gymnastics',
    regressionExercise: 'gym-ring-support',
    progressionExercise: 'gym-ring-muscle-up',
  },
  {
    id: 'gym-ring-pushup',
    name: 'Ring Push-Up',
    type: 'gymnastics',
    difficulty: 2,
    primaryMuscles: 'chest-mid,triceps-lateral,delt-front',
    description: 'Push-up performed on low rings. Added instability increases difficulty and muscle recruitment.',
    cues: 'Rings at hip height, turn rings out at top, control throughout',
    equipmentRequired: ['gymnastics_rings'],
    locations: ['gym', 'home', 'park'],
    movementPattern: 'push_horizontal',
    skillLevel: 'intermediate',
    sourceMethodology: 'gymnastics',
  },
  {
    id: 'gym-ring-muscle-up',
    name: 'Ring Muscle-Up',
    type: 'gymnastics',
    difficulty: 4,
    primaryMuscles: 'lats,chest-lower,triceps-long',
    description: 'Pull to dip transition on rings. Harder than bar muscle-up due to ring instability.',
    cues: 'False grip, explosive pull, turn rings out as you press up',
    equipmentRequired: ['gymnastics_rings'],
    locations: ['gym', 'home', 'park'],
    movementPattern: 'pull_push_compound',
    skillLevel: 'advanced',
    sourceMethodology: 'gymnastics',
    regressionExercise: 'gym-ring-dip',
  },
  {
    id: 'gym-skin-the-cat',
    name: 'Skin the Cat',
    type: 'gymnastics',
    difficulty: 3,
    primaryMuscles: 'lats,delt-rear,rotator-cuff',
    description: 'Rotate through hang position backward into German hang and back. Builds shoulder flexibility and strength.',
    cues: 'Controlled rotation, pause in German hang, reverse slowly',
    equipmentRequired: ['gymnastics_rings'],
    equipmentOptional: ['pull_up_bar'],
    locations: ['gym', 'home', 'park'],
    movementPattern: 'pull_rotation',
    skillLevel: 'intermediate',
    sourceMethodology: 'gymnastics',
  },

  // Handstand Work
  {
    id: 'gym-wall-handstand-chest',
    name: 'Wall Handstand (Chest to Wall)',
    type: 'gymnastics',
    difficulty: 2,
    primaryMuscles: 'delt-front,triceps-long,traps-upper',
    description: 'Handstand facing wall, chest toward wall. Better alignment than back-to-wall. Build time for 60+ seconds.',
    cues: 'Walk feet up wall, chest toward wall, arms locked, look at hands',
    equipmentRequired: [],
    locations: ['gym', 'home'],
    movementPattern: 'push_isometric',
    skillLevel: 'intermediate',
    sourceMethodology: 'gymnastics',
    progressionExercise: 'gym-wall-handstand-back',
  },
  {
    id: 'gym-wall-handstand-back',
    name: 'Wall Handstand (Back to Wall)',
    type: 'gymnastics',
    difficulty: 2,
    primaryMuscles: 'delt-front,triceps-long,traps-upper',
    description: 'Handstand with back toward wall, kick up entry. Practice pulling away from wall for balance work.',
    cues: 'Kick up to wall, only heels touch, practice pulling away',
    equipmentRequired: [],
    locations: ['gym', 'home'],
    movementPattern: 'push_isometric',
    skillLevel: 'intermediate',
    sourceMethodology: 'gymnastics',
    regressionExercise: 'gym-wall-handstand-chest',
    progressionExercise: 'gym-freestanding-handstand',
  },
  {
    id: 'gym-freestanding-handstand',
    name: 'Freestanding Handstand',
    type: 'gymnastics',
    difficulty: 4,
    primaryMuscles: 'delt-front,triceps-long,rectus-abdominis,traps-upper',
    description: 'Balance in handstand without wall support. Requires strength, balance, and body awareness.',
    cues: 'Kick up, use finger pressure to balance, hollow body, look at hands',
    equipmentRequired: [],
    locations: ['gym', 'home', 'park'],
    movementPattern: 'push_isometric',
    skillLevel: 'advanced',
    sourceMethodology: 'gymnastics',
    regressionExercise: 'gym-wall-handstand-back',
    progressionExercise: 'gym-handstand-walk',
  },
  {
    id: 'gym-handstand-walk',
    name: 'Handstand Walking',
    type: 'gymnastics',
    difficulty: 4,
    primaryMuscles: 'delt-front,triceps-long,rectus-abdominis',
    description: 'Walk on hands while maintaining handstand balance. Advanced balance and coordination.',
    cues: 'Shift weight side to side, small steps, maintain hollow body',
    equipmentRequired: [],
    locations: ['gym', 'home', 'park'],
    movementPattern: 'push_dynamic',
    skillLevel: 'advanced',
    sourceMethodology: 'gymnastics',
    regressionExercise: 'gym-freestanding-handstand',
    progressionExercise: 'gym-press-handstand',
  },
  {
    id: 'gym-press-handstand',
    name: 'Press to Handstand',
    type: 'gymnastics',
    difficulty: 5,
    primaryMuscles: 'delt-front,triceps-long,hip-flexors,rectus-abdominis',
    description: 'Press from standing pike or straddle into handstand without jumping. Elite skill requiring flexibility and strength.',
    cues: 'Lean forward as hips rise, keep compression, press to lockout',
    equipmentRequired: [],
    locations: ['gym', 'home', 'park'],
    movementPattern: 'push_dynamic',
    skillLevel: 'elite',
    sourceMethodology: 'gymnastics',
    regressionExercise: 'gym-handstand-walk',
  },

  // Core Progressions
  {
    id: 'gym-hollow-hold',
    name: 'Hollow Body Hold',
    type: 'gymnastics',
    difficulty: 2,
    primaryMuscles: 'rectus-abdominis,hip-flexors,transverse-abdominis',
    description: 'Lie on back with lower back pressed into floor, arms and legs extended off ground. Foundation gymnastics core position.',
    cues: 'Lower back flat on floor, arms by ears, legs straight, point toes',
    equipmentRequired: [],
    locations: ['gym', 'home', 'park', 'hotel'],
    movementPattern: 'anti_extension',
    skillLevel: 'intermediate',
    sourceMethodology: 'gymnastics',
    progressionExercise: 'gym-hollow-rock',
  },
  {
    id: 'gym-hollow-rock',
    name: 'Hollow Body Rock',
    type: 'gymnastics',
    difficulty: 2,
    primaryMuscles: 'rectus-abdominis,hip-flexors',
    description: 'Rock back and forth while maintaining hollow body position. Builds dynamic core stability.',
    cues: 'Maintain hollow shape throughout, small controlled rocks',
    equipmentRequired: [],
    locations: ['gym', 'home', 'park', 'hotel'],
    movementPattern: 'anti_extension',
    skillLevel: 'intermediate',
    sourceMethodology: 'gymnastics',
    regressionExercise: 'gym-hollow-hold',
  },
  {
    id: 'gym-arch-hold',
    name: 'Arch Body Hold',
    type: 'gymnastics',
    difficulty: 2,
    primaryMuscles: 'erector-spinae,glute-max,hamstring-bicep',
    description: 'Lie face down, lift arms and legs off ground, squeeze glutes. Counterpart to hollow hold.',
    cues: 'Arms by ears, legs together, squeeze glutes, lift chest',
    equipmentRequired: [],
    locations: ['gym', 'home', 'park', 'hotel'],
    movementPattern: 'anti_flexion',
    skillLevel: 'intermediate',
    sourceMethodology: 'gymnastics',
  },
  {
    id: 'gym-tuck-l-sit',
    name: 'Tuck L-Sit',
    type: 'gymnastics',
    difficulty: 2,
    primaryMuscles: 'hip-flexors,triceps-long,rectus-abdominis',
    description: 'Support body on hands with knees tucked, feet off ground. First L-sit progression.',
    cues: 'Push through hands, depress shoulders, knees to chest',
    equipmentRequired: [],
    equipmentOptional: ['parallettes'],
    locations: ['gym', 'home', 'park'],
    movementPattern: 'push_isometric',
    skillLevel: 'intermediate',
    sourceMethodology: 'gymnastics',
    progressionExercise: 'gym-one-leg-l-sit',
  },
  {
    id: 'gym-one-leg-l-sit',
    name: 'One-Leg L-Sit',
    type: 'gymnastics',
    difficulty: 3,
    primaryMuscles: 'hip-flexors,triceps-long,rectus-abdominis',
    description: 'L-sit with one leg extended, one tucked. Intermediate progression toward full L-sit.',
    cues: 'Alternate legs, extended leg parallel to ground, point toe',
    equipmentRequired: [],
    equipmentOptional: ['parallettes'],
    locations: ['gym', 'home', 'park'],
    movementPattern: 'push_isometric',
    skillLevel: 'intermediate',
    sourceMethodology: 'gymnastics',
    regressionExercise: 'gym-tuck-l-sit',
    progressionExercise: 'bw-lsit',
  },
  {
    id: 'gym-v-sit',
    name: 'V-Sit',
    type: 'gymnastics',
    difficulty: 4,
    primaryMuscles: 'hip-flexors,rectus-abdominis,triceps-long',
    description: 'L-sit with legs raised above horizontal. Very advanced hip flexor and core strength.',
    cues: 'Legs above horizontal, point toes, maintain shoulder depression',
    equipmentRequired: [],
    equipmentOptional: ['parallettes'],
    locations: ['gym', 'home', 'park'],
    movementPattern: 'push_isometric',
    skillLevel: 'elite',
    sourceMethodology: 'gymnastics',
    regressionExercise: 'bw-lsit',
  },
];

// ============================================
// CALISTHENICS SKILL EXERCISES (40+)
// ============================================

export const calisthenicsExercises: ExerciseSeed[] = [
  // Muscle-Up Progressions
  {
    id: 'cali-high-pull',
    name: 'High Pull-Up',
    type: 'calisthenics',
    difficulty: 3,
    primaryMuscles: 'lats,biceps-long,rhomboids',
    description: 'Pull-up pulling as high as possible, ideally to chest or sternum. Builds pulling power for muscle-up.',
    cues: 'Explosive pull, aim for chest to bar, lead with chest not chin',
    equipmentRequired: ['pull_up_bar'],
    locations: ['gym', 'home', 'park'],
    movementPattern: 'pull_vertical',
    skillLevel: 'intermediate',
    sourceMethodology: 'calisthenics',
    progressionExercise: 'cali-muscle-up-transition',
  },
  {
    id: 'cali-muscle-up-transition',
    name: 'Muscle-Up Transition Practice',
    type: 'calisthenics',
    difficulty: 3,
    primaryMuscles: 'lats,chest-lower,triceps-long',
    description: 'Practice the transition portion of muscle-up from low bar or with band assistance.',
    cues: 'Pull high, lean over bar aggressively, keep elbows close',
    equipmentRequired: ['pull_up_bar'],
    equipmentOptional: ['resistance_band'],
    locations: ['gym', 'home', 'park'],
    movementPattern: 'pull_push_compound',
    skillLevel: 'advanced',
    sourceMethodology: 'calisthenics',
    regressionExercise: 'cali-high-pull',
    progressionExercise: 'cali-kipping-muscle-up',
  },
  {
    id: 'cali-kipping-muscle-up',
    name: 'Kipping Muscle-Up',
    type: 'calisthenics',
    difficulty: 4,
    primaryMuscles: 'lats,chest-lower,triceps-long',
    description: 'Muscle-up using swing momentum for the transition. Gateway to strict muscle-up.',
    cues: 'Generate swing, pull and lean simultaneously, press to lockout',
    equipmentRequired: ['pull_up_bar'],
    locations: ['gym', 'park'],
    movementPattern: 'pull_push_compound',
    skillLevel: 'advanced',
    sourceMethodology: 'calisthenics',
    regressionExercise: 'cali-muscle-up-transition',
    progressionExercise: 'cali-strict-muscle-up',
  },
  {
    id: 'cali-strict-muscle-up',
    name: 'Strict Muscle-Up',
    type: 'calisthenics',
    difficulty: 5,
    primaryMuscles: 'lats,chest-lower,triceps-long',
    description: 'Muscle-up without any swing or kip. Pure strength from dead hang to support.',
    cues: 'No swing, explosive pull from dead hang, smooth transition',
    equipmentRequired: ['pull_up_bar'],
    locations: ['gym', 'park'],
    movementPattern: 'pull_push_compound',
    skillLevel: 'elite',
    sourceMethodology: 'calisthenics',
    regressionExercise: 'cali-kipping-muscle-up',
  },

  // One-Arm Pull-Up Progressions
  {
    id: 'cali-archer-pullup',
    name: 'Archer Pull-Up',
    type: 'calisthenics',
    difficulty: 4,
    primaryMuscles: 'lats,biceps-long,teres-major',
    description: 'Wide grip pull-up shifting weight to one arm, assist arm stays straight.',
    cues: 'Shift weight to working arm, assist arm straight, alternate sides',
    equipmentRequired: ['pull_up_bar'],
    locations: ['gym', 'home', 'park'],
    movementPattern: 'pull_vertical',
    skillLevel: 'advanced',
    sourceMethodology: 'calisthenics',
    progressionExercise: 'cali-one-arm-negative',
  },
  {
    id: 'cali-one-arm-negative',
    name: 'One-Arm Pull-Up Negative',
    type: 'calisthenics',
    difficulty: 4,
    primaryMuscles: 'lats,biceps-long,brachialis',
    description: 'Lower slowly from top of pull-up using one arm. Eccentric training for one-arm pull-up.',
    cues: 'Jump or use other arm to get to top, lower as slowly as possible',
    equipmentRequired: ['pull_up_bar'],
    locations: ['gym', 'home', 'park'],
    movementPattern: 'pull_eccentric',
    skillLevel: 'advanced',
    sourceMethodology: 'calisthenics',
    regressionExercise: 'cali-archer-pullup',
    progressionExercise: 'cali-assisted-one-arm',
  },
  {
    id: 'cali-assisted-one-arm',
    name: 'Assisted One-Arm Pull-Up',
    type: 'calisthenics',
    difficulty: 5,
    primaryMuscles: 'lats,biceps-long,brachialis',
    description: 'One-arm pull-up with minimal assistance from towel, band, or finger grip.',
    cues: 'Use minimal assistance, focus on pulling arm, reduce help over time',
    equipmentRequired: ['pull_up_bar'],
    equipmentOptional: ['towel', 'resistance_band'],
    locations: ['gym', 'home', 'park'],
    movementPattern: 'pull_vertical',
    skillLevel: 'elite',
    sourceMethodology: 'calisthenics',
    regressionExercise: 'cali-one-arm-negative',
    progressionExercise: 'cali-one-arm-pullup',
  },
  {
    id: 'cali-one-arm-pullup',
    name: 'One-Arm Pull-Up',
    type: 'calisthenics',
    difficulty: 5,
    primaryMuscles: 'lats,biceps-long,brachialis,obliques',
    description: 'Full pull-up using only one arm from dead hang. Elite pulling strength.',
    cues: 'Dead hang start, control rotation, full ROM',
    equipmentRequired: ['pull_up_bar'],
    locations: ['gym', 'home', 'park'],
    movementPattern: 'pull_vertical',
    skillLevel: 'elite',
    sourceMethodology: 'calisthenics',
    regressionExercise: 'cali-assisted-one-arm',
  },

  // Human Flag Progressions
  {
    id: 'cali-vertical-flag',
    name: 'Vertical Flag Hold',
    type: 'calisthenics',
    difficulty: 3,
    primaryMuscles: 'obliques,lats,delt-side',
    description: 'Hold body vertically (feet up) on pole. Foundation for human flag.',
    cues: 'Push with bottom arm, pull with top, body straight up',
    equipmentRequired: ['vertical_pole'],
    locations: ['gym', 'park'],
    movementPattern: 'anti_lateral',
    skillLevel: 'advanced',
    sourceMethodology: 'calisthenics',
    progressionExercise: 'cali-tuck-flag',
  },
  {
    id: 'cali-tuck-flag',
    name: 'Tuck Human Flag',
    type: 'calisthenics',
    difficulty: 4,
    primaryMuscles: 'obliques,lats,delt-side',
    description: 'Human flag with knees tucked to reduce lever arm.',
    cues: 'Maintain push-pull tension, tuck knees tight, tilt from vertical',
    equipmentRequired: ['vertical_pole'],
    locations: ['gym', 'park'],
    movementPattern: 'anti_lateral',
    skillLevel: 'advanced',
    sourceMethodology: 'calisthenics',
    regressionExercise: 'cali-vertical-flag',
    progressionExercise: 'cali-straddle-flag',
  },
  {
    id: 'cali-straddle-flag',
    name: 'Straddle Human Flag',
    type: 'calisthenics',
    difficulty: 5,
    primaryMuscles: 'obliques,lats,delt-side,adductor-magnus',
    description: 'Human flag with legs extended in straddle position.',
    cues: 'Wide straddle, straight legs, body approaching horizontal',
    equipmentRequired: ['vertical_pole'],
    locations: ['gym', 'park'],
    movementPattern: 'anti_lateral',
    skillLevel: 'elite',
    sourceMethodology: 'calisthenics',
    regressionExercise: 'cali-tuck-flag',
    progressionExercise: 'cali-full-flag',
  },
  {
    id: 'cali-full-flag',
    name: 'Full Human Flag',
    type: 'calisthenics',
    difficulty: 5,
    primaryMuscles: 'obliques,lats,delt-side,glute-med',
    description: 'Full human flag with body horizontal, legs together. Iconic calisthenics skill.',
    cues: 'Legs together, body horizontal, perfect push-pull balance',
    equipmentRequired: ['vertical_pole'],
    locations: ['gym', 'park'],
    movementPattern: 'anti_lateral',
    skillLevel: 'elite',
    sourceMethodology: 'calisthenics',
    regressionExercise: 'cali-straddle-flag',
  },

  // Back Lever Progressions
  {
    id: 'cali-tuck-back-lever',
    name: 'Tuck Back Lever',
    type: 'calisthenics',
    difficulty: 3,
    primaryMuscles: 'lats,biceps-long,delt-front',
    description: 'Inverted hang with knees tucked, body horizontal facing down.',
    cues: 'Inverted position, knees tucked, depress shoulders, arms straight',
    equipmentRequired: ['pull_up_bar'],
    equipmentOptional: ['gymnastics_rings'],
    locations: ['gym', 'home', 'park'],
    movementPattern: 'pull_isometric',
    skillLevel: 'intermediate',
    sourceMethodology: 'calisthenics',
    progressionExercise: 'cali-adv-tuck-back-lever',
  },
  {
    id: 'cali-adv-tuck-back-lever',
    name: 'Advanced Tuck Back Lever',
    type: 'calisthenics',
    difficulty: 3,
    primaryMuscles: 'lats,biceps-long,delt-front',
    description: 'Back lever with hips extended more, knees still bent.',
    cues: 'Open hip angle, back approaching horizontal, arms locked',
    equipmentRequired: ['pull_up_bar'],
    equipmentOptional: ['gymnastics_rings'],
    locations: ['gym', 'home', 'park'],
    movementPattern: 'pull_isometric',
    skillLevel: 'advanced',
    sourceMethodology: 'calisthenics',
    regressionExercise: 'cali-tuck-back-lever',
    progressionExercise: 'cali-straddle-back-lever',
  },
  {
    id: 'cali-straddle-back-lever',
    name: 'Straddle Back Lever',
    type: 'calisthenics',
    difficulty: 4,
    primaryMuscles: 'lats,biceps-long,delt-front',
    description: 'Back lever with legs extended in straddle.',
    cues: 'Wide straddle, straight legs, body horizontal',
    equipmentRequired: ['pull_up_bar'],
    equipmentOptional: ['gymnastics_rings'],
    locations: ['gym', 'home', 'park'],
    movementPattern: 'pull_isometric',
    skillLevel: 'advanced',
    sourceMethodology: 'calisthenics',
    regressionExercise: 'cali-adv-tuck-back-lever',
    progressionExercise: 'cali-full-back-lever',
  },
  {
    id: 'cali-full-back-lever',
    name: 'Full Back Lever',
    type: 'calisthenics',
    difficulty: 4,
    primaryMuscles: 'lats,biceps-long,delt-front,erector-spinae',
    description: 'Full back lever with legs together, body horizontal.',
    cues: 'Legs together, body horizontal, total body tension',
    equipmentRequired: ['pull_up_bar'],
    equipmentOptional: ['gymnastics_rings'],
    locations: ['gym', 'home', 'park'],
    movementPattern: 'pull_isometric',
    skillLevel: 'advanced',
    sourceMethodology: 'calisthenics',
    regressionExercise: 'cali-straddle-back-lever',
  },
];

// Combine all exercises
export const allClimbingGymnasticsExercises = [
  ...climbingExercises,
  ...gymnasticsExercises,
  ...calisthenicsExercises,
];

// ============================================
// MUSCLE ACTIVATIONS
// ============================================

export const climbingGymnasticsActivations: ActivationSeed[] = [
  // Climbing - Hangboard
  { exerciseId: 'climb-halfcrimp-20mm', muscleId: 'forearm-flexors', activation: 95 },
  { exerciseId: 'climb-halfcrimp-20mm', muscleId: 'lats', activation: 40 },
  { exerciseId: 'climb-halfcrimp-20mm', muscleId: 'biceps-long', activation: 30 },

  { exerciseId: 'climb-repeaters-7-3', muscleId: 'forearm-flexors', activation: 85 },
  { exerciseId: 'climb-repeaters-7-3', muscleId: 'lats', activation: 50 },
  { exerciseId: 'climb-repeaters-7-3', muscleId: 'biceps-long', activation: 40 },

  { exerciseId: 'climb-max-hangs', muscleId: 'forearm-flexors', activation: 100 },
  { exerciseId: 'climb-max-hangs', muscleId: 'lats', activation: 50 },
  { exerciseId: 'climb-max-hangs', muscleId: 'biceps-long', activation: 35 },

  { exerciseId: 'climb-lockoff-90', muscleId: 'biceps-long', activation: 85 },
  { exerciseId: 'climb-lockoff-90', muscleId: 'biceps-short', activation: 75 },
  { exerciseId: 'climb-lockoff-90', muscleId: 'lats', activation: 60 },

  { exerciseId: 'climb-frenchies', muscleId: 'biceps-long', activation: 90 },
  { exerciseId: 'climb-frenchies', muscleId: 'lats', activation: 70 },
  { exerciseId: 'climb-frenchies', muscleId: 'forearm-flexors', activation: 60 },

  // Gymnastics - Front Lever
  { exerciseId: 'gym-tuck-front-lever', muscleId: 'lats', activation: 80 },
  { exerciseId: 'gym-tuck-front-lever', muscleId: 'rectus-abdominis', activation: 70 },
  { exerciseId: 'gym-tuck-front-lever', muscleId: 'biceps-long', activation: 50 },

  { exerciseId: 'gym-full-front-lever', muscleId: 'lats', activation: 95 },
  { exerciseId: 'gym-full-front-lever', muscleId: 'rectus-abdominis', activation: 85 },
  { exerciseId: 'gym-full-front-lever', muscleId: 'biceps-long', activation: 60 },
  { exerciseId: 'gym-full-front-lever', muscleId: 'glute-max', activation: 50 },

  // Gymnastics - Planche
  { exerciseId: 'gym-planche-lean', muscleId: 'delt-front', activation: 70 },
  { exerciseId: 'gym-planche-lean', muscleId: 'chest-mid', activation: 50 },
  { exerciseId: 'gym-planche-lean', muscleId: 'triceps-long', activation: 40 },

  { exerciseId: 'gym-tuck-planche', muscleId: 'delt-front', activation: 85 },
  { exerciseId: 'gym-tuck-planche', muscleId: 'chest-mid', activation: 60 },
  { exerciseId: 'gym-tuck-planche', muscleId: 'triceps-long', activation: 50 },
  { exerciseId: 'gym-tuck-planche', muscleId: 'rectus-abdominis', activation: 60 },

  { exerciseId: 'gym-full-planche', muscleId: 'delt-front', activation: 100 },
  { exerciseId: 'gym-full-planche', muscleId: 'chest-mid', activation: 70 },
  { exerciseId: 'gym-full-planche', muscleId: 'triceps-long', activation: 60 },
  { exerciseId: 'gym-full-planche', muscleId: 'rectus-abdominis', activation: 80 },

  // Gymnastics - Rings
  { exerciseId: 'gym-ring-support', muscleId: 'chest-mid', activation: 60 },
  { exerciseId: 'gym-ring-support', muscleId: 'triceps-long', activation: 70 },
  { exerciseId: 'gym-ring-support', muscleId: 'delt-front', activation: 50 },

  { exerciseId: 'gym-ring-dip', muscleId: 'chest-lower', activation: 80 },
  { exerciseId: 'gym-ring-dip', muscleId: 'triceps-long', activation: 85 },
  { exerciseId: 'gym-ring-dip', muscleId: 'delt-front', activation: 60 },

  { exerciseId: 'gym-ring-muscle-up', muscleId: 'lats', activation: 85 },
  { exerciseId: 'gym-ring-muscle-up', muscleId: 'chest-lower', activation: 70 },
  { exerciseId: 'gym-ring-muscle-up', muscleId: 'triceps-long', activation: 80 },

  // Gymnastics - Handstand
  { exerciseId: 'gym-freestanding-handstand', muscleId: 'delt-front', activation: 80 },
  { exerciseId: 'gym-freestanding-handstand', muscleId: 'triceps-long', activation: 70 },
  { exerciseId: 'gym-freestanding-handstand', muscleId: 'rectus-abdominis', activation: 60 },
  { exerciseId: 'gym-freestanding-handstand', muscleId: 'traps-upper', activation: 50 },

  { exerciseId: 'gym-press-handstand', muscleId: 'delt-front', activation: 90 },
  { exerciseId: 'gym-press-handstand', muscleId: 'hip-flexors', activation: 85 },
  { exerciseId: 'gym-press-handstand', muscleId: 'triceps-long', activation: 70 },

  // Gymnastics - Core
  { exerciseId: 'gym-hollow-hold', muscleId: 'rectus-abdominis', activation: 75 },
  { exerciseId: 'gym-hollow-hold', muscleId: 'hip-flexors', activation: 60 },
  { exerciseId: 'gym-hollow-hold', muscleId: 'transverse-abdominis', activation: 70 },

  { exerciseId: 'gym-v-sit', muscleId: 'hip-flexors', activation: 95 },
  { exerciseId: 'gym-v-sit', muscleId: 'rectus-abdominis', activation: 80 },
  { exerciseId: 'gym-v-sit', muscleId: 'triceps-long', activation: 50 },

  // Calisthenics - Muscle Up
  { exerciseId: 'cali-high-pull', muscleId: 'lats', activation: 90 },
  { exerciseId: 'cali-high-pull', muscleId: 'biceps-long', activation: 70 },
  { exerciseId: 'cali-high-pull', muscleId: 'rhomboids', activation: 60 },

  { exerciseId: 'cali-strict-muscle-up', muscleId: 'lats', activation: 95 },
  { exerciseId: 'cali-strict-muscle-up', muscleId: 'chest-lower', activation: 75 },
  { exerciseId: 'cali-strict-muscle-up', muscleId: 'triceps-long', activation: 85 },

  // Calisthenics - One Arm Pull-Up
  { exerciseId: 'cali-archer-pullup', muscleId: 'lats', activation: 85 },
  { exerciseId: 'cali-archer-pullup', muscleId: 'biceps-long', activation: 75 },
  { exerciseId: 'cali-archer-pullup', muscleId: 'teres-major', activation: 60 },

  { exerciseId: 'cali-one-arm-pullup', muscleId: 'lats', activation: 100 },
  { exerciseId: 'cali-one-arm-pullup', muscleId: 'biceps-long', activation: 90 },
  { exerciseId: 'cali-one-arm-pullup', muscleId: 'brachialis', activation: 85 },
  { exerciseId: 'cali-one-arm-pullup', muscleId: 'obliques', activation: 60 },

  // Calisthenics - Human Flag
  { exerciseId: 'cali-full-flag', muscleId: 'obliques', activation: 95 },
  { exerciseId: 'cali-full-flag', muscleId: 'lats', activation: 80 },
  { exerciseId: 'cali-full-flag', muscleId: 'delt-side', activation: 75 },
  { exerciseId: 'cali-full-flag', muscleId: 'glute-med', activation: 60 },

  // Calisthenics - Back Lever
  { exerciseId: 'cali-full-back-lever', muscleId: 'lats', activation: 85 },
  { exerciseId: 'cali-full-back-lever', muscleId: 'biceps-long', activation: 70 },
  { exerciseId: 'cali-full-back-lever', muscleId: 'delt-front', activation: 60 },
  { exerciseId: 'cali-full-back-lever', muscleId: 'erector-spinae', activation: 50 },
];

export default {
  exercises: allClimbingGymnasticsExercises,
  activations: climbingGymnasticsActivations,
};
