/**
 * Olympic Weightlifting, Wrestling & Combat Sports Exercise Seeds
 *
 * 100+ exercises based on training methodologies from:
 * - USA Weightlifting
 * - NSCA Olympic lifting progressions
 * - NCAA wrestling strength programs
 * - Combat sports conditioning research
 */

import { ExerciseSeed, ActivationSeed } from './climbing-gymnastics-exercises';

// ============================================
// OLYMPIC WEIGHTLIFTING EXERCISES (40+)
// ============================================

export const olympicWeightliftingExercises: ExerciseSeed[] = [
  // Snatch Progressions
  {
    id: 'oly-snatch-grip-deadlift',
    name: 'Snatch Grip Deadlift',
    type: 'olympic_weightlifting',
    difficulty: 2,
    primaryMuscles: 'erector-spinae,glute-max,hamstring-bicep,traps-upper',
    description: 'Deadlift with wide snatch grip. Builds positional strength and lat engagement for the snatch pull.',
    cues: 'Wide grip (index on rings), keep back flat, drive through heels',
    equipmentRequired: ['barbell'],
    locations: ['gym', 'home'],
    movementPattern: 'hip_hinge',
    skillLevel: 'intermediate',
    sourceMethodology: 'olympic_weightlifting',
    progressionExercise: 'oly-snatch-pull',
  },
  {
    id: 'oly-snatch-pull',
    name: 'Snatch Pull',
    type: 'olympic_weightlifting',
    difficulty: 2,
    primaryMuscles: 'traps-upper,erector-spinae,glute-max,gastrocnemius',
    description: 'First and second pull of the snatch without the catch. Develops explosive hip extension and shrug.',
    cues: 'Explode at hip, shrug violently, stay over bar until explosion',
    equipmentRequired: ['barbell'],
    locations: ['gym'],
    movementPattern: 'pull_explosive',
    skillLevel: 'intermediate',
    sourceMethodology: 'olympic_weightlifting',
    regressionExercise: 'oly-snatch-grip-deadlift',
    progressionExercise: 'oly-hang-snatch',
  },
  {
    id: 'oly-snatch-high-pull',
    name: 'Snatch High Pull',
    type: 'olympic_weightlifting',
    difficulty: 3,
    primaryMuscles: 'traps-upper,delt-side,erector-spinae,glute-max',
    description: 'Snatch pull continuing to high pull position. Builds turnover speed and timing.',
    cues: 'Full extension, elbows high and outside, bar stays close',
    equipmentRequired: ['barbell'],
    locations: ['gym'],
    movementPattern: 'pull_explosive',
    skillLevel: 'intermediate',
    sourceMethodology: 'olympic_weightlifting',
  },
  {
    id: 'oly-hang-snatch',
    name: 'Hang Snatch',
    type: 'olympic_weightlifting',
    difficulty: 3,
    primaryMuscles: 'traps-upper,delt-side,glute-max,quad-rectus',
    description: 'Full snatch from hang position (above knee). Simplifies the lift by removing first pull.',
    cues: 'Start above knee, explosive hip drive, fast elbows, catch deep',
    equipmentRequired: ['barbell'],
    locations: ['gym'],
    movementPattern: 'pull_catch_compound',
    skillLevel: 'advanced',
    sourceMethodology: 'olympic_weightlifting',
    regressionExercise: 'oly-snatch-pull',
    progressionExercise: 'oly-power-snatch',
  },
  {
    id: 'oly-power-snatch',
    name: 'Power Snatch',
    type: 'olympic_weightlifting',
    difficulty: 4,
    primaryMuscles: 'traps-upper,delt-side,glute-max,quad-rectus',
    description: 'Full snatch caught in power position (above parallel). Develops speed and power.',
    cues: 'Pull high, punch up fast, catch with knees slightly bent',
    equipmentRequired: ['barbell'],
    locations: ['gym'],
    movementPattern: 'pull_catch_compound',
    skillLevel: 'advanced',
    sourceMethodology: 'olympic_weightlifting',
    regressionExercise: 'oly-hang-snatch',
    progressionExercise: 'oly-full-snatch',
  },
  {
    id: 'oly-full-snatch',
    name: 'Full Snatch',
    type: 'olympic_weightlifting',
    difficulty: 5,
    primaryMuscles: 'traps-upper,delt-side,glute-max,quad-rectus,erector-spinae',
    description: 'Complete snatch from floor to overhead squat. The most technical barbell lift.',
    cues: 'First pull slow, explode at hip, pull under fast, catch in bottom',
    equipmentRequired: ['barbell'],
    locations: ['gym'],
    movementPattern: 'pull_catch_compound',
    skillLevel: 'elite',
    sourceMethodology: 'olympic_weightlifting',
    regressionExercise: 'oly-power-snatch',
  },
  {
    id: 'oly-snatch-balance',
    name: 'Snatch Balance',
    type: 'olympic_weightlifting',
    difficulty: 4,
    primaryMuscles: 'quad-rectus,delt-side,triceps-long,glute-max',
    description: 'Drop under bar from back squat position to overhead squat. Builds receiving speed.',
    cues: 'Dip, drive, drop fast, punch overhead, catch in bottom',
    equipmentRequired: ['barbell'],
    locations: ['gym'],
    movementPattern: 'squat_overhead',
    skillLevel: 'advanced',
    sourceMethodology: 'olympic_weightlifting',
  },
  {
    id: 'oly-overhead-squat',
    name: 'Overhead Squat',
    type: 'olympic_weightlifting',
    difficulty: 3,
    primaryMuscles: 'quad-rectus,glute-max,delt-side,erector-spinae',
    description: 'Deep squat with barbell locked out overhead. Essential receiving position for snatch.',
    cues: 'Snatch grip, bar over mid-foot, upright torso, full depth',
    equipmentRequired: ['barbell'],
    locations: ['gym', 'home'],
    movementPattern: 'squat_overhead',
    skillLevel: 'intermediate',
    sourceMethodology: 'olympic_weightlifting',
  },

  // Clean Progressions
  {
    id: 'oly-clean-grip-deadlift',
    name: 'Clean Grip Deadlift',
    type: 'olympic_weightlifting',
    difficulty: 2,
    primaryMuscles: 'erector-spinae,glute-max,hamstring-bicep,quad-rectus',
    description: 'Deadlift with clean grip (shoulder width). Builds positional strength for clean pull.',
    cues: 'Hook grip, shoulders over bar, drive through whole foot',
    equipmentRequired: ['barbell'],
    locations: ['gym', 'home'],
    movementPattern: 'hip_hinge',
    skillLevel: 'intermediate',
    sourceMethodology: 'olympic_weightlifting',
    progressionExercise: 'oly-clean-pull',
  },
  {
    id: 'oly-clean-pull',
    name: 'Clean Pull',
    type: 'olympic_weightlifting',
    difficulty: 2,
    primaryMuscles: 'traps-upper,erector-spinae,glute-max,quad-rectus',
    description: 'First and second pull of the clean. Develops explosive power for the clean.',
    cues: 'Stay over bar, explode at hip, shrug and rise on toes',
    equipmentRequired: ['barbell'],
    locations: ['gym'],
    movementPattern: 'pull_explosive',
    skillLevel: 'intermediate',
    sourceMethodology: 'olympic_weightlifting',
    regressionExercise: 'oly-clean-grip-deadlift',
    progressionExercise: 'oly-hang-clean',
  },
  {
    id: 'oly-hang-clean',
    name: 'Hang Clean',
    type: 'olympic_weightlifting',
    difficulty: 3,
    primaryMuscles: 'traps-upper,quad-rectus,glute-max,delt-front',
    description: 'Full clean from hang position. Develops timing and receiving position.',
    cues: 'Start above knee, explosive hip, fast elbows, catch in front rack',
    equipmentRequired: ['barbell'],
    locations: ['gym'],
    movementPattern: 'pull_catch_compound',
    skillLevel: 'advanced',
    sourceMethodology: 'olympic_weightlifting',
    regressionExercise: 'oly-clean-pull',
    progressionExercise: 'oly-power-clean',
  },
  {
    id: 'oly-power-clean',
    name: 'Power Clean',
    type: 'olympic_weightlifting',
    difficulty: 3,
    primaryMuscles: 'traps-upper,quad-rectus,glute-max,delt-front',
    description: 'Clean caught in power position. Common athletic training exercise.',
    cues: 'Pull high, fast elbows, catch with soft knees, upright torso',
    equipmentRequired: ['barbell'],
    locations: ['gym'],
    movementPattern: 'pull_catch_compound',
    skillLevel: 'advanced',
    sourceMethodology: 'olympic_weightlifting',
    regressionExercise: 'oly-hang-clean',
    progressionExercise: 'oly-full-clean',
  },
  {
    id: 'oly-full-clean',
    name: 'Full Clean',
    type: 'olympic_weightlifting',
    difficulty: 4,
    primaryMuscles: 'traps-upper,quad-rectus,glute-max,delt-front,erector-spinae',
    description: 'Complete clean from floor to front rack. Foundation for clean & jerk.',
    cues: 'Controlled first pull, explosive second pull, fast elbows under',
    equipmentRequired: ['barbell'],
    locations: ['gym'],
    movementPattern: 'pull_catch_compound',
    skillLevel: 'elite',
    sourceMethodology: 'olympic_weightlifting',
    regressionExercise: 'oly-power-clean',
    progressionExercise: 'oly-clean-and-jerk',
  },

  // Jerk Progressions
  {
    id: 'oly-push-press',
    name: 'Push Press',
    type: 'olympic_weightlifting',
    difficulty: 2,
    primaryMuscles: 'delt-front,triceps-long,quad-rectus,glute-max',
    description: 'Overhead press using leg drive. Builds overhead strength and dip/drive timing.',
    cues: 'Dip with knees over toes, drive through heels, lock out overhead',
    equipmentRequired: ['barbell'],
    locations: ['gym', 'home'],
    movementPattern: 'push_vertical',
    skillLevel: 'intermediate',
    sourceMethodology: 'olympic_weightlifting',
    progressionExercise: 'oly-push-jerk',
  },
  {
    id: 'oly-push-jerk',
    name: 'Push Jerk',
    type: 'olympic_weightlifting',
    difficulty: 3,
    primaryMuscles: 'delt-front,triceps-long,quad-rectus,glute-max',
    description: 'Jerk caught with feet in squat stance. Develops drive timing and overhead stability.',
    cues: 'Dip, drive, push under, catch with soft knees, stand to finish',
    equipmentRequired: ['barbell'],
    locations: ['gym'],
    movementPattern: 'push_catch_compound',
    skillLevel: 'advanced',
    sourceMethodology: 'olympic_weightlifting',
    regressionExercise: 'oly-push-press',
    progressionExercise: 'oly-split-jerk',
  },
  {
    id: 'oly-split-jerk',
    name: 'Split Jerk',
    type: 'olympic_weightlifting',
    difficulty: 4,
    primaryMuscles: 'delt-front,triceps-long,quad-rectus,glute-max,hip-flexors',
    description: 'Competition jerk with split receiving position. Most efficient jerk style.',
    cues: 'Vertical dip/drive, split fast and even, recover front foot first',
    equipmentRequired: ['barbell'],
    locations: ['gym'],
    movementPattern: 'push_catch_compound',
    skillLevel: 'elite',
    sourceMethodology: 'olympic_weightlifting',
    regressionExercise: 'oly-push-jerk',
  },
  {
    id: 'oly-clean-and-jerk',
    name: 'Clean & Jerk',
    type: 'olympic_weightlifting',
    difficulty: 5,
    primaryMuscles: 'traps-upper,quad-rectus,glute-max,delt-front,triceps-long',
    description: 'Complete competition lift. Clean to front rack, then jerk overhead.',
    cues: 'Clean, recover, reset, dip/drive, split, recover, stand',
    equipmentRequired: ['barbell'],
    locations: ['gym'],
    movementPattern: 'pull_push_compound',
    skillLevel: 'elite',
    sourceMethodology: 'olympic_weightlifting',
    regressionExercise: 'oly-full-clean',
  },

  // Accessory Lifts
  {
    id: 'oly-front-squat',
    name: 'Front Squat',
    type: 'olympic_weightlifting',
    difficulty: 2,
    primaryMuscles: 'quad-rectus,glute-max,erector-spinae,rectus-abdominis',
    description: 'Squat with barbell in front rack. Essential for clean receiving strength.',
    cues: 'Elbows high, upright torso, full depth, drive out of hole',
    equipmentRequired: ['barbell'],
    locations: ['gym', 'home'],
    movementPattern: 'squat',
    skillLevel: 'intermediate',
    sourceMethodology: 'olympic_weightlifting',
  },
  {
    id: 'oly-pause-front-squat',
    name: 'Pause Front Squat',
    type: 'olympic_weightlifting',
    difficulty: 3,
    primaryMuscles: 'quad-rectus,glute-max,erector-spinae,rectus-abdominis',
    description: 'Front squat with 2-3 second pause in hole. Builds strength out of receiving position.',
    cues: '2-3 second pause at bottom, maintain position, drive up explosively',
    equipmentRequired: ['barbell'],
    locations: ['gym'],
    movementPattern: 'squat',
    skillLevel: 'advanced',
    sourceMethodology: 'olympic_weightlifting',
  },
  {
    id: 'oly-clean-deadlift',
    name: 'Clean Deadlift',
    type: 'olympic_weightlifting',
    difficulty: 2,
    primaryMuscles: 'erector-spinae,glute-max,hamstring-bicep,traps-mid',
    description: 'Deadlift with clean setup and tempo. Builds positional strength for clean.',
    cues: 'Hook grip, controlled tempo, maintain back angle through first pull',
    equipmentRequired: ['barbell'],
    locations: ['gym', 'home'],
    movementPattern: 'hip_hinge',
    skillLevel: 'intermediate',
    sourceMethodology: 'olympic_weightlifting',
  },
  {
    id: 'oly-snatch-deadlift',
    name: 'Snatch Deadlift',
    type: 'olympic_weightlifting',
    difficulty: 2,
    primaryMuscles: 'erector-spinae,glute-max,hamstring-bicep,lats',
    description: 'Deadlift with snatch grip. Builds back and lat strength for snatch.',
    cues: 'Wide grip, lats engaged, maintain back angle, controlled tempo',
    equipmentRequired: ['barbell'],
    locations: ['gym', 'home'],
    movementPattern: 'hip_hinge',
    skillLevel: 'intermediate',
    sourceMethodology: 'olympic_weightlifting',
  },
  {
    id: 'oly-behind-neck-press',
    name: 'Behind Neck Press (Snatch Grip)',
    type: 'olympic_weightlifting',
    difficulty: 2,
    primaryMuscles: 'delt-side,triceps-long,traps-upper',
    description: 'Overhead press from behind neck with snatch grip. Builds overhead stability.',
    cues: 'Snatch grip, press straight up, lock out fully, control descent',
    equipmentRequired: ['barbell'],
    locations: ['gym'],
    movementPattern: 'push_vertical',
    skillLevel: 'intermediate',
    sourceMethodology: 'olympic_weightlifting',
  },
  {
    id: 'oly-sotts-press',
    name: 'Sotts Press',
    type: 'olympic_weightlifting',
    difficulty: 4,
    primaryMuscles: 'delt-side,triceps-long,quad-rectus,rectus-abdominis',
    description: 'Overhead press performed in bottom of squat position. Extreme mobility and stability work.',
    cues: 'Full squat depth, press without rising, maintain upright torso',
    equipmentRequired: ['barbell'],
    locations: ['gym'],
    movementPattern: 'push_squat_compound',
    skillLevel: 'elite',
    sourceMethodology: 'olympic_weightlifting',
  },
];

// ============================================
// WRESTLING & GRAPPLING EXERCISES (35+)
// ============================================

export const wrestlingExercises: ExerciseSeed[] = [
  // Takedown Strength
  {
    id: 'wrest-sprawl',
    name: 'Sprawl',
    type: 'wrestling',
    difficulty: 1,
    primaryMuscles: 'hip-flexors,glute-max,rectus-abdominis,triceps-long',
    description: 'Defensive wrestling movement. Explosively shoot hips back and down to defend takedowns.',
    cues: 'Explosive hip extension back, hands on floor, drive hips to ground',
    equipmentRequired: [],
    locations: ['gym', 'home', 'outdoor'],
    movementPattern: 'hip_explosive',
    skillLevel: 'fundamental',
    sourceMethodology: 'wrestling',
  },
  {
    id: 'wrest-sprawl-burpee',
    name: 'Sprawl Burpee',
    type: 'wrestling',
    difficulty: 2,
    primaryMuscles: 'hip-flexors,glute-max,chest-mid,quad-rectus',
    description: 'Burpee with sprawl at bottom. Wrestling-specific conditioning.',
    cues: 'Drop to sprawl, push up, jump up, repeat continuously',
    equipmentRequired: [],
    locations: ['gym', 'home', 'outdoor'],
    movementPattern: 'full_body_explosive',
    skillLevel: 'intermediate',
    sourceMethodology: 'wrestling',
    regressionExercise: 'wrest-sprawl',
  },
  {
    id: 'wrest-level-change',
    name: 'Level Change Drill',
    type: 'wrestling',
    difficulty: 1,
    primaryMuscles: 'quad-rectus,glute-max,hip-flexors',
    description: 'Practice dropping levels for takedowns. Essential wrestling movement pattern.',
    cues: 'Drop hips, bend knees, keep back straight, head up',
    equipmentRequired: [],
    locations: ['gym', 'home', 'outdoor'],
    movementPattern: 'squat_explosive',
    skillLevel: 'fundamental',
    sourceMethodology: 'wrestling',
  },
  {
    id: 'wrest-penetration-step',
    name: 'Penetration Step Drill',
    type: 'wrestling',
    difficulty: 2,
    primaryMuscles: 'quad-rectus,glute-max,hip-flexors,gastrocnemius',
    description: 'Practice explosive penetration step for single/double leg takedowns.',
    cues: 'Level change, explosive step forward, trail knee to ground',
    equipmentRequired: [],
    locations: ['gym', 'home', 'outdoor'],
    movementPattern: 'lunge_explosive',
    skillLevel: 'intermediate',
    sourceMethodology: 'wrestling',
    regressionExercise: 'wrest-level-change',
  },
  {
    id: 'wrest-shot-drill',
    name: 'Shot Drill (with bands)',
    type: 'wrestling',
    difficulty: 2,
    primaryMuscles: 'quad-rectus,glute-max,erector-spinae,delt-front',
    description: 'Resisted takedown shot practice. Builds explosive power for single/double legs.',
    cues: 'Explosive penetration, drive through, finish the shot',
    equipmentRequired: ['resistance_band'],
    locations: ['gym', 'home'],
    movementPattern: 'lunge_explosive',
    skillLevel: 'intermediate',
    sourceMethodology: 'wrestling',
  },

  // Grip & Pull Strength
  {
    id: 'wrest-rope-climb',
    name: 'Rope Climb',
    type: 'wrestling',
    difficulty: 3,
    primaryMuscles: 'lats,biceps-long,forearm-flexors,rectus-abdominis',
    description: 'Climb rope using arms and legs. Fundamental grip and pulling strength.',
    cues: 'Secure grip, use legs to assist, pull with lats',
    equipmentRequired: ['climbing_rope'],
    locations: ['gym'],
    movementPattern: 'pull_climb',
    skillLevel: 'intermediate',
    sourceMethodology: 'wrestling',
  },
  {
    id: 'wrest-legless-rope-climb',
    name: 'Legless Rope Climb',
    type: 'wrestling',
    difficulty: 4,
    primaryMuscles: 'lats,biceps-long,forearm-flexors,rectus-abdominis',
    description: 'Rope climb using only arms. Elite upper body pulling strength.',
    cues: 'Arms only, pull from lats, maintain grip, control descent',
    equipmentRequired: ['climbing_rope'],
    locations: ['gym'],
    movementPattern: 'pull_climb',
    skillLevel: 'advanced',
    sourceMethodology: 'wrestling',
    regressionExercise: 'wrest-rope-climb',
  },
  {
    id: 'wrest-towel-pullup',
    name: 'Towel Pull-Up',
    type: 'wrestling',
    difficulty: 3,
    primaryMuscles: 'forearm-flexors,lats,biceps-long,brachialis',
    description: 'Pull-up gripping towels. Develops crushing grip strength for wrestling.',
    cues: 'Grip towels tight, pull from lats, squeeze at top',
    equipmentRequired: ['pull_up_bar', 'towel'],
    locations: ['gym', 'home'],
    movementPattern: 'pull_vertical',
    skillLevel: 'intermediate',
    sourceMethodology: 'wrestling',
  },
  {
    id: 'wrest-gi-pullup',
    name: 'Gi Grip Pull-Up',
    type: 'wrestling',
    difficulty: 3,
    primaryMuscles: 'forearm-flexors,lats,biceps-long',
    description: 'Pull-up gripping a gi or thick fabric. Develops lapel grip strength.',
    cues: 'Grip gi material, pull explosively, vary grip positions',
    equipmentRequired: ['pull_up_bar', 'gi'],
    locations: ['gym', 'home'],
    movementPattern: 'pull_vertical',
    skillLevel: 'intermediate',
    sourceMethodology: 'wrestling',
  },

  // Neck Strength
  {
    id: 'wrest-neck-bridge',
    name: 'Wrestling Neck Bridge',
    type: 'wrestling',
    difficulty: 3,
    primaryMuscles: 'erector-spinae,traps-upper',
    description: 'Bridge on head and feet. Traditional wrestling neck strengthening.',
    cues: 'Support on head, rock forward and back, build time gradually',
    equipmentRequired: [],
    locations: ['gym', 'home'],
    movementPattern: 'isometric',
    skillLevel: 'intermediate',
    sourceMethodology: 'wrestling',
  },
  {
    id: 'wrest-neck-harness',
    name: 'Neck Harness Extension',
    type: 'wrestling',
    difficulty: 2,
    primaryMuscles: 'traps-upper,erector-spinae',
    description: 'Neck extension with weighted harness. Controlled neck strengthening.',
    cues: 'Controlled tempo, full range of motion, start light',
    equipmentRequired: ['neck_harness', 'weight_plate'],
    locations: ['gym'],
    movementPattern: 'neck_extension',
    skillLevel: 'intermediate',
    sourceMethodology: 'wrestling',
  },
  {
    id: 'wrest-neck-rotation',
    name: 'Neck Rotation (Manual)',
    type: 'wrestling',
    difficulty: 1,
    primaryMuscles: 'traps-upper',
    description: 'Partner-assisted neck rotation. Builds rotational neck strength.',
    cues: 'Resist partner pressure, controlled movement, both directions',
    equipmentRequired: [],
    locations: ['gym', 'home'],
    movementPattern: 'neck_rotation',
    skillLevel: 'fundamental',
    sourceMethodology: 'wrestling',
  },

  // Core & Stability
  {
    id: 'wrest-turkish-getup',
    name: 'Turkish Get-Up',
    type: 'wrestling',
    difficulty: 3,
    primaryMuscles: 'rectus-abdominis,obliques,delt-side,glute-max',
    description: 'Ground-to-standing movement with weight overhead. Full body stability.',
    cues: 'Keep arm vertical, control each position, reverse to return',
    equipmentRequired: ['kettlebell'],
    equipmentOptional: ['dumbbell'],
    locations: ['gym', 'home'],
    movementPattern: 'full_body_stability',
    skillLevel: 'intermediate',
    sourceMethodology: 'wrestling',
  },
  {
    id: 'wrest-sandbag-shouldering',
    name: 'Sandbag Shouldering',
    type: 'wrestling',
    difficulty: 3,
    primaryMuscles: 'glute-max,erector-spinae,biceps-long,traps-upper',
    description: 'Lift sandbag from ground to shoulder. Mimics lifting opponent.',
    cues: 'Grip low, explosive hip drive, rotate to shoulder',
    equipmentRequired: ['sandbag'],
    locations: ['gym', 'outdoor'],
    movementPattern: 'pull_lift_compound',
    skillLevel: 'intermediate',
    sourceMethodology: 'wrestling',
  },
  {
    id: 'wrest-sandbag-carry',
    name: 'Sandbag Bear Hug Carry',
    type: 'wrestling',
    difficulty: 2,
    primaryMuscles: 'rectus-abdominis,biceps-short,erector-spinae,quad-rectus',
    description: 'Carry sandbag in bear hug position. Builds gripping endurance.',
    cues: 'Squeeze tight, upright posture, controlled steps',
    equipmentRequired: ['sandbag'],
    locations: ['gym', 'outdoor'],
    movementPattern: 'carry',
    skillLevel: 'intermediate',
    sourceMethodology: 'wrestling',
  },

  // Hip & Explosion
  {
    id: 'wrest-hip-toss-drill',
    name: 'Hip Toss Drill (solo)',
    type: 'wrestling',
    difficulty: 2,
    primaryMuscles: 'obliques,glute-max,quad-rectus,erector-spinae',
    description: 'Practice hip toss motion without partner. Builds rotational power.',
    cues: 'Level change, turn hips through, explosive rotation',
    equipmentRequired: [],
    locations: ['gym', 'home', 'outdoor'],
    movementPattern: 'rotation_explosive',
    skillLevel: 'intermediate',
    sourceMethodology: 'wrestling',
  },
  {
    id: 'wrest-medicine-ball-slam',
    name: 'Medicine Ball Slam',
    type: 'wrestling',
    difficulty: 2,
    primaryMuscles: 'lats,rectus-abdominis,delt-front,triceps-long',
    description: 'Explosive overhead slam. Develops finishing power for throws.',
    cues: 'Full extension overhead, slam with full body, catch and repeat',
    equipmentRequired: ['medicine_ball'],
    locations: ['gym'],
    movementPattern: 'slam',
    skillLevel: 'intermediate',
    sourceMethodology: 'wrestling',
  },
  {
    id: 'wrest-rotational-throw',
    name: 'Medicine Ball Rotational Throw',
    type: 'wrestling',
    difficulty: 2,
    primaryMuscles: 'obliques,glute-max,delt-front,chest-mid',
    description: 'Rotational throw against wall. Develops throwing power.',
    cues: 'Load hips, rotate through, release at chest height',
    equipmentRequired: ['medicine_ball'],
    locations: ['gym'],
    movementPattern: 'rotation_throw',
    skillLevel: 'intermediate',
    sourceMethodology: 'wrestling',
  },

  // Conditioning
  {
    id: 'wrest-bear-crawl',
    name: 'Bear Crawl',
    type: 'wrestling',
    difficulty: 1,
    primaryMuscles: 'delt-front,quad-rectus,rectus-abdominis,hip-flexors',
    description: 'Crawl on hands and feet. Fundamental wrestling conditioning.',
    cues: 'Hips low, opposite arm/leg, keep core tight',
    equipmentRequired: [],
    locations: ['gym', 'home', 'outdoor'],
    movementPattern: 'crawl',
    skillLevel: 'fundamental',
    sourceMethodology: 'wrestling',
  },
  {
    id: 'wrest-crab-walk',
    name: 'Crab Walk',
    type: 'wrestling',
    difficulty: 1,
    primaryMuscles: 'triceps-long,glute-max,hamstring-bicep,delt-rear',
    description: 'Walk on hands and feet facing up. Builds posterior chain.',
    cues: 'Hips high, controlled movement, both directions',
    equipmentRequired: [],
    locations: ['gym', 'home', 'outdoor'],
    movementPattern: 'crawl',
    skillLevel: 'fundamental',
    sourceMethodology: 'wrestling',
  },
  {
    id: 'wrest-duck-walk',
    name: 'Duck Walk',
    type: 'wrestling',
    difficulty: 2,
    primaryMuscles: 'quad-rectus,glute-max,hip-flexors,gastrocnemius',
    description: 'Walk in deep squat position. Builds leg endurance for wrestling.',
    cues: 'Full squat depth, stay low, controlled steps',
    equipmentRequired: [],
    locations: ['gym', 'home', 'outdoor'],
    movementPattern: 'squat_walk',
    skillLevel: 'intermediate',
    sourceMethodology: 'wrestling',
  },
  {
    id: 'wrest-fireman-carry',
    name: 'Fireman Carry (sandbag)',
    type: 'wrestling',
    difficulty: 3,
    primaryMuscles: 'traps-upper,quad-rectus,glute-max,erector-spinae',
    description: 'Carry sandbag across shoulders. Mimics fireman carry position.',
    cues: 'Load across shoulders, upright posture, controlled walking',
    equipmentRequired: ['sandbag'],
    locations: ['gym', 'outdoor'],
    movementPattern: 'carry',
    skillLevel: 'intermediate',
    sourceMethodology: 'wrestling',
  },
];

// ============================================
// COMBAT SPORTS CONDITIONING (25+)
// ============================================

export const combatConditioningExercises: ExerciseSeed[] = [
  // Striking Power
  {
    id: 'combat-heavy-bag-rounds',
    name: 'Heavy Bag Rounds',
    type: 'combat_conditioning',
    difficulty: 2,
    primaryMuscles: 'delt-front,chest-mid,triceps-long,obliques,gastrocnemius',
    description: 'Boxing rounds on heavy bag. Develops striking endurance and power.',
    cues: 'Full combinations, move around bag, maintain form',
    equipmentRequired: ['heavy_bag', 'boxing_gloves'],
    locations: ['gym'],
    movementPattern: 'striking',
    skillLevel: 'intermediate',
    sourceMethodology: 'boxing',
  },
  {
    id: 'combat-shadow-boxing',
    name: 'Shadow Boxing',
    type: 'combat_conditioning',
    difficulty: 1,
    primaryMuscles: 'delt-front,triceps-long,obliques,gastrocnemius',
    description: 'Boxing practice without equipment. Develops technique and endurance.',
    cues: 'Full extension on punches, move feet, visualize opponent',
    equipmentRequired: [],
    locations: ['gym', 'home', 'outdoor'],
    movementPattern: 'striking',
    skillLevel: 'fundamental',
    sourceMethodology: 'boxing',
  },
  {
    id: 'combat-speed-bag',
    name: 'Speed Bag',
    type: 'combat_conditioning',
    difficulty: 2,
    primaryMuscles: 'delt-front,biceps-short,forearm-flexors',
    description: 'Rhythm training on speed bag. Develops hand speed and timing.',
    cues: 'Small circles, consistent rhythm, both hands',
    equipmentRequired: ['speed_bag'],
    locations: ['gym'],
    movementPattern: 'striking',
    skillLevel: 'intermediate',
    sourceMethodology: 'boxing',
  },
  {
    id: 'combat-double-end-bag',
    name: 'Double End Bag',
    type: 'combat_conditioning',
    difficulty: 3,
    primaryMuscles: 'delt-front,triceps-long,obliques',
    description: 'Accuracy training on moving target. Develops timing and precision.',
    cues: 'Light, accurate punches, head movement, track the target',
    equipmentRequired: ['double_end_bag'],
    locations: ['gym'],
    movementPattern: 'striking',
    skillLevel: 'advanced',
    sourceMethodology: 'boxing',
  },

  // Kick Training
  {
    id: 'combat-thai-pad-rounds',
    name: 'Thai Pad Rounds',
    type: 'combat_conditioning',
    difficulty: 2,
    primaryMuscles: 'quad-rectus,glute-max,obliques,hip-flexors',
    description: 'Partner pad work for kicks and knees. Full body striking workout.',
    cues: 'Turn hip over on kicks, full power, combinations',
    equipmentRequired: ['thai_pads'],
    locations: ['gym'],
    movementPattern: 'kicking',
    skillLevel: 'intermediate',
    sourceMethodology: 'muay_thai',
  },
  {
    id: 'combat-kick-bag',
    name: 'Kick Heavy Bag',
    type: 'combat_conditioning',
    difficulty: 2,
    primaryMuscles: 'quad-rectus,glute-max,obliques,gastrocnemius',
    description: 'Kicking practice on heavy bag. Develops leg power and technique.',
    cues: 'Full hip rotation, kick through target, both legs',
    equipmentRequired: ['heavy_bag'],
    locations: ['gym'],
    movementPattern: 'kicking',
    skillLevel: 'intermediate',
    sourceMethodology: 'muay_thai',
  },

  // Combat Conditioning
  {
    id: 'combat-battle-ropes',
    name: 'Battle Ropes',
    type: 'combat_conditioning',
    difficulty: 2,
    primaryMuscles: 'delt-front,biceps-short,rectus-abdominis,forearm-flexors',
    description: 'Alternating waves with heavy ropes. Develops arm endurance.',
    cues: 'Continuous waves, full range of motion, maintain intensity',
    equipmentRequired: ['battle_ropes'],
    locations: ['gym'],
    movementPattern: 'conditioning',
    skillLevel: 'intermediate',
    sourceMethodology: 'combat_conditioning',
  },
  {
    id: 'combat-sled-push',
    name: 'Sled Push',
    type: 'combat_conditioning',
    difficulty: 2,
    primaryMuscles: 'quad-rectus,glute-max,gastrocnemius,delt-front',
    description: 'Push weighted sled. Develops leg drive power.',
    cues: 'Low drive angle, push through balls of feet, arms extended',
    equipmentRequired: ['sled'],
    locations: ['gym'],
    movementPattern: 'push_horizontal',
    skillLevel: 'intermediate',
    sourceMethodology: 'combat_conditioning',
  },
  {
    id: 'combat-sled-pull',
    name: 'Sled Pull (Row)',
    type: 'combat_conditioning',
    difficulty: 2,
    primaryMuscles: 'lats,biceps-long,rhomboids,erector-spinae',
    description: 'Pull sled toward you hand-over-hand. Develops pulling power.',
    cues: 'Sit back, pull from lats, continuous motion',
    equipmentRequired: ['sled', 'rope'],
    locations: ['gym'],
    movementPattern: 'pull_horizontal',
    skillLevel: 'intermediate',
    sourceMethodology: 'combat_conditioning',
  },
  {
    id: 'combat-tire-flip',
    name: 'Tire Flip',
    type: 'combat_conditioning',
    difficulty: 3,
    primaryMuscles: 'glute-max,quad-rectus,chest-mid,biceps-long',
    description: 'Flip large tire. Full body explosive power.',
    cues: 'Get under tire, drive with legs, push over at top',
    equipmentRequired: ['tire'],
    locations: ['gym', 'outdoor'],
    movementPattern: 'lift_push_compound',
    skillLevel: 'intermediate',
    sourceMethodology: 'strongman',
  },
  {
    id: 'combat-sledgehammer-swing',
    name: 'Sledgehammer Tire Strike',
    type: 'combat_conditioning',
    difficulty: 2,
    primaryMuscles: 'obliques,lats,forearm-flexors,rectus-abdominis',
    description: 'Strike tire with sledgehammer. Rotational power development.',
    cues: 'Full rotation, strike with purpose, alternate sides',
    equipmentRequired: ['sledgehammer', 'tire'],
    locations: ['gym', 'outdoor'],
    movementPattern: 'rotation_strike',
    skillLevel: 'intermediate',
    sourceMethodology: 'combat_conditioning',
  },
  {
    id: 'combat-farmers-walk',
    name: 'Farmers Walk',
    type: 'combat_conditioning',
    difficulty: 2,
    primaryMuscles: 'forearm-flexors,traps-upper,obliques,quad-rectus',
    description: 'Walk with heavy weights in each hand. Grip and core stability.',
    cues: 'Tall posture, controlled steps, grip tight',
    equipmentRequired: ['dumbbells'],
    equipmentOptional: ['farmers_handles', 'kettlebells'],
    locations: ['gym'],
    movementPattern: 'carry',
    skillLevel: 'intermediate',
    sourceMethodology: 'strongman',
  },
];

// ============================================
// COMBINED EXPORTS
// ============================================

export const allOlympicWrestlingExercises: ExerciseSeed[] = [
  ...olympicWeightliftingExercises,
  ...wrestlingExercises,
  ...combatConditioningExercises,
];

// ============================================
// MUSCLE ACTIVATIONS
// ============================================

export const olympicWrestlingActivations: ActivationSeed[] = [
  // Olympic - Snatch variations
  { exerciseId: 'oly-snatch-grip-deadlift', muscleId: 'erector-spinae', activation: 85 },
  { exerciseId: 'oly-snatch-grip-deadlift', muscleId: 'glute-max', activation: 80 },
  { exerciseId: 'oly-snatch-grip-deadlift', muscleId: 'hamstring-bicep', activation: 75 },
  { exerciseId: 'oly-snatch-grip-deadlift', muscleId: 'lats', activation: 70 },
  { exerciseId: 'oly-snatch-grip-deadlift', muscleId: 'traps-upper', activation: 50 },

  { exerciseId: 'oly-snatch-pull', muscleId: 'traps-upper', activation: 90 },
  { exerciseId: 'oly-snatch-pull', muscleId: 'erector-spinae', activation: 80 },
  { exerciseId: 'oly-snatch-pull', muscleId: 'glute-max', activation: 85 },
  { exerciseId: 'oly-snatch-pull', muscleId: 'gastrocnemius', activation: 60 },

  { exerciseId: 'oly-hang-snatch', muscleId: 'traps-upper', activation: 85 },
  { exerciseId: 'oly-hang-snatch', muscleId: 'delt-side', activation: 75 },
  { exerciseId: 'oly-hang-snatch', muscleId: 'glute-max', activation: 80 },
  { exerciseId: 'oly-hang-snatch', muscleId: 'quad-rectus', activation: 70 },

  { exerciseId: 'oly-power-snatch', muscleId: 'traps-upper', activation: 90 },
  { exerciseId: 'oly-power-snatch', muscleId: 'delt-side', activation: 80 },
  { exerciseId: 'oly-power-snatch', muscleId: 'glute-max', activation: 85 },
  { exerciseId: 'oly-power-snatch', muscleId: 'quad-rectus', activation: 75 },

  { exerciseId: 'oly-full-snatch', muscleId: 'traps-upper', activation: 95 },
  { exerciseId: 'oly-full-snatch', muscleId: 'delt-side', activation: 85 },
  { exerciseId: 'oly-full-snatch', muscleId: 'glute-max', activation: 90 },
  { exerciseId: 'oly-full-snatch', muscleId: 'quad-rectus', activation: 85 },
  { exerciseId: 'oly-full-snatch', muscleId: 'erector-spinae', activation: 80 },

  { exerciseId: 'oly-overhead-squat', muscleId: 'quad-rectus', activation: 85 },
  { exerciseId: 'oly-overhead-squat', muscleId: 'glute-max', activation: 80 },
  { exerciseId: 'oly-overhead-squat', muscleId: 'delt-side', activation: 70 },
  { exerciseId: 'oly-overhead-squat', muscleId: 'erector-spinae', activation: 65 },

  // Olympic - Clean variations
  { exerciseId: 'oly-clean-pull', muscleId: 'traps-upper', activation: 90 },
  { exerciseId: 'oly-clean-pull', muscleId: 'erector-spinae', activation: 80 },
  { exerciseId: 'oly-clean-pull', muscleId: 'glute-max', activation: 85 },
  { exerciseId: 'oly-clean-pull', muscleId: 'quad-rectus', activation: 70 },

  { exerciseId: 'oly-hang-clean', muscleId: 'traps-upper', activation: 85 },
  { exerciseId: 'oly-hang-clean', muscleId: 'quad-rectus', activation: 80 },
  { exerciseId: 'oly-hang-clean', muscleId: 'glute-max', activation: 80 },
  { exerciseId: 'oly-hang-clean', muscleId: 'delt-front', activation: 60 },

  { exerciseId: 'oly-power-clean', muscleId: 'traps-upper', activation: 90 },
  { exerciseId: 'oly-power-clean', muscleId: 'quad-rectus', activation: 85 },
  { exerciseId: 'oly-power-clean', muscleId: 'glute-max', activation: 85 },
  { exerciseId: 'oly-power-clean', muscleId: 'delt-front', activation: 65 },

  { exerciseId: 'oly-full-clean', muscleId: 'traps-upper', activation: 95 },
  { exerciseId: 'oly-full-clean', muscleId: 'quad-rectus', activation: 90 },
  { exerciseId: 'oly-full-clean', muscleId: 'glute-max', activation: 90 },
  { exerciseId: 'oly-full-clean', muscleId: 'delt-front', activation: 70 },
  { exerciseId: 'oly-full-clean', muscleId: 'erector-spinae', activation: 75 },

  // Olympic - Jerk variations
  { exerciseId: 'oly-push-press', muscleId: 'delt-front', activation: 85 },
  { exerciseId: 'oly-push-press', muscleId: 'triceps-long', activation: 75 },
  { exerciseId: 'oly-push-press', muscleId: 'quad-rectus', activation: 60 },
  { exerciseId: 'oly-push-press', muscleId: 'glute-max', activation: 50 },

  { exerciseId: 'oly-push-jerk', muscleId: 'delt-front', activation: 90 },
  { exerciseId: 'oly-push-jerk', muscleId: 'triceps-long', activation: 80 },
  { exerciseId: 'oly-push-jerk', muscleId: 'quad-rectus', activation: 70 },
  { exerciseId: 'oly-push-jerk', muscleId: 'glute-max', activation: 60 },

  { exerciseId: 'oly-split-jerk', muscleId: 'delt-front', activation: 95 },
  { exerciseId: 'oly-split-jerk', muscleId: 'triceps-long', activation: 85 },
  { exerciseId: 'oly-split-jerk', muscleId: 'quad-rectus', activation: 75 },
  { exerciseId: 'oly-split-jerk', muscleId: 'hip-flexors', activation: 60 },

  { exerciseId: 'oly-clean-and-jerk', muscleId: 'traps-upper', activation: 95 },
  { exerciseId: 'oly-clean-and-jerk', muscleId: 'quad-rectus', activation: 90 },
  { exerciseId: 'oly-clean-and-jerk', muscleId: 'glute-max', activation: 90 },
  { exerciseId: 'oly-clean-and-jerk', muscleId: 'delt-front', activation: 85 },
  { exerciseId: 'oly-clean-and-jerk', muscleId: 'triceps-long', activation: 80 },

  { exerciseId: 'oly-front-squat', muscleId: 'quad-rectus', activation: 95 },
  { exerciseId: 'oly-front-squat', muscleId: 'glute-max', activation: 80 },
  { exerciseId: 'oly-front-squat', muscleId: 'erector-spinae', activation: 65 },
  { exerciseId: 'oly-front-squat', muscleId: 'rectus-abdominis', activation: 60 },

  // Wrestling
  { exerciseId: 'wrest-sprawl', muscleId: 'hip-flexors', activation: 80 },
  { exerciseId: 'wrest-sprawl', muscleId: 'glute-max', activation: 75 },
  { exerciseId: 'wrest-sprawl', muscleId: 'rectus-abdominis', activation: 60 },
  { exerciseId: 'wrest-sprawl', muscleId: 'triceps-long', activation: 50 },

  { exerciseId: 'wrest-penetration-step', muscleId: 'quad-rectus', activation: 85 },
  { exerciseId: 'wrest-penetration-step', muscleId: 'glute-max', activation: 80 },
  { exerciseId: 'wrest-penetration-step', muscleId: 'hip-flexors', activation: 70 },

  { exerciseId: 'wrest-towel-pullup', muscleId: 'forearm-flexors', activation: 95 },
  { exerciseId: 'wrest-towel-pullup', muscleId: 'lats', activation: 85 },
  { exerciseId: 'wrest-towel-pullup', muscleId: 'biceps-long', activation: 75 },

  { exerciseId: 'wrest-rope-climb', muscleId: 'lats', activation: 90 },
  { exerciseId: 'wrest-rope-climb', muscleId: 'biceps-long', activation: 85 },
  { exerciseId: 'wrest-rope-climb', muscleId: 'forearm-flexors', activation: 90 },
  { exerciseId: 'wrest-rope-climb', muscleId: 'rectus-abdominis', activation: 60 },

  { exerciseId: 'wrest-turkish-getup', muscleId: 'rectus-abdominis', activation: 75 },
  { exerciseId: 'wrest-turkish-getup', muscleId: 'obliques', activation: 80 },
  { exerciseId: 'wrest-turkish-getup', muscleId: 'delt-side', activation: 70 },
  { exerciseId: 'wrest-turkish-getup', muscleId: 'glute-max', activation: 65 },

  { exerciseId: 'wrest-sandbag-shouldering', muscleId: 'glute-max', activation: 85 },
  { exerciseId: 'wrest-sandbag-shouldering', muscleId: 'erector-spinae', activation: 80 },
  { exerciseId: 'wrest-sandbag-shouldering', muscleId: 'biceps-long', activation: 70 },
  { exerciseId: 'wrest-sandbag-shouldering', muscleId: 'traps-upper', activation: 65 },

  { exerciseId: 'wrest-bear-crawl', muscleId: 'delt-front', activation: 70 },
  { exerciseId: 'wrest-bear-crawl', muscleId: 'quad-rectus', activation: 60 },
  { exerciseId: 'wrest-bear-crawl', muscleId: 'rectus-abdominis', activation: 75 },

  // Combat conditioning
  { exerciseId: 'combat-heavy-bag-rounds', muscleId: 'delt-front', activation: 80 },
  { exerciseId: 'combat-heavy-bag-rounds', muscleId: 'chest-mid', activation: 60 },
  { exerciseId: 'combat-heavy-bag-rounds', muscleId: 'triceps-long', activation: 70 },
  { exerciseId: 'combat-heavy-bag-rounds', muscleId: 'obliques', activation: 65 },

  { exerciseId: 'combat-battle-ropes', muscleId: 'delt-front', activation: 85 },
  { exerciseId: 'combat-battle-ropes', muscleId: 'biceps-short', activation: 70 },
  { exerciseId: 'combat-battle-ropes', muscleId: 'rectus-abdominis', activation: 60 },
  { exerciseId: 'combat-battle-ropes', muscleId: 'forearm-flexors', activation: 75 },

  { exerciseId: 'combat-sled-push', muscleId: 'quad-rectus', activation: 90 },
  { exerciseId: 'combat-sled-push', muscleId: 'glute-max', activation: 85 },
  { exerciseId: 'combat-sled-push', muscleId: 'gastrocnemius', activation: 70 },

  { exerciseId: 'combat-tire-flip', muscleId: 'glute-max', activation: 90 },
  { exerciseId: 'combat-tire-flip', muscleId: 'quad-rectus', activation: 85 },
  { exerciseId: 'combat-tire-flip', muscleId: 'chest-mid', activation: 70 },
  { exerciseId: 'combat-tire-flip', muscleId: 'biceps-long', activation: 65 },

  { exerciseId: 'combat-sledgehammer-swing', muscleId: 'obliques', activation: 90 },
  { exerciseId: 'combat-sledgehammer-swing', muscleId: 'lats', activation: 75 },
  { exerciseId: 'combat-sledgehammer-swing', muscleId: 'forearm-flexors', activation: 80 },
  { exerciseId: 'combat-sledgehammer-swing', muscleId: 'rectus-abdominis', activation: 70 },

  { exerciseId: 'combat-farmers-walk', muscleId: 'forearm-flexors', activation: 95 },
  { exerciseId: 'combat-farmers-walk', muscleId: 'traps-upper', activation: 85 },
  { exerciseId: 'combat-farmers-walk', muscleId: 'obliques', activation: 70 },
  { exerciseId: 'combat-farmers-walk', muscleId: 'quad-rectus', activation: 50 },
];
