/**
 * MuscleMap Exercise Database - 60+ exercises across three equipment paths
 */

export type EquipmentPath = 'bodyweight' | 'kettlebell' | 'freeweight';
export type MovementCategory = 'push' | 'pull' | 'legs' | 'hinge' | 'core' | 'carry';
export type MuscleRole = 'primary' | 'secondary' | 'stabilizer';

export interface MuscleActivation {
  muscleId: string;
  activation: number;
  role: MuscleRole;
}

export interface Exercise {
  id: string;
  name: string;
  path: EquipmentPath;
  category: MovementCategory;
  difficulty: 1 | 2 | 3 | 4 | 5;
  description: string;
  cues: string[];
  timePerSet: number;
  muscleActivations: MuscleActivation[];
}

export const exercises: Exercise[] = [
  // ========== BODYWEIGHT ==========
  { id: 'BW-PUSH-001', name: 'Push-Up', path: 'bodyweight', category: 'push', difficulty: 2,
    description: 'Classic horizontal press', cues: ['Hands shoulder-width', 'Core tight', 'Elbows 45°'], timePerSet: 60,
    muscleActivations: [
      { muscleId: 'CH-002', activation: 85, role: 'primary' },
      { muscleId: 'CH-001', activation: 75, role: 'primary' },
      { muscleId: 'SH-001', activation: 65, role: 'secondary' },
      { muscleId: 'SH-002', activation: 65, role: 'secondary' },
      { muscleId: 'AP-003', activation: 75, role: 'secondary' },
      { muscleId: 'AP-004', activation: 75, role: 'secondary' },
    ]},
  { id: 'BW-PUSH-002', name: 'Diamond Push-Up', path: 'bodyweight', category: 'push', difficulty: 3,
    description: 'Triceps-focused push-up', cues: ['Hands together', 'Elbows tight'], timePerSet: 60,
    muscleActivations: [
      { muscleId: 'AP-001', activation: 90, role: 'primary' },
      { muscleId: 'AP-002', activation: 90, role: 'primary' },
      { muscleId: 'CH-002', activation: 65, role: 'secondary' },
    ]},
  { id: 'BW-PUSH-003', name: 'Pike Push-Up', path: 'bodyweight', category: 'push', difficulty: 3,
    description: 'Shoulder-focused pressing', cues: ['Hips high', 'Head between arms'], timePerSet: 70,
    muscleActivations: [
      { muscleId: 'SH-001', activation: 85, role: 'primary' },
      { muscleId: 'SH-002', activation: 85, role: 'primary' },
      { muscleId: 'SH-003', activation: 70, role: 'secondary' },
      { muscleId: 'SH-004', activation: 70, role: 'secondary' },
    ]},
  { id: 'BW-PUSH-004', name: 'Dip', path: 'bodyweight', category: 'push', difficulty: 3,
    description: 'Vertical press for chest/triceps', cues: ['Lean forward for chest', 'Full depth'], timePerSet: 70,
    muscleActivations: [
      { muscleId: 'CH-002', activation: 80, role: 'primary' },
      { muscleId: 'CH-003', activation: 85, role: 'primary' },
      { muscleId: 'AP-001', activation: 80, role: 'primary' },
      { muscleId: 'AP-002', activation: 80, role: 'primary' },
    ]},
  { id: 'BW-PULL-001', name: 'Pull-Up', path: 'bodyweight', category: 'pull', difficulty: 3,
    description: 'Vertical pull overhand', cues: ['Pull elbows down', 'Chin over bar'], timePerSet: 70,
    muscleActivations: [
      { muscleId: 'BA-001', activation: 90, role: 'primary' },
      { muscleId: 'BA-002', activation: 90, role: 'primary' },
      { muscleId: 'AR-001', activation: 70, role: 'secondary' },
      { muscleId: 'AR-002', activation: 70, role: 'secondary' },
      { muscleId: 'SH-012', activation: 60, role: 'secondary' },
      { muscleId: 'SH-013', activation: 60, role: 'secondary' },
    ]},
  { id: 'BW-PULL-002', name: 'Chin-Up', path: 'bodyweight', category: 'pull', difficulty: 3,
    description: 'Vertical pull underhand', cues: ['Supinated grip', 'Pull chest to bar'], timePerSet: 70,
    muscleActivations: [
      { muscleId: 'BA-001', activation: 85, role: 'primary' },
      { muscleId: 'BA-002', activation: 85, role: 'primary' },
      { muscleId: 'AR-001', activation: 85, role: 'primary' },
      { muscleId: 'AR-002', activation: 85, role: 'primary' },
    ]},
  { id: 'BW-PULL-003', name: 'Inverted Row', path: 'bodyweight', category: 'pull', difficulty: 2,
    description: 'Horizontal pulling', cues: ['Body straight', 'Pull to chest'], timePerSet: 60,
    muscleActivations: [
      { muscleId: 'BA-001', activation: 75, role: 'primary' },
      { muscleId: 'BA-002', activation: 75, role: 'primary' },
      { muscleId: 'SH-012', activation: 70, role: 'primary' },
      { muscleId: 'SH-013', activation: 70, role: 'primary' },
    ]},
  { id: 'BW-LEGS-001', name: 'Bodyweight Squat', path: 'bodyweight', category: 'legs', difficulty: 1,
    description: 'Fundamental squat', cues: ['Knees track toes', 'Below parallel'], timePerSet: 50,
    muscleActivations: [
      { muscleId: 'LA-003', activation: 75, role: 'primary' },
      { muscleId: 'LA-004', activation: 75, role: 'primary' },
      { muscleId: 'LA-001', activation: 70, role: 'primary' },
      { muscleId: 'LA-002', activation: 70, role: 'primary' },
      { muscleId: 'HG-001', activation: 65, role: 'secondary' },
      { muscleId: 'HG-002', activation: 65, role: 'secondary' },
    ]},
  { id: 'BW-LEGS-002', name: 'Bulgarian Split Squat', path: 'bodyweight', category: 'legs', difficulty: 3,
    description: 'Single-leg squat', cues: ['Rear foot elevated', 'Vertical torso'], timePerSet: 70,
    muscleActivations: [
      { muscleId: 'LA-003', activation: 85, role: 'primary' },
      { muscleId: 'LA-001', activation: 80, role: 'primary' },
      { muscleId: 'HG-001', activation: 75, role: 'primary' },
      { muscleId: 'HG-003', activation: 70, role: 'secondary' },
    ]},
  { id: 'BW-LEGS-003', name: 'Lunge', path: 'bodyweight', category: 'legs', difficulty: 2,
    description: 'Alternating step', cues: ['Big step', 'Back knee hovers'], timePerSet: 60,
    muscleActivations: [
      { muscleId: 'LA-003', activation: 75, role: 'primary' },
      { muscleId: 'LA-004', activation: 75, role: 'primary' },
      { muscleId: 'HG-001', activation: 70, role: 'primary' },
      { muscleId: 'HG-002', activation: 70, role: 'primary' },
    ]},
  { id: 'BW-LEGS-004', name: 'Nordic Curl', path: 'bodyweight', category: 'legs', difficulty: 5,
    description: 'Eccentric hamstring', cues: ['Anchor feet', 'Control descent'], timePerSet: 90,
    muscleActivations: [
      { muscleId: 'LP-001', activation: 95, role: 'primary' },
      { muscleId: 'LP-002', activation: 95, role: 'primary' },
      { muscleId: 'LP-005', activation: 90, role: 'primary' },
      { muscleId: 'LP-006', activation: 90, role: 'primary' },
    ]},
  { id: 'BW-LEGS-005', name: 'Single-Leg Calf Raise', path: 'bodyweight', category: 'legs', difficulty: 2,
    description: 'Calf isolation', cues: ['Full stretch', 'Peak contraction'], timePerSet: 50,
    muscleActivations: [
      { muscleId: 'LP-009', activation: 85, role: 'primary' },
      { muscleId: 'LP-011', activation: 80, role: 'primary' },
      { muscleId: 'LP-013', activation: 70, role: 'secondary' },
    ]},
  { id: 'BW-HINGE-001', name: 'Glute Bridge', path: 'bodyweight', category: 'hinge', difficulty: 1,
    description: 'Hip extension', cues: ['Drive through heels', 'Squeeze glutes'], timePerSet: 50,
    muscleActivations: [
      { muscleId: 'HG-001', activation: 80, role: 'primary' },
      { muscleId: 'HG-002', activation: 80, role: 'primary' },
      { muscleId: 'LP-001', activation: 55, role: 'secondary' },
      { muscleId: 'LP-002', activation: 55, role: 'secondary' },
    ]},
  { id: 'BW-HINGE-002', name: 'Hip Thrust', path: 'bodyweight', category: 'hinge', difficulty: 2,
    description: 'Elevated hip extension', cues: ['Upper back on bench', 'Chin tucked'], timePerSet: 60,
    muscleActivations: [
      { muscleId: 'HG-001', activation: 90, role: 'primary' },
      { muscleId: 'HG-002', activation: 90, role: 'primary' },
      { muscleId: 'HG-003', activation: 60, role: 'secondary' },
      { muscleId: 'HG-004', activation: 60, role: 'secondary' },
    ]},
  { id: 'BW-CORE-001', name: 'Plank', path: 'bodyweight', category: 'core', difficulty: 1,
    description: 'Isometric core hold', cues: ['Body straight', 'Brace abs'], timePerSet: 60,
    muscleActivations: [
      { muscleId: 'CA-001', activation: 70, role: 'primary' },
      { muscleId: 'CA-002', activation: 70, role: 'primary' },
      { muscleId: 'CA-007', activation: 75, role: 'primary' },
    ]},
  { id: 'BW-CORE-002', name: 'Dead Bug', path: 'bodyweight', category: 'core', difficulty: 2,
    description: 'Anti-extension', cues: ['Lower back flat', 'Opposite limbs'], timePerSet: 60,
    muscleActivations: [
      { muscleId: 'CA-001', activation: 75, role: 'primary' },
      { muscleId: 'CA-002', activation: 80, role: 'primary' },
      { muscleId: 'CA-007', activation: 80, role: 'primary' },
    ]},
  { id: 'BW-CORE-003', name: 'Hanging Leg Raise', path: 'bodyweight', category: 'core', difficulty: 4,
    description: 'Advanced lower abs', cues: ['Hang from bar', 'Legs straight'], timePerSet: 70,
    muscleActivations: [
      { muscleId: 'CA-002', activation: 95, role: 'primary' },
      { muscleId: 'CA-001', activation: 80, role: 'primary' },
      { muscleId: 'HG-009', activation: 70, role: 'secondary' },
      { muscleId: 'HG-010', activation: 70, role: 'secondary' },
    ]},
  { id: 'BW-CORE-004', name: 'Side Plank', path: 'bodyweight', category: 'core', difficulty: 2,
    description: 'Lateral core', cues: ['Hips high', 'Body straight'], timePerSet: 50,
    muscleActivations: [
      { muscleId: 'CA-003', activation: 85, role: 'primary' },
      { muscleId: 'CA-005', activation: 80, role: 'primary' },
      { muscleId: 'CP-001', activation: 75, role: 'primary' },
    ]},

  // ========== KETTLEBELL ==========
  { id: 'KB-HINGE-001', name: 'Kettlebell Swing', path: 'kettlebell', category: 'hinge', difficulty: 2,
    description: 'Explosive hip hinge', cues: ['Hip hinge not squat', 'Snap hips'], timePerSet: 60,
    muscleActivations: [
      { muscleId: 'HG-001', activation: 90, role: 'primary' },
      { muscleId: 'HG-002', activation: 90, role: 'primary' },
      { muscleId: 'LP-001', activation: 70, role: 'primary' },
      { muscleId: 'LP-002', activation: 70, role: 'primary' },
      { muscleId: 'BA-003', activation: 65, role: 'secondary' },
      { muscleId: 'BA-004', activation: 65, role: 'secondary' },
      { muscleId: 'AR-015', activation: 60, role: 'stabilizer' },
      { muscleId: 'AR-016', activation: 60, role: 'stabilizer' },
    ]},
  { id: 'KB-HINGE-002', name: 'Kettlebell Snatch', path: 'kettlebell', category: 'hinge', difficulty: 4,
    description: 'Explosive overhead', cues: ['High pull', 'Punch through'], timePerSet: 80,
    muscleActivations: [
      { muscleId: 'HG-001', activation: 85, role: 'primary' },
      { muscleId: 'HG-002', activation: 85, role: 'primary' },
      { muscleId: 'SH-001', activation: 75, role: 'primary' },
      { muscleId: 'SH-002', activation: 75, role: 'primary' },
      { muscleId: 'SH-003', activation: 70, role: 'secondary' },
      { muscleId: 'SH-004', activation: 70, role: 'secondary' },
    ]},
  { id: 'KB-HINGE-003', name: 'Turkish Get-Up', path: 'kettlebell', category: 'hinge', difficulty: 4,
    description: 'Full-body movement', cues: ['Eyes on bell', 'Move slowly'], timePerSet: 120,
    muscleActivations: [
      { muscleId: 'SH-001', activation: 75, role: 'primary' },
      { muscleId: 'SH-002', activation: 75, role: 'primary' },
      { muscleId: 'CA-001', activation: 70, role: 'primary' },
      { muscleId: 'CA-003', activation: 70, role: 'primary' },
      { muscleId: 'CA-004', activation: 70, role: 'primary' },
      { muscleId: 'HG-001', activation: 65, role: 'secondary' },
      { muscleId: 'HG-002', activation: 65, role: 'secondary' },
    ]},
  { id: 'KB-LEGS-001', name: 'Goblet Squat', path: 'kettlebell', category: 'legs', difficulty: 2,
    description: 'Front-loaded squat', cues: ['Bell at chest', 'Elbows inside knees'], timePerSet: 70,
    muscleActivations: [
      { muscleId: 'LA-003', activation: 85, role: 'primary' },
      { muscleId: 'LA-004', activation: 85, role: 'primary' },
      { muscleId: 'LA-001', activation: 80, role: 'primary' },
      { muscleId: 'LA-002', activation: 80, role: 'primary' },
      { muscleId: 'HG-001', activation: 75, role: 'secondary' },
      { muscleId: 'HG-002', activation: 75, role: 'secondary' },
    ]},
  { id: 'KB-LEGS-002', name: 'Kettlebell Lunge', path: 'kettlebell', category: 'legs', difficulty: 2,
    description: 'Loaded lunge', cues: ['Arms at sides', 'Back knee hovers'], timePerSet: 70,
    muscleActivations: [
      { muscleId: 'LA-003', activation: 80, role: 'primary' },
      { muscleId: 'LA-004', activation: 80, role: 'primary' },
      { muscleId: 'HG-001', activation: 75, role: 'primary' },
      { muscleId: 'HG-002', activation: 75, role: 'primary' },
      { muscleId: 'AR-015', activation: 50, role: 'stabilizer' },
      { muscleId: 'AR-016', activation: 50, role: 'stabilizer' },
    ]},
  { id: 'KB-PUSH-001', name: 'Kettlebell Press', path: 'kettlebell', category: 'push', difficulty: 2,
    description: 'Strict overhead press', cues: ['Bell in rack', 'Brace core'], timePerSet: 70,
    muscleActivations: [
      { muscleId: 'SH-001', activation: 85, role: 'primary' },
      { muscleId: 'SH-002', activation: 85, role: 'primary' },
      { muscleId: 'SH-003', activation: 70, role: 'secondary' },
      { muscleId: 'SH-004', activation: 70, role: 'secondary' },
      { muscleId: 'AP-001', activation: 70, role: 'secondary' },
      { muscleId: 'AP-002', activation: 70, role: 'secondary' },
    ]},
  { id: 'KB-PUSH-002', name: 'Kettlebell Floor Press', path: 'kettlebell', category: 'push', difficulty: 2,
    description: 'Pressing from floor', cues: ['Triceps touch floor', 'Press up'], timePerSet: 70,
    muscleActivations: [
      { muscleId: 'CH-002', activation: 70, role: 'primary' },
      { muscleId: 'AP-001', activation: 80, role: 'primary' },
      { muscleId: 'AP-002', activation: 80, role: 'primary' },
      { muscleId: 'AP-003', activation: 85, role: 'primary' },
      { muscleId: 'AP-004', activation: 85, role: 'primary' },
    ]},
  { id: 'KB-PULL-001', name: 'Kettlebell Row', path: 'kettlebell', category: 'pull', difficulty: 2,
    description: 'Single-arm row', cues: ['Pull to hip', 'Squeeze at top'], timePerSet: 60,
    muscleActivations: [
      { muscleId: 'BA-001', activation: 80, role: 'primary' },
      { muscleId: 'SH-012', activation: 70, role: 'primary' },
      { muscleId: 'AR-001', activation: 60, role: 'secondary' },
      { muscleId: 'AR-015', activation: 50, role: 'stabilizer' },
    ]},
  { id: 'KB-PULL-002', name: 'Kettlebell High Pull', path: 'kettlebell', category: 'pull', difficulty: 3,
    description: 'Explosive pull', cues: ['Hip snap', 'Elbow high'], timePerSet: 70,
    muscleActivations: [
      { muscleId: 'HG-001', activation: 80, role: 'primary' },
      { muscleId: 'HG-002', activation: 80, role: 'primary' },
      { muscleId: 'SH-007', activation: 70, role: 'secondary' },
      { muscleId: 'SH-005', activation: 65, role: 'secondary' },
      { muscleId: 'SH-006', activation: 65, role: 'secondary' },
    ]},
  { id: 'KB-CARRY-001', name: 'Farmers Carry', path: 'kettlebell', category: 'carry', difficulty: 2,
    description: 'Walking with load', cues: ['Shoulders back', 'Grip hard'], timePerSet: 60,
    muscleActivations: [
      { muscleId: 'AR-015', activation: 85, role: 'primary' },
      { muscleId: 'AR-016', activation: 85, role: 'primary' },
      { muscleId: 'SH-007', activation: 75, role: 'primary' },
      { muscleId: 'CA-007', activation: 70, role: 'secondary' },
    ]},
  { id: 'KB-CARRY-002', name: 'Overhead Carry', path: 'kettlebell', category: 'carry', difficulty: 3,
    description: 'Walking with bell overhead', cues: ['Lock elbow', 'Ribs down'], timePerSet: 60,
    muscleActivations: [
      { muscleId: 'SH-001', activation: 70, role: 'primary' },
      { muscleId: 'SH-002', activation: 70, role: 'primary' },
      { muscleId: 'CA-003', activation: 70, role: 'primary' },
      { muscleId: 'CA-004', activation: 70, role: 'primary' },
    ]},

  // ========== FREEWEIGHT ==========
  { id: 'FW-PUSH-001', name: 'Barbell Bench Press', path: 'freeweight', category: 'push', difficulty: 2,
    description: 'Classic bench press', cues: ['Arch back', 'Touch chest'], timePerSet: 90,
    muscleActivations: [
      { muscleId: 'CH-002', activation: 90, role: 'primary' },
      { muscleId: 'CH-001', activation: 80, role: 'primary' },
      { muscleId: 'CH-003', activation: 70, role: 'primary' },
      { muscleId: 'SH-001', activation: 70, role: 'secondary' },
      { muscleId: 'SH-002', activation: 70, role: 'secondary' },
      { muscleId: 'AP-003', activation: 70, role: 'secondary' },
      { muscleId: 'AP-004', activation: 70, role: 'secondary' },
    ]},
  { id: 'FW-PUSH-002', name: 'Incline Dumbbell Press', path: 'freeweight', category: 'push', difficulty: 2,
    description: 'Upper chest focus', cues: ['30-45° angle', 'Press up'], timePerSet: 80,
    muscleActivations: [
      { muscleId: 'CH-001', activation: 90, role: 'primary' },
      { muscleId: 'CH-002', activation: 75, role: 'primary' },
      { muscleId: 'SH-001', activation: 75, role: 'secondary' },
      { muscleId: 'SH-002', activation: 75, role: 'secondary' },
    ]},
  { id: 'FW-PUSH-003', name: 'Overhead Press', path: 'freeweight', category: 'push', difficulty: 3,
    description: 'Standing barbell press', cues: ['Bar at collarbone', 'Brace core'], timePerSet: 80,
    muscleActivations: [
      { muscleId: 'SH-001', activation: 90, role: 'primary' },
      { muscleId: 'SH-002', activation: 90, role: 'primary' },
      { muscleId: 'SH-003', activation: 75, role: 'secondary' },
      { muscleId: 'SH-004', activation: 75, role: 'secondary' },
      { muscleId: 'AP-001', activation: 70, role: 'secondary' },
      { muscleId: 'AP-002', activation: 70, role: 'secondary' },
    ]},
  { id: 'FW-PUSH-004', name: 'Lateral Raise', path: 'freeweight', category: 'push', difficulty: 2,
    description: 'Lateral delt isolation', cues: ['Lead with elbows', 'Shoulder height'], timePerSet: 60,
    muscleActivations: [
      { muscleId: 'SH-003', activation: 95, role: 'primary' },
      { muscleId: 'SH-004', activation: 95, role: 'primary' },
      { muscleId: 'SH-007', activation: 55, role: 'secondary' },
    ]},
  { id: 'FW-PUSH-005', name: 'Tricep Pushdown', path: 'freeweight', category: 'push', difficulty: 1,
    description: 'Triceps isolation', cues: ['Elbows pinned', 'Full extension'], timePerSet: 50,
    muscleActivations: [
      { muscleId: 'AP-003', activation: 90, role: 'primary' },
      { muscleId: 'AP-004', activation: 90, role: 'primary' },
      { muscleId: 'AP-001', activation: 70, role: 'secondary' },
      { muscleId: 'AP-002', activation: 70, role: 'secondary' },
    ]},
  { id: 'FW-PULL-001', name: 'Barbell Row', path: 'freeweight', category: 'pull', difficulty: 3,
    description: 'Bent-over row', cues: ['Hinge 45°', 'Pull to chest'], timePerSet: 80,
    muscleActivations: [
      { muscleId: 'BA-001', activation: 85, role: 'primary' },
      { muscleId: 'BA-002', activation: 85, role: 'primary' },
      { muscleId: 'SH-012', activation: 75, role: 'primary' },
      { muscleId: 'SH-013', activation: 75, role: 'primary' },
      { muscleId: 'AR-001', activation: 60, role: 'secondary' },
      { muscleId: 'AR-002', activation: 60, role: 'secondary' },
    ]},
  { id: 'FW-PULL-002', name: 'Lat Pulldown', path: 'freeweight', category: 'pull', difficulty: 2,
    description: 'Cable vertical pull', cues: ['Pull to upper chest', 'Drive elbows down'], timePerSet: 70,
    muscleActivations: [
      { muscleId: 'BA-001', activation: 90, role: 'primary' },
      { muscleId: 'BA-002', activation: 90, role: 'primary' },
      { muscleId: 'AR-001', activation: 65, role: 'secondary' },
      { muscleId: 'AR-002', activation: 65, role: 'secondary' },
    ]},
  { id: 'FW-PULL-003', name: 'Face Pull', path: 'freeweight', category: 'pull', difficulty: 2,
    description: 'Rear delt and rotator', cues: ['Pull to forehead', 'External rotate'], timePerSet: 60,
    muscleActivations: [
      { muscleId: 'SH-005', activation: 90, role: 'primary' },
      { muscleId: 'SH-006', activation: 90, role: 'primary' },
      { muscleId: 'SH-012', activation: 65, role: 'secondary' },
      { muscleId: 'SH-013', activation: 65, role: 'secondary' },
      { muscleId: 'SH-018', activation: 65, role: 'secondary' },
      { muscleId: 'SH-019', activation: 65, role: 'secondary' },
    ]},
  { id: 'FW-PULL-004', name: 'Barbell Curl', path: 'freeweight', category: 'pull', difficulty: 1,
    description: 'Biceps isolation', cues: ['Elbows pinned', 'Full ROM'], timePerSet: 60,
    muscleActivations: [
      { muscleId: 'AR-001', activation: 90, role: 'primary' },
      { muscleId: 'AR-002', activation: 90, role: 'primary' },
      { muscleId: 'AR-003', activation: 85, role: 'primary' },
      { muscleId: 'AR-004', activation: 85, role: 'primary' },
      { muscleId: 'AR-005', activation: 70, role: 'secondary' },
      { muscleId: 'AR-006', activation: 70, role: 'secondary' },
    ]},
  { id: 'FW-LEGS-001', name: 'Barbell Back Squat', path: 'freeweight', category: 'legs', difficulty: 3,
    description: 'King of exercises', cues: ['Bar on traps', 'Brace hard'], timePerSet: 100,
    muscleActivations: [
      { muscleId: 'LA-003', activation: 90, role: 'primary' },
      { muscleId: 'LA-004', activation: 90, role: 'primary' },
      { muscleId: 'LA-001', activation: 85, role: 'primary' },
      { muscleId: 'LA-002', activation: 85, role: 'primary' },
      { muscleId: 'LA-005', activation: 85, role: 'primary' },
      { muscleId: 'LA-006', activation: 85, role: 'primary' },
      { muscleId: 'HG-001', activation: 80, role: 'primary' },
      { muscleId: 'HG-002', activation: 80, role: 'primary' },
      { muscleId: 'BA-003', activation: 65, role: 'stabilizer' },
      { muscleId: 'BA-004', activation: 65, role: 'stabilizer' },
    ]},
  { id: 'FW-LEGS-002', name: 'Leg Press', path: 'freeweight', category: 'legs', difficulty: 2,
    description: 'Machine quad focus', cues: ['Lower to 90°', 'Drive through heels'], timePerSet: 80,
    muscleActivations: [
      { muscleId: 'LA-003', activation: 85, role: 'primary' },
      { muscleId: 'LA-004', activation: 85, role: 'primary' },
      { muscleId: 'LA-001', activation: 80, role: 'primary' },
      { muscleId: 'LA-002', activation: 80, role: 'primary' },
      { muscleId: 'HG-001', activation: 65, role: 'secondary' },
      { muscleId: 'HG-002', activation: 65, role: 'secondary' },
    ]},
  { id: 'FW-LEGS-003', name: 'Leg Curl', path: 'freeweight', category: 'legs', difficulty: 1,
    description: 'Hamstring isolation', cues: ['Curl heels to glutes', 'Control eccentric'], timePerSet: 60,
    muscleActivations: [
      { muscleId: 'LP-001', activation: 85, role: 'primary' },
      { muscleId: 'LP-002', activation: 85, role: 'primary' },
      { muscleId: 'LP-003', activation: 90, role: 'primary' },
      { muscleId: 'LP-004', activation: 90, role: 'primary' },
      { muscleId: 'LP-005', activation: 85, role: 'primary' },
      { muscleId: 'LP-006', activation: 85, role: 'primary' },
    ]},
  { id: 'FW-LEGS-004', name: 'Leg Extension', path: 'freeweight', category: 'legs', difficulty: 1,
    description: 'Quad isolation', cues: ['Sit back', 'Squeeze at top'], timePerSet: 60,
    muscleActivations: [
      { muscleId: 'LA-001', activation: 90, role: 'primary' },
      { muscleId: 'LA-002', activation: 90, role: 'primary' },
      { muscleId: 'LA-005', activation: 95, role: 'primary' },
      { muscleId: 'LA-006', activation: 95, role: 'primary' },
      { muscleId: 'LA-003', activation: 85, role: 'primary' },
      { muscleId: 'LA-004', activation: 85, role: 'primary' },
    ]},
  { id: 'FW-LEGS-005', name: 'Standing Calf Raise', path: 'freeweight', category: 'legs', difficulty: 1,
    description: 'Calf isolation', cues: ['Full stretch', 'Peak squeeze'], timePerSet: 60,
    muscleActivations: [
      { muscleId: 'LP-009', activation: 90, role: 'primary' },
      { muscleId: 'LP-010', activation: 90, role: 'primary' },
      { muscleId: 'LP-011', activation: 85, role: 'primary' },
      { muscleId: 'LP-012', activation: 85, role: 'primary' },
    ]},
  { id: 'FW-HINGE-001', name: 'Conventional Deadlift', path: 'freeweight', category: 'hinge', difficulty: 4,
    description: 'Full-body pull', cues: ['Bar over mid-foot', 'Drive through floor'], timePerSet: 120,
    muscleActivations: [
      { muscleId: 'HG-001', activation: 90, role: 'primary' },
      { muscleId: 'HG-002', activation: 90, role: 'primary' },
      { muscleId: 'LP-001', activation: 85, role: 'primary' },
      { muscleId: 'LP-002', activation: 85, role: 'primary' },
      { muscleId: 'BA-003', activation: 85, role: 'primary' },
      { muscleId: 'BA-004', activation: 85, role: 'primary' },
      { muscleId: 'LA-003', activation: 65, role: 'secondary' },
      { muscleId: 'LA-004', activation: 65, role: 'secondary' },
      { muscleId: 'AR-015', activation: 80, role: 'stabilizer' },
      { muscleId: 'AR-016', activation: 80, role: 'stabilizer' },
    ]},
  { id: 'FW-HINGE-002', name: 'Romanian Deadlift', path: 'freeweight', category: 'hinge', difficulty: 3,
    description: 'Hip hinge for hamstrings', cues: ['Soft knees', 'Push hips back'], timePerSet: 80,
    muscleActivations: [
      { muscleId: 'LP-001', activation: 90, role: 'primary' },
      { muscleId: 'LP-002', activation: 90, role: 'primary' },
      { muscleId: 'LP-005', activation: 85, role: 'primary' },
      { muscleId: 'LP-006', activation: 85, role: 'primary' },
      { muscleId: 'HG-001', activation: 80, role: 'primary' },
      { muscleId: 'HG-002', activation: 80, role: 'primary' },
      { muscleId: 'BA-003', activation: 70, role: 'secondary' },
      { muscleId: 'BA-004', activation: 70, role: 'secondary' },
    ]},
  { id: 'FW-HINGE-003', name: 'Barbell Hip Thrust', path: 'freeweight', category: 'hinge', difficulty: 2,
    description: 'Loaded glute focus', cues: ['Bar on hips', 'Drive up'], timePerSet: 80,
    muscleActivations: [
      { muscleId: 'HG-001', activation: 95, role: 'primary' },
      { muscleId: 'HG-002', activation: 95, role: 'primary' },
      { muscleId: 'HG-003', activation: 65, role: 'secondary' },
      { muscleId: 'HG-004', activation: 65, role: 'secondary' },
    ]},
];

// Helper functions
export const getExercisesByPath = (path: EquipmentPath) => exercises.filter(e => e.path === path);
export const getExercisesByCategory = (cat: MovementCategory) => exercises.filter(e => e.category === cat);
export const getExerciseById = (id: string) => exercises.find(e => e.id === id);
export const searchExercises = (q: string) => {
  const lower = q.toLowerCase();
  return exercises.filter(e => e.name.toLowerCase().includes(lower) || e.description.toLowerCase().includes(lower));
};
