/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const __wbg_fixedwindowlimiter_free: (a: number, b: number) => void;
export const __wbg_get_ratelimitresult_allowed: (a: number) => number;
export const __wbg_get_ratelimitresult_current: (a: number) => number;
export const __wbg_get_ratelimitresult_limit: (a: number) => number;
export const __wbg_get_ratelimitresult_remaining: (a: number) => number;
export const __wbg_get_ratelimitresult_reset_seconds: (a: number) => number;
export const __wbg_ratelimiter_free: (a: number, b: number) => void;
export const __wbg_ratelimitresult_free: (a: number, b: number) => void;
export const __wbg_set_ratelimitresult_allowed: (a: number, b: number) => void;
export const __wbg_set_ratelimitresult_current: (a: number, b: number) => void;
export const __wbg_set_ratelimitresult_limit: (a: number, b: number) => void;
export const __wbg_set_ratelimitresult_remaining: (a: number, b: number) => void;
export const __wbg_set_ratelimitresult_reset_seconds: (a: number, b: number) => void;
export const __wbg_tokenbucket_free: (a: number, b: number) => void;
export const create_rate_limiter: (a: number, b: number) => number;
export const create_token_bucket: (a: number, b: number) => number;
export const fixedwindowlimiter_check: (a: number, b: number, c: number, d: number) => number;
export const fixedwindowlimiter_clear: (a: number) => void;
export const fixedwindowlimiter_new: (a: number, b: number) => number;
export const ratelimiter_check: (a: number, b: number, c: number, d: number) => number;
export const ratelimiter_check_only: (a: number, b: number, c: number) => number;
export const ratelimiter_clear: (a: number) => void;
export const ratelimiter_get_limit: (a: number) => number;
export const ratelimiter_get_window_seconds: (a: number) => number;
export const ratelimiter_new: (a: number, b: number) => number;
export const ratelimiter_remaining: (a: number, b: number, c: number) => number;
export const ratelimiter_reset_user: (a: number, b: number, c: number) => void;
export const ratelimiter_set_limit: (a: number, b: number) => void;
export const ratelimiter_user_count: (a: number) => number;
export const ratelimiter_with_capacity: (a: number, b: number, c: number) => number;
export const ratelimitresult_new: (a: number, b: number, c: number, d: number, e: number) => number;
export const tokenbucket_consume: (a: number, b: number) => number;
export const tokenbucket_get_tokens: (a: number) => number;
export const tokenbucket_reset: (a: number) => void;
export const tokenbucket_new: (a: number, b: number) => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_start: () => void;
