export {
  type PluginManifest,
  type PluginCreditAction,
  type PluginContext,
  type PluginRequestContext,
  type PluginLogger,
  type CreditService,
  type PluginDatabase,
  type PluginHooks,
  type CreditChargeEvent,
  type WorkoutCompletedEvent,
  type AdminPanel,
  type PluginRegistration,
  type PluginEntry,
  definePlugin,
  requireAuth,
  requirePermissions,
} from './backend';

export {
  type FrontendPluginManifest,
  type FrontendPluginRegistration,
  type PluginRoute,
  type PluginRouteProps,
  type PluginWidget,
  type WidgetSlot,
  type PluginWidgetProps,
  type PluginNavItem,
  type PluginCommand,
  type FrontendPluginContext,
  type PluginApiClient,
  type RequestOptions,
  type NotificationService,
  type NotificationOptions,
  type FrontendPluginHooks,
  type FrontendPluginEntry,
  definePlugin as defineFrontendPlugin,
  usePluginContext,
  useHasPermission,
  usePluginApi,
} from './frontend';
