/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const __wbg_get_loadprescription_percentage: (a: number) => number;
export const __wbg_get_loadprescription_reps: (a: number) => number;
export const __wbg_get_loadprescription_rest_seconds: (a: number) => number;
export const __wbg_get_loadprescription_rpe: (a: number) => number;
export const __wbg_get_loadprescription_sets: (a: number) => number;
export const __wbg_get_loadprescription_tempo: (a: number) => [number, number];
export const __wbg_get_loadprescription_weight_kg: (a: number) => number;
export const __wbg_loadprescription_free: (a: number, b: number) => void;
export const __wbg_onermresult_free: (a: number, b: number) => void;
export const __wbg_set_loadprescription_percentage: (a: number, b: number) => void;
export const __wbg_set_loadprescription_reps: (a: number, b: number) => void;
export const __wbg_set_loadprescription_rest_seconds: (a: number, b: number) => void;
export const __wbg_set_loadprescription_rpe: (a: number, b: number) => void;
export const __wbg_set_loadprescription_sets: (a: number, b: number) => void;
export const __wbg_set_loadprescription_tempo: (a: number, b: number, c: number) => void;
export const __wbg_set_loadprescription_weight_kg: (a: number, b: number) => void;
export const calculate_load: (a: number, b: number, c: number, d: number, e: number) => number;
export const calculate_loads_batch: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number) => [number, number, number];
export const estimate_1rm: (a: number, b: number, c: number) => number;
export const get_phase_rep_range: (a: number) => [number, number];
export const get_phase_rpe_range: (a: number) => [number, number];
export const loadprescription_new: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number) => number;
export const onermresult_new: (a: number, b: number, c: number, d: number) => number;
export const parse_tempo: (a: number, b: number) => number;
export const percentage_to_rpe: (a: number, b: number) => number;
export const progressive_overload: (a: number, b: number, c: number, d: number) => number;
export const rpe_to_percentage: (a: number, b: number) => number;
export const time_under_tension: (a: number, b: number, c: number) => number;
export const __wbg_set_onermresult_formula: (a: number, b: number, c: number) => void;
export const __wbg_set_onermresult_confidence: (a: number, b: number) => void;
export const __wbg_set_onermresult_estimated_1rm: (a: number, b: number) => void;
export const __wbg_get_onermresult_formula: (a: number) => [number, number];
export const __wbg_get_onermresult_confidence: (a: number) => number;
export const __wbg_get_onermresult_estimated_1rm: (a: number) => number;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __externref_table_dealloc: (a: number) => void;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __wbindgen_start: () => void;
