/**
 * MuscleMap Unified Icon Component
 *
 * A single component that wraps multiple icon libraries with
 * consistent theming matching the Liquid Glass design system.
 *
 * Supported libraries:
 * - Lucide React (default)
 * - Phosphor Icons
 * - MUI Icons
 * - Custom fitness/muscle icons
 */

import { forwardRef } from 'react';
import { getIconSize, getIconColor, getIconWeight, iconColors } from './iconTheme';

// Re-export commonly used Lucide icons
import {
  // Navigation
  Home,
  Menu,
  X,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  ChevronDown,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  ArrowDown,
  ExternalLink,

  // Actions
  Plus,
  Minus,
  Check,
  Search,
  Filter,
  Settings,
  Edit,
  Trash2,
  Copy,
  Share2,
  Download,
  Upload,
  RefreshCw,
  MoreHorizontal,
  MoreVertical,

  // User & Social
  User,
  Users,
  UserPlus,
  UserCheck,
  Heart,
  Star,
  ThumbsUp,
  MessageCircle,
  Bell,
  Mail,

  // Fitness & Health
  Activity,
  Flame,
  Timer,
  Clock,
  Calendar,
  Target,
  Trophy,
  Award,
  Zap,
  TrendingUp,
  TrendingDown,
  BarChart3,
  PieChart,

  // Media
  Play,
  Pause,
  SkipForward,
  SkipBack,
  Volume2,
  VolumeX,
  Camera,
  Image,
  Video,

  // Status & Feedback
  Info,
  AlertCircle,
  AlertTriangle,
  CheckCircle,
  XCircle,
  HelpCircle,
  Loader2,

  // Misc
  Sun,
  Moon,
  Eye,
  EyeOff,
  Lock,
  Unlock,
  LogIn,
  LogOut,
  Dumbbell,
  Bike,
  Footprints,
  HeartPulse,
  Brain,
  Sparkles,
  Crown,
  Bookmark,
  BookmarkCheck,
  Map,
  MapPin,
  Compass,
  Send,
  Maximize2,
  Minimize2,
  Grid,
  List,
  LayoutGrid,
  Grip,
} from 'lucide-react';

// Re-export Phosphor icons with different weight options
import {
  // Fitness icons with weight variants
  Barbell as PhBarbell,
  PersonSimpleRun as PhRun,
  PersonSimpleWalk as PhWalk,
  PersonSimpleBike as PhBike,
  PersonSimpleSwim as PhSwim,
  Heartbeat as PhHeartbeat,
  Fire as PhFire,
  Lightning as PhLightning,
  Trophy as PhTrophy,
  Medal as PhMedal,
  Target as PhTarget,
  ChartLineUp as PhChartLineUp,
  Timer as PhTimer,
  Clock as PhClock,
  CalendarBlank as PhCalendar,
  Scales as PhScales,
  Ruler as PhRuler,
  Drop as PhDrop,
  Moon as PhMoon,
  SunDim as PhSun,
  BatteryFull as PhBattery,
  Pulse as PhPulse,
  FirstAid as PhFirstAid,
  Stethoscope as PhStethoscope,
  Pill as PhPill,
  Apple as PhApple,
  Coffee as PhCoffee,
  ForkKnife as PhForkKnife,
  House as PhHouse,
  Gear as PhGear,
  User as PhUser,
  Users as PhUsers,
  UserCircle as PhUserCircle,
  Star as PhStar,
  Heart as PhHeart,
  ThumbsUp as PhThumbsUp,
  ChatCircle as PhChatCircle,
  Bell as PhBell,
  MagnifyingGlass as PhSearch,
  Plus as PhPlus,
  Minus as PhMinus,
  Check as PhCheck,
  X as PhX,
  CaretLeft as PhCaretLeft,
  CaretRight as PhCaretRight,
  CaretUp as PhCaretUp,
  CaretDown as PhCaretDown,
  ArrowLeft as PhArrowLeft,
  ArrowRight as PhArrowRight,
  Play as PhPlay,
  Pause as PhPause,
  Stop as PhStop,
  SkipForward as PhSkipForward,
  SkipBack as PhSkipBack,
  Repeat as PhRepeat,
  Shuffle as PhShuffle,
  ListBullets as PhList,
  SquaresFour as PhGrid,
  DotsThree as PhDotsThree,
  DotsThreeVertical as PhDotsThreeVertical,
  PencilSimple as PhPencil,
  Trash as PhTrash,
  Copy as PhCopy,
  Share as PhShare,
  DownloadSimple as PhDownload,
  UploadSimple as PhUpload,
  ArrowsClockwise as PhRefresh,
  Eye as PhEye,
  EyeSlash as PhEyeSlash,
  Lock as PhLock,
  LockOpen as PhLockOpen,
  SignIn as PhSignIn,
  SignOut as PhSignOut,
  Info as PhInfo,
  Warning as PhWarning,
  WarningCircle as PhWarningCircle,
  CheckCircle as PhCheckCircle,
  XCircle as PhXCircle,
  Question as PhQuestion,
  Spinner as PhSpinner,
  CircleNotch as PhLoader,
  MapPin as PhMapPin,
  Compass as PhCompass,
  GlobeHemisphereWest as PhGlobe,
  Envelope as PhEnvelope,
  PaperPlaneTilt as PhSend,
  Image as PhImage,
  Camera as PhCamera,
  VideoCamera as PhVideo,
  SpeakerHigh as PhVolume,
  SpeakerSlash as PhVolumeMute,
  Bookmark as PhBookmark,
  BookmarkSimple as PhBookmarkSimple,
  Crown as PhCrown,
  Sparkle as PhSparkle,
  Lightning as PhZap,
  Flame as PhFlame,
} from '@phosphor-icons/react';

/**
 * Icon component with consistent theming
 */
const Icon = forwardRef(function Icon(
  {
    // Icon selection
    name,
    library = 'lucide', // 'lucide' | 'phosphor' | 'mui' | 'custom'

    // Styling
    size = 'md',
    color,
    weight = 'regular',
    className = '',

    // Phosphor-specific
    mirrored = false,

    // Additional props
    ...props
  },
  ref
) {
  const computedSize = getIconSize(size);
  const computedColor = getIconColor(color);
  const computedWeight = getIconWeight(weight);

  const baseProps = {
    ref,
    size: computedSize,
    color: computedColor,
    strokeWidth: computedWeight,
    className: `mm-icon ${className}`.trim(),
    ...props,
  };

  // Phosphor props differ slightly
  const phosphorProps = {
    ref,
    size: computedSize,
    color: computedColor,
    weight: weight === 'thin' ? 'thin' : weight === 'light' ? 'light' : weight === 'bold' ? 'bold' : 'regular',
    mirrored,
    className: `mm-icon ${className}`.trim(),
    ...props,
  };

  // Get the icon component based on library and name
  const IconComponent = getIconComponent(name, library);

  if (!IconComponent) {
    console.warn(`Icon "${name}" not found in library "${library}"`);
    return null;
  }

  return library === 'phosphor'
    ? <IconComponent {...phosphorProps} />
    : <IconComponent {...baseProps} />;
});

/**
 * Get icon component by name and library
 */
function getIconComponent(name, library) {
  if (library === 'phosphor') {
    return phosphorIcons[name];
  }
  // Default to Lucide
  return lucideIcons[name];
}

// Icon lookup maps
const lucideIcons = {
  // Navigation
  home: Home,
  menu: Menu,
  close: X,
  x: X,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  chevronUp: ChevronUp,
  chevronDown: ChevronDown,
  arrowLeft: ArrowLeft,
  arrowRight: ArrowRight,
  arrowUp: ArrowUp,
  arrowDown: ArrowDown,
  externalLink: ExternalLink,

  // Actions
  plus: Plus,
  add: Plus,
  minus: Minus,
  check: Check,
  search: Search,
  filter: Filter,
  settings: Settings,
  edit: Edit,
  delete: Trash2,
  trash: Trash2,
  copy: Copy,
  share: Share2,
  download: Download,
  upload: Upload,
  refresh: RefreshCw,
  moreHorizontal: MoreHorizontal,
  moreVertical: MoreVertical,

  // User & Social
  user: User,
  users: Users,
  userPlus: UserPlus,
  userCheck: UserCheck,
  heart: Heart,
  like: Heart,
  star: Star,
  favorite: Star,
  thumbsUp: ThumbsUp,
  comment: MessageCircle,
  message: MessageCircle,
  notification: Bell,
  bell: Bell,
  mail: Mail,
  email: Mail,

  // Fitness & Health
  activity: Activity,
  workout: Activity,
  flame: Flame,
  fire: Flame,
  calories: Flame,
  timer: Timer,
  clock: Clock,
  time: Clock,
  calendar: Calendar,
  schedule: Calendar,
  target: Target,
  goal: Target,
  trophy: Trophy,
  achievement: Trophy,
  award: Award,
  medal: Award,
  energy: Zap,
  zap: Zap,
  lightning: Zap,
  trendingUp: TrendingUp,
  progress: TrendingUp,
  trendingDown: TrendingDown,
  decline: TrendingDown,
  chart: BarChart3,
  stats: BarChart3,
  barChart: BarChart3,
  pieChart: PieChart,
  dumbbell: Dumbbell,
  weights: Dumbbell,
  bike: Bike,
  cycling: Bike,
  footprints: Footprints,
  steps: Footprints,
  walking: Footprints,
  heartPulse: HeartPulse,
  heartRate: HeartPulse,
  brain: Brain,
  mind: Brain,

  // Media
  play: Play,
  pause: Pause,
  skipForward: SkipForward,
  next: SkipForward,
  skipBack: SkipBack,
  previous: SkipBack,
  volume: Volume2,
  volumeMute: VolumeX,
  mute: VolumeX,
  camera: Camera,
  photo: Camera,
  image: Image,
  picture: Image,
  video: Video,

  // Status & Feedback
  info: Info,
  information: Info,
  alert: AlertCircle,
  alertCircle: AlertCircle,
  warning: AlertTriangle,
  alertTriangle: AlertTriangle,
  success: CheckCircle,
  checkCircle: CheckCircle,
  error: XCircle,
  xCircle: XCircle,
  help: HelpCircle,
  helpCircle: HelpCircle,
  loader: Loader2,
  loading: Loader2,
  spinner: Loader2,

  // Misc
  sun: Sun,
  light: Sun,
  moon: Moon,
  dark: Moon,
  eye: Eye,
  show: Eye,
  visible: Eye,
  eyeOff: EyeOff,
  hide: EyeOff,
  hidden: EyeOff,
  lock: Lock,
  locked: Lock,
  unlock: Unlock,
  unlocked: Unlock,
  login: LogIn,
  signIn: LogIn,
  logout: LogOut,
  signOut: LogOut,
  sparkles: Sparkles,
  magic: Sparkles,
  ai: Sparkles,
  crown: Crown,
  premium: Crown,
  pro: Crown,
  bookmark: Bookmark,
  save: Bookmark,
  bookmarkCheck: BookmarkCheck,
  saved: BookmarkCheck,
  map: Map,
  mapPin: MapPin,
  location: MapPin,
  compass: Compass,
  direction: Compass,
  send: Send,
  submit: Send,
  maximize: Maximize2,
  fullscreen: Maximize2,
  minimize: Minimize2,
  exitFullscreen: Minimize2,
  grid: Grid,
  gridView: LayoutGrid,
  list: List,
  listView: List,
  drag: Grip,
  grip: Grip,
};

const phosphorIcons = {
  // Fitness (Phosphor has better fitness icons)
  barbell: PhBarbell,
  weights: PhBarbell,
  dumbbell: PhBarbell,
  run: PhRun,
  running: PhRun,
  walk: PhWalk,
  walking: PhWalk,
  bike: PhBike,
  cycling: PhBike,
  swim: PhSwim,
  swimming: PhSwim,
  heartbeat: PhHeartbeat,
  heartRate: PhHeartbeat,
  pulse: PhPulse,
  fire: PhFire,
  flame: PhFlame,
  calories: PhFlame,
  lightning: PhLightning,
  energy: PhLightning,
  zap: PhZap,
  trophy: PhTrophy,
  achievement: PhTrophy,
  medal: PhMedal,
  award: PhMedal,
  target: PhTarget,
  goal: PhTarget,
  chartLineUp: PhChartLineUp,
  progress: PhChartLineUp,
  stats: PhChartLineUp,
  timer: PhTimer,
  stopwatch: PhTimer,
  clock: PhClock,
  time: PhClock,
  calendar: PhCalendar,
  schedule: PhCalendar,
  scales: PhScales,
  weight: PhScales,
  ruler: PhRuler,
  height: PhRuler,
  drop: PhDrop,
  water: PhDrop,
  hydration: PhDrop,
  battery: PhBattery,
  energy: PhBattery,

  // Health
  firstAid: PhFirstAid,
  medical: PhFirstAid,
  stethoscope: PhStethoscope,
  doctor: PhStethoscope,
  pill: PhPill,
  medication: PhPill,

  // Nutrition
  apple: PhApple,
  fruit: PhApple,
  healthy: PhApple,
  coffee: PhCoffee,
  caffeine: PhCoffee,
  forkKnife: PhForkKnife,
  meal: PhForkKnife,
  food: PhForkKnife,
  nutrition: PhForkKnife,

  // Navigation
  home: PhHouse,
  house: PhHouse,
  settings: PhGear,
  gear: PhGear,
  user: PhUser,
  profile: PhUserCircle,
  userCircle: PhUserCircle,
  users: PhUsers,
  community: PhUsers,

  // Social
  star: PhStar,
  favorite: PhStar,
  heart: PhHeart,
  like: PhHeart,
  thumbsUp: PhThumbsUp,
  chat: PhChatCircle,
  comment: PhChatCircle,
  bell: PhBell,
  notification: PhBell,
  search: PhSearch,
  find: PhSearch,

  // Actions
  plus: PhPlus,
  add: PhPlus,
  minus: PhMinus,
  check: PhCheck,
  x: PhX,
  close: PhX,
  caretLeft: PhCaretLeft,
  caretRight: PhCaretRight,
  caretUp: PhCaretUp,
  caretDown: PhCaretDown,
  arrowLeft: PhArrowLeft,
  arrowRight: PhArrowRight,
  play: PhPlay,
  pause: PhPause,
  stop: PhStop,
  skipForward: PhSkipForward,
  skipBack: PhSkipBack,
  repeat: PhRepeat,
  shuffle: PhShuffle,
  list: PhList,
  grid: PhGrid,
  dots: PhDotsThree,
  dotsVertical: PhDotsThreeVertical,
  edit: PhPencil,
  pencil: PhPencil,
  delete: PhTrash,
  trash: PhTrash,
  copy: PhCopy,
  share: PhShare,
  download: PhDownload,
  upload: PhUpload,
  refresh: PhRefresh,
  eye: PhEye,
  show: PhEye,
  eyeSlash: PhEyeSlash,
  hide: PhEyeSlash,
  lock: PhLock,
  lockOpen: PhLockOpen,
  unlock: PhLockOpen,
  signIn: PhSignIn,
  login: PhSignIn,
  signOut: PhSignOut,
  logout: PhSignOut,

  // Status
  info: PhInfo,
  warning: PhWarning,
  warningCircle: PhWarningCircle,
  checkCircle: PhCheckCircle,
  success: PhCheckCircle,
  xCircle: PhXCircle,
  error: PhXCircle,
  question: PhQuestion,
  help: PhQuestion,
  spinner: PhSpinner,
  loader: PhLoader,
  loading: PhLoader,

  // Misc
  mapPin: PhMapPin,
  location: PhMapPin,
  compass: PhCompass,
  direction: PhCompass,
  globe: PhGlobe,
  world: PhGlobe,
  envelope: PhEnvelope,
  email: PhEnvelope,
  mail: PhEnvelope,
  send: PhSend,
  image: PhImage,
  photo: PhImage,
  camera: PhCamera,
  video: PhVideo,
  volume: PhVolume,
  volumeMute: PhVolumeMute,
  mute: PhVolumeMute,
  bookmark: PhBookmark,
  save: PhBookmarkSimple,
  crown: PhCrown,
  premium: PhCrown,
  sparkle: PhSparkle,
  magic: PhSparkle,
  ai: PhSparkle,
  sun: PhSun,
  light: PhSun,
  moon: PhMoon,
  dark: PhMoon,
};

// Export individual icons for direct use
export {
  // Lucide
  Home,
  Menu,
  X,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  ChevronDown,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  ArrowDown,
  ExternalLink,
  Plus,
  Minus,
  Check,
  Search,
  Filter,
  Settings,
  Edit,
  Trash2,
  Copy,
  Share2,
  Download,
  Upload,
  RefreshCw,
  MoreHorizontal,
  MoreVertical,
  User,
  Users,
  UserPlus,
  UserCheck,
  Heart,
  Star,
  ThumbsUp,
  MessageCircle,
  Bell,
  Mail,
  Activity,
  Flame,
  Timer,
  Clock,
  Calendar,
  Target,
  Trophy,
  Award,
  Zap,
  TrendingUp,
  TrendingDown,
  BarChart3,
  PieChart,
  Play,
  Pause,
  SkipForward,
  SkipBack,
  Volume2,
  VolumeX,
  Camera,
  Image,
  Video,
  Info,
  AlertCircle,
  AlertTriangle,
  CheckCircle,
  XCircle,
  HelpCircle,
  Loader2,
  Sun,
  Moon,
  Eye,
  EyeOff,
  Lock,
  Unlock,
  LogIn,
  LogOut,
  Dumbbell,
  Bike,
  Footprints,
  HeartPulse,
  Brain,
  Sparkles,
  Crown,
  Bookmark,
  BookmarkCheck,
  Map,
  MapPin,
  Compass,
  Send,
  Maximize2,
  Minimize2,
  Grid,
  List,
  LayoutGrid,
  Grip,
};

// Export Phosphor icons
export {
  PhBarbell,
  PhRun,
  PhWalk,
  PhBike,
  PhSwim,
  PhHeartbeat,
  PhFire,
  PhLightning,
  PhTrophy,
  PhMedal,
  PhTarget,
  PhChartLineUp,
  PhTimer,
  PhClock,
  PhCalendar,
  PhScales,
  PhRuler,
  PhDrop,
  PhPulse,
  PhFirstAid,
  PhStethoscope,
  PhPill,
  PhApple,
  PhCoffee,
  PhForkKnife,
  PhFlame,
};

// Export theme utilities
export { iconSizes, iconWeights, iconColors } from './iconTheme';

export default Icon;
