/**
 * GraphQL Module Exports
 *
 * Single entry point for all GraphQL-related imports
 */

// Apollo Client
export { apolloClient, default } from './client';

// Queries
export {
  // Auth & User
  ME_QUERY,
  MY_CAPABILITIES_QUERY,

  // Profile
  PROFILE_QUERY,

  // Exercises & Muscles
  EXERCISES_QUERY,
  EXERCISE_QUERY,
  MUSCLES_QUERY,
  MY_MUSCLE_ACTIVATIONS_QUERY,
  EXERCISE_HISTORY_QUERY,
  EXERCISE_SUBSTITUTIONS_QUERY,

  // Workouts
  MY_WORKOUTS_QUERY,
  MY_WORKOUT_STATS_QUERY,
  WORKOUT_QUERY,

  // Workout Sessions
  ACTIVE_WORKOUT_SESSION_QUERY,
  WORKOUT_SESSION_QUERY,
  RECOVERABLE_SESSIONS_QUERY,
  WORKOUT_MUSCLE_BREAKDOWN_QUERY,

  // Goals
  GOALS_QUERY,
  GOAL_SUGGESTIONS_QUERY,

  // Journey & Archetypes
  JOURNEY_QUERY,
  JOURNEY_OVERVIEW_QUERY,
  ARCHETYPES_QUERY,

  // Stats
  MY_STATS_QUERY,
  LEADERBOARDS_QUERY,

  // Community
  PUBLIC_COMMUNITY_STATS_QUERY,
  COMMUNITY_STATS_QUERY,
  COMMUNITY_FEED_QUERY,
  COMMUNITY_PRESENCE_QUERY,

  // Economy
  CREDITS_BALANCE_QUERY,
  ECONOMY_BALANCE_QUERY,
  ECONOMY_WALLET_QUERY,
  ECONOMY_PRICING_QUERY,
  ECONOMY_HISTORY_QUERY,
  MY_ENTITLEMENTS_QUERY,
  MY_WALLET_INFO_QUERY,
  MY_PERSONAL_RECORDS_QUERY,

  // Tips
  TIPS_QUERY,

  // Health
  HEALTH_QUERY,
  HEALTH_DETAILED_QUERY,

  // Messaging
  CONVERSATIONS_QUERY,
  CONVERSATION_MESSAGES_QUERY,
  PINNED_MESSAGES_QUERY,
  TYPING_USERS_QUERY,
  USER_PRESENCE_QUERY,
  BLOCK_STATUS_QUERY,
  MESSAGE_TEMPLATES_QUERY,
  SCHEDULED_MESSAGES_QUERY,
  SEARCH_MESSAGES_QUERY,
  SEARCH_USERS_QUERY,

  // Issues & Roadmap
  ISSUES_QUERY,
  ISSUE_QUERY,
  ISSUE_LABELS_QUERY,
  ISSUE_STATS_QUERY,
  MY_ISSUES_QUERY,
  ROADMAP_QUERY,
  UPDATES_QUERY,

  // Achievements
  ACHIEVEMENTS_QUERY,
  ACHIEVEMENT_DEFINITIONS_QUERY,
  MY_ACHIEVEMENTS_QUERY,
  MY_ACHIEVEMENT_SUMMARY_QUERY,

  // Skills
  SKILL_TREES_QUERY,
  SKILL_TREE_QUERY,
  SKILL_TREE_PROGRESS_QUERY,
  SKILL_SUMMARY_QUERY,
  SKILL_PROGRESS_QUERY,

  // Martial Arts
  MARTIAL_ARTS_PROGRESS_QUERY,
  MARTIAL_ARTS_DISCIPLINES_QUERY,
  MARTIAL_ARTS_DISCIPLINE_QUERY,
  MARTIAL_ARTS_TECHNIQUES_QUERY,
  MARTIAL_ARTS_DISCIPLINE_PROGRESS_QUERY,
  MARTIAL_ARTS_DISCIPLINE_LEADERBOARD_QUERY,
  MARTIAL_ARTS_PRACTICE_HISTORY_QUERY,

  // Prescription
  PRESCRIPTION_QUERY,

  // Competitions
  COMPETITIONS_QUERY,
  MY_COMPETITION_ENTRIES_QUERY,

  // Trainers & Classes
  TRAINERS_QUERY,
  MY_TRAINER_PROFILE_QUERY,
  CLASSES_QUERY,

  // Notifications
  NOTIFICATIONS_QUERY,
  NOTIFICATION_UNREAD_COUNT_QUERY,

  // Buddy
  BUDDY_QUERY,
  BUDDY_INVENTORY_QUERY,
  BUDDY_EVOLUTION_PATH_QUERY,
  BUDDY_LEADERBOARD_QUERY,

  // Collection
  COLLECTION_STATS_QUERY,
  COLLECTION_ITEMS_QUERY,
  COLLECTION_FAVORITES_QUERY,
  COLLECTION_SETS_QUERY,
  COLLECTION_SET_DETAIL_QUERY,
  COLLECTION_SHOWCASE_QUERY,
  COLLECTION_NEW_COUNT_QUERY,

  // Marketplace
  MARKETPLACE_LISTINGS_QUERY,
  MARKETPLACE_WATCHLIST_QUERY,
  MARKETPLACE_STATS_QUERY,

  // Trades
  TRADES_INCOMING_QUERY,
  TRADES_OUTGOING_QUERY,
  TRADES_HISTORY_QUERY,
  TRADE_QUERY,

  // Mystery Boxes
  MYSTERY_BOXES_QUERY,
  MYSTERY_BOX_QUERY,
  MYSTERY_BOX_HISTORY_QUERY,
  MYSTERY_BOX_PITY_QUERY,

  // Skins
  SKINS_QUERY,
  OWNED_SKINS_QUERY,
  EQUIPPED_SKINS_QUERY,
  UNLOCKABLE_SKINS_QUERY,

  // Admin
  ADMIN_USERS_QUERY,
  ADMIN_FEEDBACK_STATS_QUERY,
  ADMIN_BUGS_STATS_QUERY,
  ADMIN_TEST_SCORECARD_QUERY,

  // Limitations
  MY_LIMITATIONS_QUERY,
  BODY_REGIONS_QUERY,

  // PT Tests
  PT_TESTS_QUERY,
  PT_TESTS_BY_INSTITUTION_QUERY,
  PT_TEST_QUERY,
  MY_ARCHETYPE_PT_TEST_QUERY,
  PT_TEST_RESULTS_QUERY,
  PT_TEST_RESULT_QUERY,
  PT_TEST_LEADERBOARD_QUERY,

  // Career Readiness
  CAREER_STANDARDS_QUERY,
  CAREER_STANDARD_QUERY,
  CAREER_STANDARD_CATEGORIES_QUERY,
  MY_CAREER_GOALS_QUERY,
  CAREER_EXERCISE_RECOMMENDATIONS_QUERY,

  // Progress Photos
  PROGRESS_PHOTOS_QUERY,
  PROGRESS_PHOTO_QUERY,
  PROGRESS_PHOTO_TIMELINE_QUERY,
  PROGRESS_PHOTO_COMPARISON_QUERY,
  PROGRESS_PHOTO_STATS_QUERY,
} from './queries';

// Mutations
export {
  // Auth
  REGISTER_MUTATION,
  LOGIN_MUTATION,

  // Profile
  UPDATE_PROFILE_MUTATION,

  // Workouts
  CREATE_WORKOUT_MUTATION,
  PREVIEW_WORKOUT_MUTATION,

  // Workout Sessions
  START_WORKOUT_SESSION_MUTATION,
  LOG_SET_MUTATION,
  UPDATE_SET_MUTATION,
  DELETE_SET_MUTATION,
  PAUSE_WORKOUT_SESSION_MUTATION,
  RESUME_WORKOUT_SESSION_MUTATION,
  COMPLETE_WORKOUT_SESSION_MUTATION,
  ABANDON_WORKOUT_SESSION_MUTATION,
  RECOVER_WORKOUT_SESSION_MUTATION,

  // Goals
  CREATE_GOAL_MUTATION,
  UPDATE_GOAL_MUTATION,
  DELETE_GOAL_MUTATION,

  // Archetypes
  SELECT_ARCHETYPE_MUTATION,

  // Economy
  CHARGE_CREDITS_MUTATION,
  TRANSFER_CREDITS_BY_USERNAME_MUTATION,

  // Tips
  MARK_TIP_SEEN_MUTATION,

  // Logging
  LOG_FRONTEND_ERROR_MUTATION,

  // Messaging
  CREATE_CONVERSATION_MUTATION,
  SEND_MESSAGE_MUTATION,
  EDIT_MESSAGE_MUTATION,
  MARK_CONVERSATION_READ_MUTATION,
  DELETE_MESSAGE_MUTATION,
  PIN_MESSAGE_MUTATION,
  UNPIN_MESSAGE_MUTATION,
  ADD_REACTION_MUTATION,
  REMOVE_REACTION_MUTATION,
  SET_TYPING_STATUS_MUTATION,
  STAR_CONVERSATION_MUTATION,
  UNSTAR_CONVERSATION_MUTATION,
  ARCHIVE_CONVERSATION_MUTATION,
  UNARCHIVE_CONVERSATION_MUTATION,
  FORWARD_MESSAGE_MUTATION,
  SET_DISAPPEARING_MESSAGES_MUTATION,
  SCHEDULE_MESSAGE_MUTATION,
  CANCEL_SCHEDULED_MESSAGE_MUTATION,
  CREATE_MESSAGE_TEMPLATE_MUTATION,
  BLOCK_USER_MUTATION,
  UNBLOCK_USER_MUTATION,

  // Issues
  CREATE_ISSUE_MUTATION,
  UPDATE_ISSUE_MUTATION,
  VOTE_ON_ISSUE_MUTATION,
  CREATE_ISSUE_COMMENT_MUTATION,
  SUBSCRIBE_TO_ISSUE_MUTATION,

  // Roadmap
  CREATE_ROADMAP_ITEM_MUTATION,
  VOTE_ON_ROADMAP_ITEM_MUTATION,

  // Skills
  PRACTICE_SKILL_MUTATION,
  LOG_SKILL_PRACTICE_MUTATION,
  ACHIEVE_SKILL_MUTATION,

  // Martial Arts
  PRACTICE_MARTIAL_ART_MUTATION,
  MASTER_MARTIAL_ART_MUTATION,
  UPDATE_MARTIAL_ART_NOTES_MUTATION,

  // Prescription
  GENERATE_PRESCRIPTION_MUTATION,

  // Competitions
  JOIN_COMPETITION_MUTATION,
  CREATE_COMPETITION_MUTATION,

  // Trainers & Classes
  UPDATE_TRAINER_PROFILE_MUTATION,
  CREATE_CLASS_MUTATION,

  // Buddy
  CREATE_BUDDY_MUTATION,
  UPDATE_BUDDY_MUTATION,
  UPDATE_BUDDY_NICKNAME_MUTATION,
  UPDATE_BUDDY_SETTINGS_MUTATION,
  FEED_BUDDY_MUTATION,
  EQUIP_BUDDY_ITEM_MUTATION,
  UNEQUIP_BUDDY_ITEM_MUTATION,

  // Collection
  TOGGLE_FAVORITE_MUTATION,
  MARK_ITEM_SEEN_MUTATION,
  MARK_ALL_SEEN_MUTATION,
  CLAIM_SET_REWARD_MUTATION,

  // Marketplace
  CREATE_LISTING_MUTATION,
  PURCHASE_LISTING_MUTATION,
  MAKE_OFFER_MUTATION,
  ADD_TO_WATCHLIST_MUTATION,
  REMOVE_FROM_WATCHLIST_MUTATION,

  // Trades
  CREATE_TRADE_MUTATION,
  ACCEPT_TRADE_MUTATION,
  REJECT_TRADE_MUTATION,
  CANCEL_TRADE_MUTATION,

  // Mystery Boxes
  OPEN_MYSTERY_BOX_MUTATION,

  // Skins
  PURCHASE_SKIN_MUTATION,
  EQUIP_SKIN_MUTATION,
  UNEQUIP_SKIN_MUTATION,

  // Feedback
  SUBMIT_FEEDBACK_MUTATION,

  // Admin
  ADMIN_ADJUST_CREDITS_MUTATION,
  ADMIN_BAN_USER_MUTATION,
  ADMIN_GRANT_ACHIEVEMENT_MUTATION,
  ADMIN_BULK_UPDATE_ISSUES_MUTATION,

  // Community
  UPDATE_PRESENCE_MUTATION,

  // Limitations
  CREATE_LIMITATION_MUTATION,
  UPDATE_LIMITATION_MUTATION,
  DELETE_LIMITATION_MUTATION,

  // PT Tests
  RECORD_PT_TEST_RESULT_MUTATION,

  // Career Readiness
  CREATE_CAREER_GOAL_MUTATION,

  // Progress Photos
  CREATE_PROGRESS_PHOTO_MUTATION,
  UPDATE_PROGRESS_PHOTO_MUTATION,
  DELETE_PROGRESS_PHOTO_MUTATION,
} from './mutations';
