/**
 * GraphQL Module Exports
 *
 * Single entry point for all GraphQL-related imports
 */

// Apollo Client
export { apolloClient, default } from './client';

// Queries
export {
  ME_QUERY,
  MY_CAPABILITIES_QUERY,
  EXERCISES_QUERY,
  EXERCISE_QUERY,
  MUSCLES_QUERY,
  MY_WORKOUTS_QUERY,
  MY_WORKOUT_STATS_QUERY,
  WORKOUT_QUERY,
  GOALS_QUERY,
  JOURNEY_QUERY,
  ARCHETYPES_QUERY,
  MY_STATS_QUERY,
  LEADERBOARDS_QUERY,
  PUBLIC_COMMUNITY_STATS_QUERY,
  COMMUNITY_STATS_QUERY,
  CREDITS_BALANCE_QUERY,
  ECONOMY_BALANCE_QUERY,
  TIPS_QUERY,
  HEALTH_QUERY,
  HEALTH_DETAILED_QUERY,
  // Workout Sessions
  ACTIVE_WORKOUT_SESSION_QUERY,
  WORKOUT_SESSION_QUERY,
  RECOVERABLE_SESSIONS_QUERY,
  WORKOUT_MUSCLE_BREAKDOWN_QUERY,
  EXERCISE_SUBSTITUTIONS_QUERY,
  EXERCISE_HISTORY_QUERY,
} from './queries';

// Mutations
export {
  REGISTER_MUTATION,
  LOGIN_MUTATION,
  UPDATE_PROFILE_MUTATION,
  CREATE_WORKOUT_MUTATION,
  PREVIEW_WORKOUT_MUTATION,
  CREATE_GOAL_MUTATION,
  DELETE_GOAL_MUTATION,
  SELECT_ARCHETYPE_MUTATION,
  CHARGE_CREDITS_MUTATION,
  MARK_TIP_SEEN_MUTATION,
  LOG_FRONTEND_ERROR_MUTATION,
  // Workout Sessions
  START_WORKOUT_SESSION_MUTATION,
  LOG_SET_MUTATION,
  UPDATE_SET_MUTATION,
  DELETE_SET_MUTATION,
  PAUSE_WORKOUT_SESSION_MUTATION,
  RESUME_WORKOUT_SESSION_MUTATION,
  COMPLETE_WORKOUT_SESSION_MUTATION,
  ABANDON_WORKOUT_SESSION_MUTATION,
  RECOVER_WORKOUT_SESSION_MUTATION,
} from './mutations';
